(function () {
  "use strict";

  const rows = [
    ["homeowner", "/ˈhəʊməʊnə(r)/", "noun", "房主；自有住房者", "a person who owns the home in which they live", "support local homeowners", "The council offers energy advice to local homeowners.", "市政部门为当地房主提供节能建议。", "海外生活"],
    ["tenant", "/ˈtenənt/", "noun", "租户；房客", "a person who pays to live in a rented property", "a new tenant", "Each tenant receives a copy of the building rules.", "每位租户都会收到一份楼宇规定。", "海外生活"],
    ["residence", "/ˈrezɪdəns/", "noun", "住所；居住地", "the place where a person officially lives", "proof of residence", "The bank asked me to provide proof of residence.", "银行要求我提供居住证明。", "海外生活"],
    ["deposit", "/dɪˈpɒzɪt/", "noun", "押金；保证金", "money paid in advance and returned if no damage is caused", "pay a security deposit", "We paid a one-month deposit before moving in.", "入住前，我们支付了一个月的押金。", "海外生活"],
    ["lease", "/liːs/", "noun", "租约；租赁合同", "a legal agreement that allows someone to use property for a period", "sign a lease", "Please read the lease carefully before you sign it.", "签署租约前请仔细阅读。", "海外生活"],
    ["utility", "/juːˈtɪləti/", "noun", "公用事业费；公共服务", "a service such as water, gas, or electricity", "monthly utility bills", "Our monthly utility bills are higher in winter.", "冬季我们的每月公用事业费更高。", "海外生活"],
    ["electricity", "/ɪˌlekˈtrɪsəti/", "noun", "电；电力", "a form of energy used for light, heat, and machines", "save electricity", "Turn off the lights when you leave to save electricity.", "离开时关灯以节约用电。", "海外生活"],
    ["plumbing", "/ˈplʌmɪŋ/", "noun", "管道系统；水暖设施", "the system of water pipes and equipment in a building", "a plumbing problem", "A plumbing problem caused water to leak under the sink.", "管道问题导致水从水槽下方漏出。", "海外生活"],
    ["maintenance", "/ˈmeɪntənəns/", "noun", "维护；保养工作", "work done to keep a building or machine in good condition", "request maintenance", "Residents can request maintenance through the building portal.", "住户可以通过楼宇平台申请维护服务。", "海外生活"],
    ["neighborhood", "/ˈneɪbəhʊd/", "noun", "街区；社区周边", "the area of a town or city where people live", "a quiet neighborhood", "We chose this neighborhood because it is safe and convenient.", "我们选择这个街区，因为它安全又便利。", "海外生活"],
    ["community", "/kəˈmjuːnəti/", "noun", "社区；群体", "the people living in a particular area or sharing interests", "join the local community", "Volunteering helped me become part of the local community.", "志愿服务帮助我融入了当地社区。", "海外生活"],
    ["housing", "/ˈhaʊzɪŋ/", "noun", "住房；住宅供应", "homes provided for people to live in", "affordable housing", "The university helps international students find suitable housing.", "大学帮助国际学生寻找合适的住房。", "海外生活"],
    ["resident", "/ˈrezɪdənt/", "noun", "居民；住户", "a person who lives in a particular place", "local residents", "Local residents can apply for a parking permit.", "当地居民可以申请停车许可证。", "海外生活"],
    ["property", "/ˈprɒpəti/", "noun", "房产；财产", "a building, land, or possessions owned by someone", "rental property", "The owner checks the property once a year.", "房主每年检查一次出租房产。", "海外生活"],
    ["tenancy", "/ˈtenənsi/", "noun", "租住期；租赁关系", "the period or legal arrangement in which someone rents a property", "end a tenancy", "Give the landlord one month's notice before ending the tenancy.", "结束租住前要提前一个月通知房东。", "海外生活"],
    ["insurance", "/ɪnˈʃʊərəns/", "noun", "保险；保险保障", "an arrangement that provides payment after loss or damage", "travel insurance", "My insurance covers emergency medical treatment abroad.", "我的保险涵盖海外紧急医疗。", "海外生活"],
    ["emergency", "/ɪˈmɜːdʒənsi/", "noun", "紧急情况；突发事件", "a serious and unexpected situation needing immediate action", "in an emergency", "Call this number if there is an emergency in the building.", "楼内如有紧急情况，请拨打这个号码。", "海外生活"],
    ["healthcare", "/ˈhelθkeə(r)/", "noun", "医疗保健；医疗服务", "services that maintain or improve people's health", "access local healthcare", "New residents receive a guide to accessing local healthcare.", "新住户会收到一份当地医疗服务使用指南。", "海外生活"],
    ["registration", "/ˌredʒɪˈstreɪʃn/", "noun", "登记；注册", "the process of recording a name or information officially", "complete the registration", "You must complete your address registration within two weeks.", "你必须在两周内完成住址登记。", "海外生活"],
    ["permit", "/ˈpɜːmɪt/", "noun", "许可证；许可文件", "an official document allowing someone to do something", "apply for a permit", "She applied for a work permit before accepting the job.", "她在接受工作前申请了工作许可证。", "海外生活"],
    ["embassy", "/ˈembəsi/", "noun", "大使馆", "the official office of one country in another country", "contact the embassy", "The embassy provided information about replacing my passport.", "大使馆提供了补办护照的信息。", "海外生活"],
    ["consulate", "/ˈkɒnsjələt/", "noun", "领事馆", "an office that helps its country's citizens in a foreign city", "visit the consulate", "I booked an appointment at the consulate for Monday.", "我预约了周一去领事馆办理事务。", "海外生活"],
    ["customs", "/ˈkʌstəmz/", "plural noun", "海关；海关检查", "the official department that checks goods entering a country", "go through customs", "We collected our bags and then went through customs.", "我们取完行李后通过了海关。", "海外生活"],
    ["immigration", "/ˌɪmɪˈɡreɪʃn/", "noun", "入境管理；移民事务", "the process and control of people entering a country to live", "pass through immigration", "Keep your documents ready when you pass through immigration.", "通过入境检查时请准备好证件。", "海外生活"],

    ["application", "/ˌæplɪˈkeɪʃn/", "noun", "申请；申请材料", "a formal request for a job, course, or service", "submit an application", "I submitted my application before the closing date.", "我在截止日期前提交了申请。", "求职准备"],
    ["profile", "/ˈprəʊfaɪl/", "noun", "职业简介；个人概况", "a short description of a person's skills and experience", "write a professional profile", "Begin your application with a clear professional profile.", "在申请材料开头写一段清晰的职业简介。", "求职准备"],
    ["referee", "/ˌrefəˈriː/", "noun", "推荐人；证明人", "a person who gives information about a job applicant", "name a referee", "Ask permission before naming someone as a referee.", "将某人列为推荐人前要先征得同意。", "求职准备"],
    ["employer", "/ɪmˈplɔɪə(r)/", "noun", "雇主；用人单位", "a person or organization that employs people", "a potential employer", "A potential employer may check your online profile.", "潜在雇主可能会查看你的网络资料。", "求职准备"],
    ["employee", "/ɪmˈplɔɪiː/", "noun", "雇员；员工", "a person paid to work for an organization", "a full-time employee", "Every new employee completes an orientation program.", "每位新员工都要完成入职培训。", "求职准备"],
    ["position", "/pəˈzɪʃn/", "noun", "职位；岗位", "a paid job in an organization", "apply for a position", "She applied for a position in customer operations.", "她申请了客户运营岗位。", "求职准备"],
    ["career", "/kəˈrɪə(r)/", "noun", "职业生涯；事业", "the series of jobs a person has during working life", "build a career", "I hope to build a career in international business.", "我希望在国际商务领域发展事业。", "求职准备"],
    ["skill", "/skɪl/", "noun", "技能；本领", "an ability developed through training or experience", "develop a practical skill", "The course helped me develop practical workplace skills.", "这门课程帮助我培养了实用的职场技能。", "求职准备"],
    ["ability", "/əˈbɪləti/", "noun", "能力；才干", "the power or skill needed to do something", "demonstrate your ability", "The task will demonstrate your ability to analyze information.", "这项任务将展示你分析信息的能力。", "求职准备"],
    ["available", "/əˈveɪləbl/", "adjective", "有空的；可任职的", "free and able to start or do something", "available to start", "I am available to start work at the beginning of May.", "我可以在五月初开始工作。", "求职准备"],
    ["flexible", "/ˈfleksəbl/", "adjective", "灵活的；可调整的", "able and willing to change according to circumstances", "a flexible schedule", "I am flexible about working hours during busy periods.", "在繁忙时期，我可以灵活调整工作时间。", "求职准备"],
    ["degree", "/dɪˈɡriː/", "noun", "学位；学历", "a qualification awarded after completing university study", "hold a degree in", "She holds a degree in business administration.", "她拥有工商管理学位。", "求职准备"],
    ["graduate", "/ˈɡrædʒuət/", "noun", "大学毕业生；毕业者", "a person who has completed a university course", "a recent graduate", "The program is designed for recent graduates with limited experience.", "该项目面向工作经验有限的应届毕业生。", "求职准备"],
    ["trainee", "/ˌtreɪˈniː/", "noun", "实习生；受训人员", "a person learning the skills needed for a job", "a management trainee", "As a trainee, I rotated through three departments.", "作为实习生，我轮岗了三个部门。", "求职准备"],
    ["employment", "/ɪmˈplɔɪmənt/", "noun", "就业；受雇", "paid work or the state of having a job", "seek employment", "The service helps international graduates seek employment.", "这项服务帮助国际毕业生寻找工作。", "求职准备"],
    ["occupation", "/ˌɒkjuˈpeɪʃn/", "noun", "职业；工作类别", "a person's regular job or profession", "state your occupation", "The form asks you to state your current occupation.", "表格要求填写你目前的职业。", "求职准备"],
    ["industry", "/ˈɪndəstri/", "noun", "行业；产业", "a particular area of business or economic activity", "work in the industry", "Networking events can help you learn more about the industry.", "行业交流活动能帮助你深入了解该行业。", "求职准备"],
    ["company", "/ˈkʌmpəni/", "noun", "公司；企业", "an organization that sells goods or services", "research a company", "Research the company before writing your cover letter.", "写求职信前要先研究这家公司。", "求职准备"],
    ["organization", "/ˌɔːɡənaɪˈzeɪʃn/", "noun", "组织；机构", "a group formed for a particular purpose", "join an organization", "I want to join an organization that values learning.", "我希望加入重视学习的机构。", "求职准备"],
    ["apply", "/əˈplaɪ/", "verb", "申请；应聘", "to formally ask for a job or opportunity", "apply for a role", "You can apply for the role through the company website.", "你可以通过公司网站申请该职位。", "求职准备"],
    ["advertise", "/ˈædvətaɪz/", "verb", "刊登招聘；宣传", "to make a job, product, or service known publicly", "advertise a vacancy", "The agency advertised the vacancy on several job boards.", "该机构在多个招聘网站发布了职位。", "求职准备"],
    ["shortlist", "/ˈʃɔːtlɪst/", "verb", "列入候选名单", "to choose a small group of candidates for further consideration", "shortlist candidates", "The recruiter shortlisted six candidates for interview.", "招聘人员选出六名候选人参加面试。", "求职准备"],
    ["offer", "/ˈɒfə(r)/", "noun / verb", "录用通知；提供", "a proposal to give someone a job or opportunity", "receive a job offer", "He received a job offer after the final interview.", "终面后，他收到了录用通知。", "求职准备"],
    ["decline", "/dɪˈklaɪn/", "verb", "谢绝；婉拒", "to politely refuse an offer or request", "decline an offer", "She declined the offer because the location was unsuitable.", "她因工作地点不合适而谢绝了录用。", "求职准备"],

    ["interview", "/ˈɪntəvjuː/", "noun / verb", "面试；采访", "a formal meeting in which someone is asked questions", "attend an interview", "I attended an online interview with the regional manager.", "我参加了区域经理主持的线上面试。", "面试沟通"],
    ["interviewer", "/ˈɪntəvjuːə(r)/", "noun", "面试官；采访者", "a person who asks questions during an interview", "ask the interviewer", "Ask the interviewer one thoughtful question at the end.", "结束时可以向面试官提出一个有思考的问题。", "面试沟通"],
    ["applicant", "/ˈæplɪkənt/", "noun", "申请人；求职者", "a person who formally asks for a job or place", "a successful applicant", "Successful applicants will be contacted within five days.", "成功入选的申请人将在五天内收到联系。", "面试沟通"],
    ["introduction", "/ˌɪntrəˈdʌkʃn/", "noun", "介绍；开场说明", "the act of presenting someone or something for the first time", "give a brief introduction", "Begin with a brief introduction of your background.", "先简要介绍一下你的背景。", "面试沟通"],
    ["personality", "/ˌpɜːsəˈnæləti/", "noun", "性格；个性", "the qualities that make a person's character", "describe your personality", "My personality suits roles that involve regular customer contact.", "我的性格适合需要经常接触顾客的岗位。", "面试沟通"],
    ["attitude", "/ˈætɪtjuːd/", "noun", "态度；看法", "the way someone thinks or feels about something", "a positive attitude", "A positive attitude helped our team during a difficult week.", "积极的态度帮助团队度过了艰难的一周。", "面试沟通"],
    ["behavior", "/bɪˈheɪvjə(r)/", "noun", "行为；表现", "the way a person acts in a situation", "professional behavior", "The interviewer asked about professional behavior under pressure.", "面试官询问了压力下的职业表现。", "面试沟通"],
    ["knowledge", "/ˈnɒlɪdʒ/", "noun", "知识；了解", "information and understanding gained through learning or experience", "industry knowledge", "I developed basic industry knowledge during my internship.", "我在实习期间积累了基础行业知识。", "面试沟通"],
    ["talent", "/ˈtælənt/", "noun", "才能；天赋", "a natural ability to do something well", "develop your talent", "The role would allow me to develop my talent for organization.", "这个职位能让我发挥组织方面的才能。", "面试沟通"],
    ["honest", "/ˈɒnɪst/", "adjective", "诚实的；坦诚的", "truthful and not intending to deceive", "give an honest answer", "Give an honest answer if you lack experience in one area.", "如果某方面经验不足，要坦诚回答。", "面试沟通"],
    ["creative", "/kriˈeɪtɪv/", "adjective", "有创造力的；创新的", "able to produce original and useful ideas", "a creative approach", "I used a creative approach to attract more visitors.", "我采用了有创意的方法来吸引更多访客。", "面试沟通"],
    ["independent", "/ˌɪndɪˈpendənt/", "adjective", "独立的；自主的", "able to work or act without needing much help", "work independently", "I can work independently while keeping my manager informed.", "我能独立工作，同时及时向经理汇报。", "面试沟通"],
    ["willing", "/ˈwɪlɪŋ/", "adjective", "愿意的；乐意的", "ready and prepared to do something", "willing to learn", "I am willing to learn unfamiliar systems quickly.", "我愿意快速学习不熟悉的系统。", "面试沟通"],
    ["ambitious", "/æmˈbɪʃəs/", "adjective", "有抱负的；进取的", "determined to be successful or achieve difficult goals", "an ambitious goal", "I am ambitious, but I also value steady progress.", "我有进取心，同时也重视稳步成长。", "面试沟通"],
    ["nervous", "/ˈnɜːvəs/", "adjective", "紧张的；不安的", "worried or slightly afraid about what may happen", "feel nervous about", "It is normal to feel nervous before an important interview.", "重要面试前感到紧张很正常。", "面试沟通"],
    ["punctual", "/ˈpʌŋktʃuəl/", "adjective", "准时的；守时的", "arriving or doing something at the agreed time", "be punctual for work", "My previous manager described me as reliable and punctual.", "我的前经理认为我可靠且守时。", "面试沟通"],
    ["statement", "/ˈsteɪtmənt/", "noun", "陈述；说明", "a clear expression of facts, opinions, or intentions", "prepare a personal statement", "Prepare a short statement explaining your career goal.", "准备一段说明职业目标的简短陈述。", "面试沟通"],
    ["example", "/ɪɡˈzɑːmpl/", "noun", "例子；事例", "a case used to explain or prove something", "give a practical example", "Give a practical example of how you solved a problem.", "举一个你如何解决问题的实际事例。", "面试沟通"],
    ["reason", "/ˈriːzn/", "noun", "原因；理由", "a fact that explains why something happens or is done", "explain the reason", "Explain the reason you are interested in this position.", "说明你对这个职位感兴趣的原因。", "面试沟通"],
    ["success", "/səkˈses/", "noun", "成功；成功成果", "the achievement of a desired result", "measure success", "We measured success by the reduction in waiting time.", "我们通过等待时间的缩短来衡量成果。", "面试沟通"],
    ["failure", "/ˈfeɪljə(r)/", "noun", "失败；未能实现", "a lack of success in doing or achieving something", "learn from failure", "The experience taught me how to learn from failure.", "这段经历教会了我如何从失败中学习。", "面试沟通"],
    ["accept", "/əkˈsept/", "verb", "接受；同意接纳", "to agree to receive or take something offered", "accept a job offer", "I accepted the offer after confirming the working hours.", "确认工作时间后，我接受了录用。", "面试沟通"],
    ["availability", "/əˌveɪləˈbɪləti/", "noun", "可任职时间；空闲情况", "the times when someone is free or able to work", "confirm your availability", "Please confirm your availability for a second interview.", "请确认你参加第二轮面试的时间。", "面试沟通"],
    ["select", "/sɪˈlekt/", "verb", "挑选；选中", "to choose someone or something from a group", "select the best candidate", "The panel will select the best candidate next week.", "评审组将在下周选出最合适的候选人。", "面试沟通"],

    ["agenda", "/əˈdʒendə/", "noun", "议程；待办事项", "a list of subjects to be discussed at a meeting", "prepare an agenda", "I sent the agenda one day before the meeting.", "我在会议前一天发送了议程。", "职场沟通"],
    ["minutes", "/ˈmɪnɪts/", "plural noun", "会议记录；纪要", "the official written record of a meeting", "take meeting minutes", "Maya took the minutes and shared them with the team.", "玛雅记录了会议纪要并分享给团队。", "职场沟通"],
    ["memo", "/ˈmeməʊ/", "noun", "备忘录；内部通知", "a short written message used inside an organization", "send an internal memo", "The director sent a memo about the new office policy.", "主管发送了一份关于新办公政策的备忘录。", "职场沟通"],
    ["attachment", "/əˈtætʃmənt/", "noun", "附件；附加文件", "a file sent with an email", "open an attachment", "Please check the attachment for the revised schedule.", "请在附件中查看修改后的日程。", "职场沟通"],
    ["reply", "/rɪˈplaɪ/", "noun / verb", "回复；答复", "to answer a message, question, or request", "reply to an email", "I will reply to the client's email before noon.", "我会在中午前回复客户邮件。", "职场沟通"],
    ["forward", "/ˈfɔːwəd/", "verb", "转发；转交", "to send a received message or document to another person", "forward a message", "Could you forward the message to the finance team?", "你能把这条消息转发给财务团队吗？", "职场沟通"],
    ["announce", "/əˈnaʊns/", "verb", "宣布；公布", "to make information publicly or officially known", "announce a change", "Management announced the change at the weekly meeting.", "管理层在周会上公布了这项变更。", "职场沟通"],
    ["notify", "/ˈnəʊtɪfaɪ/", "verb", "通知；告知", "to formally tell someone about something", "notify employees", "Please notify employees if the office closes early.", "如果办公室提前关闭，请通知员工。", "职场沟通"],
    ["consult", "/kənˈsʌlt/", "verb", "征求意见；咨询", "to ask someone for information or advice", "consult a colleague", "I consulted a colleague who had handled a similar case.", "我咨询了一位处理过类似情况的同事。", "职场沟通"],
    ["suggest", "/səˈdʒest/", "verb", "建议；提出", "to offer an idea or plan for consideration", "suggest an alternative", "She suggested an alternative date for the workshop.", "她为研讨会建议了另一个日期。", "职场沟通"],
    ["agree", "/əˈɡriː/", "verb", "同意；达成一致", "to have the same opinion or accept a proposal", "agree on a deadline", "We agreed on a realistic deadline for the report.", "我们就报告的合理截止日期达成了一致。", "职场沟通"],
    ["disagree", "/ˌdɪsəˈɡriː/", "verb", "不同意；持不同意见", "to have a different opinion", "politely disagree", "You can disagree politely and explain your evidence.", "你可以礼貌地表示不同意并说明依据。", "职场沟通"],
    ["conversation", "/ˌkɒnvəˈseɪʃn/", "noun", "交谈；对话", "an informal talk between two or more people", "have a private conversation", "We had a private conversation about the workload.", "我们私下讨论了工作量问题。", "职场沟通"],
    ["communication", "/kəˌmjuːnɪˈkeɪʃn/", "noun", "沟通；信息交流", "the process of sharing information and ideas", "improve team communication", "Clear roles improve communication across the team.", "明确的职责能改善团队沟通。", "职场沟通"],
    ["brief", "/briːf/", "adjective", "简短的；简明的", "lasting only a short time or using few words", "a brief update", "I gave the manager a brief update after the call.", "通话后，我向经理做了简短汇报。", "职场沟通"],
    ["casual", "/ˈkæʒuəl/", "adjective", "非正式的；随意的", "relaxed and not formal", "a casual message", "A casual message is fine for the team chat.", "团队聊天中使用非正式消息是可以的。", "职场沟通"],
    ["polite", "/pəˈlaɪt/", "adjective", "礼貌的；客气的", "showing respect and good manners", "make a polite request", "Use a polite request when asking someone to repeat.", "请别人重复时要使用礼貌的请求。", "职场沟通"],
    ["direct", "/dəˈrekt/", "adjective", "直接的；明确的", "clear and honest without unnecessary words", "a direct question", "The client asked a direct question about the cost.", "客户直接询问了费用问题。", "职场沟通"],
    ["specific", "/spəˈsɪfɪk/", "adjective", "具体的；明确的", "clearly defined and exact", "give specific details", "Please give specific details about the technical problem.", "请提供有关技术问题的具体细节。", "职场沟通"],
    ["general", "/ˈdʒenrəl/", "adjective", "总体的；一般性的", "relating to the main features rather than details", "a general overview", "The first slide gives a general overview of the project.", "第一张幻灯片概述了整个项目。", "职场沟通"],
    ["issue", "/ˈɪʃuː/", "noun", "问题；待处理事项", "a problem or subject that needs attention", "raise an issue", "Please raise the issue before it affects the deadline.", "请在问题影响截止日期前提出。", "职场沟通"],
    ["concern", "/kənˈsɜːn/", "noun", "担忧；关注事项", "a worry or matter that someone considers important", "express a concern", "Several employees expressed concern about the new schedule.", "几名员工表达了对新排班的担忧。", "职场沟通"],
    ["comment", "/ˈkɒment/", "noun / verb", "评论；意见", "a spoken or written opinion about something", "add a comment", "Add your comments directly to the shared document.", "请直接在共享文档中添加意见。", "职场沟通"],
    ["response", "/rɪˈspɒns/", "noun", "回应；答复", "an answer or reaction to something", "receive a response", "We expect a response from the supplier by Friday.", "我们预计周五前收到供应商的答复。", "职场沟通"],

    ["service", "/ˈsɜːvɪs/", "noun", "服务；服务项目", "work done to help customers or meet a need", "provide excellent service", "Our goal is to provide fast and friendly service.", "我们的目标是提供快速友好的服务。", "客户服务"],
    ["client", "/ˈklaɪənt/", "noun", "客户；委托人", "a person or organization receiving professional services", "meet a new client", "We will meet the new client on Tuesday morning.", "我们将在周二上午与新客户会面。", "客户服务"],
    ["product", "/ˈprɒdʌkt/", "noun", "产品；商品", "something made or sold by a business", "explain a product", "Staff must be able to explain the product clearly.", "员工必须能够清楚介绍产品。", "客户服务"],
    ["item", "/ˈaɪtəm/", "noun", "物品；商品项目", "one particular thing in a group or list", "a missing item", "The customer reported a missing item in the package.", "顾客报告包裹中少了一件商品。", "客户服务"],
    ["quality", "/ˈkwɒləti/", "noun", "质量；品质", "how good or bad something is", "check the quality", "We check the quality before sending each order.", "我们在发出每份订单前检查质量。", "客户服务"],
    ["quantity", "/ˈkwɒntəti/", "noun", "数量；数额", "the amount or number of something", "confirm the quantity", "Could you confirm the quantity you would like to order?", "你能确认一下想订购的数量吗？", "客户服务"],
    ["resolution", "/ˌrezəˈluːʃn/", "noun", "解决结果；处理方案", "a successful way of settling a problem or complaint", "reach a resolution", "The agent worked with the customer to reach a fair resolution.", "客服专员与顾客共同达成了公平的处理方案。", "客户服务"],
    ["replace", "/rɪˈpleɪs/", "verb", "更换；替换", "to provide a new thing instead of a damaged or lost one", "replace a damaged item", "We can replace the damaged item at no extra cost.", "我们可以免费更换损坏的商品。", "客户服务"],
    ["cancellation", "/ˌkænsəˈleɪʃn/", "noun", "取消；撤销", "the act of stopping an arrangement or service", "request a cancellation", "The guest requested a cancellation because of illness.", "客人因生病申请取消预订。", "客户服务"],
    ["reimbursement", "/ˌriːɪmˈbɜːsmənt/", "noun", "报销款；费用偿还", "money paid back to someone for costs they have already paid", "request reimbursement", "The customer requested reimbursement for the return postage.", "顾客申请报销退货邮费。", "客户服务"],
    ["agent", "/ˈeɪdʒənt/", "noun", "客服专员；代理人", "a person who acts for a company or helps customers", "speak to an agent", "Please stay on the line to speak to an agent.", "请不要挂断，等待客服专员接听。", "客户服务"],
    ["representative", "/ˌreprɪˈzentətɪv/", "noun", "代表；客服代表", "a person who speaks or acts for an organization", "customer service representative", "A representative will contact you within one business day.", "客服代表将在一个工作日内联系你。", "客户服务"],
    ["dissatisfied", "/dɪsˈsætɪsfaɪd/", "adjective", "不满意的；不满的", "not pleased with a product, service, or result", "a dissatisfied customer", "The customer was dissatisfied with the repair result.", "顾客对维修结果不满意。", "客户服务"],
    ["satisfied", "/ˈsætɪsfaɪd/", "adjective", "满意的；满足的", "pleased because expectations have been met", "be satisfied with", "Are you satisfied with the solution we provided?", "你对我们提供的解决方案满意吗？", "客户服务"],
    ["disappointed", "/ˌdɪsəˈpɔɪntɪd/", "adjective", "失望的；沮丧的", "unhappy because something was worse than expected", "feel disappointed", "I understand why you feel disappointed about the delay.", "我理解这次延误为何让你失望。", "客户服务"],
    ["helpful", "/ˈhelpfl/", "adjective", "有帮助的；乐于助人的", "giving useful assistance or information", "a helpful explanation", "The support agent gave me a very helpful explanation.", "客服专员给了我非常有帮助的说明。", "客户服务"],
    ["attentive", "/əˈtentɪv/", "adjective", "周到的；专心倾听的", "carefully noticing and responding to someone's needs", "attentive service", "Attentive service helps customers feel understood.", "周到的服务能让顾客感到自己被理解。", "客户服务"],
    ["solve", "/sɒlv/", "verb", "解决；处理好", "to find an answer to a problem", "solve a customer problem", "We solved the payment problem during the call.", "我们在通话中解决了付款问题。", "客户服务"],
    ["handle", "/ˈhændl/", "verb", "处理；应对", "to deal with a situation, task, or person", "handle a difficult case", "She handled the difficult case patiently and professionally.", "她耐心而专业地处理了棘手情况。", "客户服务"],
    ["hold", "/həʊld/", "noun / verb", "等候；保持通话", "to wait on a telephone line", "put a caller on hold", "Ask permission before putting a caller on hold.", "让来电者等候前要先征得同意。", "客户服务"],
    ["transfer", "/trænsˈfɜː(r)/", "verb", "转接；转交", "to move a call or case to another person or department", "transfer a call", "I will transfer your call to the billing department.", "我会把你的电话转接到结算部门。", "客户服务"],
    ["patience", "/ˈpeɪʃns/", "noun", "耐心；忍耐力", "the ability to remain calm while waiting or facing difficulty", "show patience", "Good service requires patience with confused customers.", "优质服务需要耐心对待感到困惑的顾客。", "客户服务"],
    ["courtesy", "/ˈkɜːtəsi/", "noun", "礼貌；礼遇", "polite behavior that shows respect", "treat someone with courtesy", "Treat every caller with courtesy, even during busy periods.", "即使在繁忙时段，也要礼貌对待每位来电者。", "客户服务"],
    ["follow-up", "/ˈfɒləʊ ʌp/", "noun", "后续跟进；进一步联系", "an action taken to check or continue an earlier matter", "send a follow-up", "I sent a follow-up to confirm that the issue was fixed.", "我进行了后续联系，确认问题已经解决。", "客户服务"],

    ["brand", "/brænd/", "noun", "品牌；牌子", "a named type of product made by a company", "a well-known brand", "This brand is popular with younger shoppers.", "这个品牌很受年轻顾客欢迎。", "零售运营"],
    ["label", "/ˈleɪbl/", "noun", "标签；标牌", "a piece of paper or material giving product information", "read the label", "Check the label for washing instructions before purchase.", "购买前请查看标签上的洗涤说明。", "零售运营"],
    ["package", "/ˈpækɪdʒ/", "noun", "包裹；包装件", "an object wrapped or boxed for transport or sale", "open a package", "The package arrived in good condition this morning.", "包裹今天上午完好送达。", "零售运营"],
    ["packaging", "/ˈpækɪdʒɪŋ/", "noun", "包装材料；包装设计", "materials used to cover and protect a product", "recyclable packaging", "Customers increasingly prefer recyclable packaging.", "顾客越来越偏好可回收包装。", "零售运营"],
    ["checkout", "/ˈtʃekaʊt/", "noun", "收银台；结账处", "the place or process where customers pay in a shop", "wait at the checkout", "We opened another checkout to reduce the queue.", "我们增开了一个收银台以缩短队伍。", "零售运营"],
    ["counter", "/ˈkaʊntə(r)/", "noun", "柜台；服务台", "a long flat surface where goods are sold or service is provided", "the service counter", "Please take the return to the service counter.", "请把退货商品带到服务台。", "零售运营"],
    ["aisle", "/aɪl/", "noun", "过道；货架通道", "a passage between rows of shelves or seats", "walk down an aisle", "Cleaning products are in aisle twelve.", "清洁用品在十二号通道。", "零售运营"],
    ["cart", "/kɑːt/", "noun", "购物车；手推车", "a wheeled container used for carrying goods in a store", "push a shopping cart", "Please return the shopping cart near the entrance.", "请把购物车归还到入口附近。", "零售运营"],
    ["shopper", "/ˈʃɒpə(r)/", "noun", "购物者；顾客", "a person who is buying things in shops", "online shoppers", "Online shoppers expect clear delivery information.", "线上购物者希望看到清晰的配送信息。", "零售运营"],
    ["markdown", "/ˈmɑːkdaʊn/", "noun", "降价；标价下调", "a reduction in the selling price of a product", "apply a markdown", "The manager approved a markdown on the remaining winter coats.", "经理批准下调剩余冬季外套的价格。", "零售运营"],
    ["clearance", "/ˈklɪərəns/", "noun", "清仓销售；清货", "a sale intended to remove remaining goods quickly", "a clearance sale", "The clearance sale applies only to last season's stock.", "清仓销售只适用于上一季的存货。", "零售运营"],
    ["coupon", "/ˈkuːpɒn/", "noun", "优惠券；折价券", "a document or code that reduces a price", "use a coupon", "Enter the coupon code before completing payment.", "完成付款前请输入优惠码。", "零售运营"],
    ["credit", "/ˈkredɪt/", "noun", "赊购额度；账户余额", "money added to an account or allowed for later payment", "receive store credit", "You may receive store credit instead of cash.", "你可以获得商店余额而不是现金退款。", "零售运营"],
    ["debit", "/ˈdebɪt/", "noun", "借记；账户扣款", "a payment taken directly from a bank account", "pay by debit card", "The customer paid by debit card at the checkout.", "顾客在收银台使用借记卡付款。", "零售运营"],
    ["subtotal", "/ˈsʌbtəʊtl/", "noun", "小计；部分合计", "the total before tax, delivery, or other charges", "calculate the subtotal", "The subtotal appears above the delivery fee.", "小计显示在配送费上方。", "零售运营"],
    ["tax", "/tæks/", "noun", "税；税款", "money charged by a government on goods, income, or services", "include sales tax", "The displayed price already includes sales tax.", "标示价格已经包含销售税。", "零售运营"],
    ["total", "/ˈtəʊtl/", "noun / adjective", "总额；全部的", "the complete amount after everything is added", "check the total", "Please check the total before you confirm payment.", "确认付款前请核对总额。", "零售运营"],
    ["branch", "/brɑːntʃ/", "noun", "分店；分支机构", "one local office or shop belonging to a larger organization", "visit a local branch", "This item is available at our central branch.", "这件商品在我们的中心分店有货。", "零售运营"],
    ["membership", "/ˈmembəʃɪp/", "noun", "会员资格；会员制度", "the state of belonging to a group or program", "renew a membership", "Members receive a reminder before their membership expires.", "会员资格到期前会收到提醒。", "零售运营"],
    ["manager", "/ˈmænɪdʒə(r)/", "noun", "经理；管理人员", "a person responsible for controlling a team or business", "speak to the manager", "The manager approved the exchange immediately.", "经理立即批准了换货。", "零售运营"],
    ["assistant", "/əˈsɪstənt/", "noun", "助理；店员", "a person whose job is to help another person or customers", "sales assistant", "A sales assistant showed me where to find the item.", "一名店员告诉我在哪里可以找到那件商品。", "零售运营"],
    ["store", "/stɔː(r)/", "noun", "商店；门店", "a place where goods are sold", "visit the store", "The store stays open until nine on weekdays.", "这家门店工作日营业到晚上九点。", "零售运营"],
    ["marketplace", "/ˈmɑːkɪtpleɪs/", "noun", "交易平台；市场环境", "a physical or online place where buyers and sellers meet", "an online marketplace", "The brand began selling through an international marketplace.", "该品牌开始通过国际交易平台销售商品。", "零售运营"],
    ["outlet", "/ˈaʊtlet/", "noun", "销售门店；经销点", "a shop or place through which products are sold", "a retail outlet", "The company opened a smaller retail outlet near the station.", "公司在车站附近开了一家较小的销售门店。", "零售运营"],

    ["project", "/ˈprɒdʒekt/", "noun", "项目；计划任务", "a planned piece of work with a particular purpose", "lead a project", "Our team is starting a six-week customer research project.", "我们的团队正启动一个为期六周的顾客研究项目。", "项目协作"],
    ["phase", "/feɪz/", "noun", "阶段；时期", "one part of a process or project", "the first phase", "The first phase focuses on collecting user feedback.", "第一阶段重点收集用户反馈。", "项目协作"],
    ["timeline", "/ˈtaɪmlaɪn/", "noun", "时间线；进度安排", "a plan showing when project activities will happen", "create a timeline", "We created a realistic timeline for every major task.", "我们为每项主要任务制定了合理的时间安排。", "项目协作"],
    ["target", "/ˈtɑːɡɪt/", "noun", "目标；指标", "a result or level that someone aims to achieve", "meet a target", "The sales team met its monthly target early.", "销售团队提前完成了月度目标。", "项目协作"],
    ["action", "/ˈækʃn/", "noun", "行动；措施", "something done to achieve a result or deal with a problem", "take immediate action", "We took immediate action after receiving the test results.", "收到测试结果后，我们立即采取了行动。", "项目协作"],
    ["status", "/ˈsteɪtəs/", "noun", "状态；进展情况", "the current condition or stage of something", "check the project status", "You can check the project status on the shared board.", "你可以在共享看板上查看项目状态。", "项目协作"],
    ["role", "/rəʊl/", "noun", "角色；职责", "the function or responsibility someone has in a group", "define each role", "We defined each person's role at the first meeting.", "我们在第一次会议上明确了每个人的职责。", "项目协作"],
    ["member", "/ˈmembə(r)/", "noun", "成员；会员", "a person who belongs to a group or team", "a team member", "Each team member owns at least one task.", "每位团队成员至少负责一项任务。", "项目协作"],
    ["complete", "/kəmˈpliːt/", "verb", "完成；结束", "to finish making or doing something", "complete a task", "Please complete the draft before Thursday afternoon.", "请在周四下午前完成草稿。", "项目协作"],
    ["achieve", "/əˈtʃiːv/", "verb", "实现；达到", "to successfully reach a goal through effort", "achieve a goal", "Regular reviews helped us achieve the project goal.", "定期审查帮助我们实现了项目目标。", "项目协作"],
    ["deliver", "/dɪˈlɪvə(r)/", "verb", "交付；提供成果", "to provide something promised or completed", "deliver on time", "The design team delivered the final files on time.", "设计团队按时交付了最终文件。", "项目协作"],
    ["develop", "/dɪˈveləp/", "verb", "开发；逐步形成", "to create or improve something over time", "develop a new process", "We developed a simpler process for handling requests.", "我们开发了一套更简单的请求处理流程。", "项目协作"],
    ["design", "/dɪˈzaɪn/", "noun / verb", "设计；规划", "to plan how something will look or work", "design a solution", "The group designed a solution based on customer needs.", "小组根据顾客需求设计了解决方案。", "项目协作"],
    ["involve", "/ɪnˈvɒlv/", "verb", "涉及；让……参与", "to include someone or something in an activity", "involve the whole team", "Important changes should involve the whole team.", "重要变更应让整个团队参与。", "项目协作"],
    ["manage", "/ˈmænɪdʒ/", "verb", "管理；设法完成", "to control work, resources, or a situation", "manage a project", "She manages several small projects at the same time.", "她同时管理多个小型项目。", "项目协作"],
    ["measure", "/ˈmeʒə(r)/", "verb", "衡量；测量", "to judge the size, amount, or success of something", "measure progress", "We measure progress against three clear indicators.", "我们用三个明确指标衡量进展。", "项目协作"],
    ["compare", "/kəmˈpeə(r)/", "verb", "比较；对照", "to examine things to see how they are similar or different", "compare two options", "The team compared two options before making a choice.", "团队在做出选择前比较了两个方案。", "项目协作"],
    ["identify", "/aɪˈdentɪfaɪ/", "verb", "识别；找出", "to recognize or discover what something is", "identify a risk", "The planning session helped us identify several risks.", "规划会议帮助我们识别了几项风险。", "项目协作"],
    ["decision", "/dɪˈsɪʒn/", "noun", "决定；决策", "a choice made after considering possibilities", "make a decision", "We need more information before making a final decision.", "做最终决定前，我们还需要更多信息。", "项目协作"],
    ["result", "/rɪˈzʌlt/", "noun", "结果；成果", "something that happens because of an action or process", "review the result", "The group reviewed the result of the first test.", "小组审查了第一次测试的结果。", "项目协作"],
    ["process", "/ˈprəʊses/", "noun", "流程；过程", "a series of actions used to achieve a result", "improve a process", "A checklist made the approval process easier to follow.", "检查表让审批流程更容易遵循。", "项目协作"],
    ["method", "/ˈmeθəd/", "noun", "方法；做法", "a particular way of doing something", "use an effective method", "We tested a different method for collecting responses.", "我们测试了另一种收集反馈的方法。", "项目协作"],
    ["system", "/ˈsɪstəm/", "noun", "系统；体系", "a set of connected parts or rules working together", "use a tracking system", "The new system shows who is responsible for each action.", "新系统会显示每项行动的负责人。", "项目协作"],
    ["standard", "/ˈstændəd/", "noun", "标准；规范", "an accepted level of quality or performance", "meet a quality standard", "Every deliverable must meet the same quality standard.", "每项交付成果都必须达到同一质量标准。", "项目协作"],

    ["runway", "/ˈrʌnweɪ/", "noun", "跑道；飞机起降道", "a long strip of ground where aircraft take off and land", "clear the runway", "The aircraft waited until the runway was clear.", "飞机等到跑道清空后才起飞。", "旅行出行"],
    ["airline", "/ˈeəlaɪn/", "noun", "航空公司", "a company that carries passengers or goods by air", "contact the airline", "Contact the airline if you need special assistance.", "如果需要特殊协助，请联系航空公司。", "旅行出行"],
    ["flight", "/flaɪt/", "noun", "航班；飞行", "a journey made by aircraft", "book a flight", "I booked a direct flight to Singapore.", "我预订了直飞新加坡的航班。", "旅行出行"],
    ["boarding", "/ˈbɔːdɪŋ/", "noun", "登机；上车", "the process of getting onto a plane, ship, or train", "boarding begins", "Boarding begins forty minutes before the flight leaves.", "航班起飞前四十分钟开始登机。", "旅行出行"],
    ["gate", "/ɡeɪt/", "noun", "登机口；出入口", "a numbered place where passengers board a flight", "departure gate", "The departure gate changed after we passed security.", "我们通过安检后，登机口发生了变化。", "旅行出行"],
    ["terminal", "/ˈtɜːmɪnl/", "noun", "航站楼；终点站", "a building where passengers arrive or depart", "international terminal", "The shuttle connects the domestic and international terminals.", "接驳车连接国内和国际航站楼。", "旅行出行"],
    ["baggage", "/ˈbæɡɪdʒ/", "noun", "行李；托运行李", "bags and cases taken on a journey", "collect your baggage", "Collect your baggage from carousel number six.", "请在六号转盘领取行李。", "旅行出行"],
    ["suitcase", "/ˈsuːtkeɪs/", "noun", "手提箱；旅行箱", "a rectangular case used for carrying clothes while traveling", "pack a suitcase", "Leave some space in your suitcase for souvenirs.", "在旅行箱里留些空间放纪念品。", "旅行出行"],
    ["excursion", "/ɪkˈskɜːʃn/", "noun", "短途游览；集体出行", "a short organized journey for pleasure or education", "a day excursion", "We booked a day excursion to the coastal villages.", "我们预订了前往沿海村庄的一日游。", "旅行出行"],
    ["getaway", "/ˈɡetəweɪ/", "noun", "短期度假；休闲出行", "a short holiday away from home", "a weekend getaway", "The hotel offers packages for a quiet weekend getaway.", "这家酒店为安静的周末短期度假提供套餐。", "旅行出行"],
    ["tour", "/tʊə(r)/", "noun", "游览；参观行程", "a planned visit to several places", "join a guided tour", "We joined a guided tour of the old city.", "我们参加了老城区的导览游。", "旅行出行"],
    ["tourist", "/ˈtʊərɪst/", "noun", "游客；观光者", "a person traveling for pleasure", "a popular tourist area", "The square becomes crowded with tourists in summer.", "夏季这个广场会挤满游客。", "旅行出行"],
    ["guide", "/ɡaɪd/", "noun / verb", "导游；指南", "a person or book that gives travel information", "a local guide", "Our local guide explained the history of the temple.", "当地导游讲解了这座寺庙的历史。", "旅行出行"],
    ["timetable", "/ˈtaɪmteɪbl/", "noun", "时刻表；时间安排", "a list showing when transport or events happen", "check the timetable", "Check the weekend timetable because trains run less often.", "请查看周末时刻表，因为列车班次较少。", "旅行出行"],
    ["arrival", "/əˈraɪvl/", "noun", "到达；抵达时间", "the act or time of reaching a place", "on arrival", "You will receive your room key on arrival.", "抵达后你会拿到房间钥匙。", "旅行出行"],
    ["connection", "/kəˈnekʃn/", "noun", "联程交通；换乘衔接", "a second train or flight used to continue a journey", "miss a connection", "The delay may cause us to miss our connection.", "这次延误可能导致我们错过联程航班。", "旅行出行"],
    ["transit", "/ˈtrænzɪt/", "noun", "中转；运输过程", "the process of passing through or being transported", "in transit", "Passengers in transit should follow the purple signs.", "中转旅客应跟随紫色标志。", "旅行出行"],
    ["carriage", "/ˈkærɪdʒ/", "noun", "火车车厢", "one of the sections of a passenger train", "the quiet carriage", "Phone calls are not allowed in the quiet carriage.", "安静车厢内不允许打电话。", "旅行出行"],
    ["seat", "/siːt/", "noun", "座位；席位", "a place where a person sits", "reserve a seat", "I reserved an aisle seat for the long flight.", "我为长途航班预订了靠过道的座位。", "旅行出行"],
    ["booking", "/ˈbʊkɪŋ/", "noun", "预订；预约记录", "an arrangement to reserve travel, accommodation, or a service", "confirm a booking", "The hotel emailed me to confirm my booking.", "酒店发邮件确认了我的预订。", "旅行出行"],
    ["cancel", "/ˈkænsl/", "verb", "取消；撤销安排", "to decide that a planned event or service will not happen", "cancel a reservation", "You can cancel the reservation without charge until Friday.", "你可以在周五前免费取消预订。", "旅行出行"],
    ["abroad", "/əˈbrɔːd/", "adverb", "在国外；到国外", "in or to a foreign country", "study abroad", "Living abroad taught me to solve problems independently.", "海外生活教会了我独立解决问题。", "旅行出行"],
    ["overseas", "/ˌəʊvəˈsiːz/", "adjective / adverb", "海外的；在海外", "in or connected with a foreign country across the sea", "overseas travel", "The company provides insurance for overseas travel.", "公司为海外出行提供保险。", "旅行出行"],
    ["currency", "/ˈkʌrənsi/", "noun", "货币；通用货币", "the money used in a particular country", "exchange foreign currency", "I exchanged some foreign currency before the trip.", "旅行前我兑换了一些外币。", "旅行出行"],

    ["account", "/əˈkaʊnt/", "noun", "账户；账号", "a personal record used to access a service", "create an account", "You need to create an account before placing an order.", "下单前你需要创建一个账户。", "数字生活"],
    ["username", "/ˈjuːzəneɪm/", "noun", "用户名；登录名", "a name used to identify someone on a computer service", "enter a username", "Enter your username exactly as it appears in the email.", "请输入与邮件中完全相同的用户名。", "数字生活"],
    ["login", "/ˈlɒɡɪn/", "noun", "登录；登录信息", "the act or details used to enter a computer system", "login details", "Never share your login details in a public message.", "不要在公开消息中分享登录信息。", "数字生活"],
    ["logout", "/ˈlɒɡaʊt/", "noun", "退出登录；注销操作", "the act of leaving a computer account or system", "automatic logout", "Automatic logout protects your account on shared devices.", "自动退出登录能保护你在共用设备上的账户。", "数字生活"],
    ["website", "/ˈwebsaɪt/", "noun", "网站；网页站点", "a collection of connected pages on the internet", "visit a website", "Visit the official website for the latest opening hours.", "请访问官方网站查询最新营业时间。", "数字生活"],
    ["browser", "/ˈbraʊzə(r)/", "noun", "浏览器；网页浏览程序", "a program used to view information on the internet", "open in a browser", "Try opening the page in a different browser.", "请尝试用另一个浏览器打开页面。", "数字生活"],
    ["link", "/lɪŋk/", "noun", "链接；关联入口", "a connection that opens another page, file, or resource", "click a secure link", "The meeting link will become active ten minutes early.", "会议链接会提前十分钟生效。", "数字生活"],
    ["upload", "/ˌʌpˈləʊd/", "verb", "上传；传送到网络", "to send a file from a device to an online system", "upload a document", "Upload the signed document as a PDF file.", "请以 PDF 文件形式上传已签署的文档。", "数字生活"],
    ["install", "/ɪnˈstɔːl/", "verb", "安装；设置软件", "to put software or equipment in place for use", "install an update", "Install the update before restarting the application.", "重启应用程序前请安装更新。", "数字生活"],
    ["software", "/ˈsɒftweə(r)/", "noun", "软件；程序", "programs and instructions used by a computer", "business software", "The company uses cloud-based software for scheduling.", "公司使用云端软件进行排班。", "数字生活"],
    ["device", "/dɪˈvaɪs/", "noun", "设备；电子装置", "a piece of electronic equipment made for a purpose", "a mobile device", "You can access the service from any mobile device.", "你可以通过任何移动设备访问这项服务。", "数字生活"],
    ["network", "/ˈnetwɜːk/", "noun", "网络；计算机网络", "a group of connected computers or systems", "connect to a network", "Guests can connect to a separate wireless network.", "访客可以连接独立的无线网络。", "数字生活"],
    ["online", "/ˌɒnˈlaɪn/", "adjective / adverb", "在线的；通过网络", "connected to or available through the internet", "complete an online form", "You can complete the entire application online.", "你可以在线完成整个申请流程。", "数字生活"],
    ["offline", "/ˌɒfˈlaɪn/", "adjective / adverb", "离线的；未联网的", "not connected to or using the internet", "work offline", "Save a copy so that you can work offline.", "请保存一份副本，以便离线工作。", "数字生活"],
    ["data", "/ˈdeɪtə/", "noun", "数据；资料", "information stored or used by a computer or organization", "protect personal data", "The form collects only the personal data it needs.", "该表格只收集必要的个人资料。", "数字生活"],
    ["privacy", "/ˈprɪvəsi/", "noun", "隐私；私密权", "the right to keep personal information and activities protected", "protect user privacy", "Read the privacy notice before sharing your location.", "分享位置前请阅读隐私声明。", "数字生活"],
    ["security", "/sɪˈkjʊərəti/", "noun", "安全；信息防护", "protection against danger, attack, or unauthorized access", "improve account security", "A unique password improves your account security.", "独立密码可以提高账户安全性。", "数字生活"],
    ["permission", "/pəˈmɪʃn/", "noun", "权限；许可", "official approval or the right to access something", "grant permission", "The app asks for permission to use the camera.", "该应用会请求使用相机的权限。", "数字生活"],
    ["access", "/ˈækses/", "noun / verb", "访问权；访问", "the ability or right to enter, use, or view something", "gain access to", "New employees receive access to the system on day one.", "新员工入职第一天会获得系统访问权。", "数字生活"],
    ["backup", "/ˈbækʌp/", "noun", "备份；备用副本", "a copy of information kept in case the original is lost", "create a backup", "Create a backup before changing the device settings.", "更改设备设置前请创建备份。", "数字生活"],
    ["restore", "/rɪˈstɔː(r)/", "verb", "恢复；还原", "to return data or a system to an earlier condition", "restore deleted data", "Support helped me restore the deleted calendar.", "技术支持帮助我恢复了被删除的日历。", "数字生活"],
    ["delete", "/dɪˈliːt/", "verb", "删除；移除数据", "to remove text, files, or information from a device", "delete an old file", "Check the folder before you permanently delete anything.", "永久删除任何内容前请检查文件夹。", "数字生活"],
    ["settings", "/ˈsetɪŋz/", "plural noun", "设置；配置选项", "controls used to change how a device or program works", "adjust the settings", "Adjust the notification settings to reduce interruptions.", "请调整通知设置以减少干扰。", "数字生活"],
    ["notification", "/ˌnəʊtɪfɪˈkeɪʃn/", "noun", "通知；系统提醒", "a message that informs someone of an event or change", "receive a notification", "You will receive a notification when the upload finishes.", "上传完成时你会收到通知。", "数字生活"],

    ["sales", "/seɪlz/", "plural noun", "销售额；销售活动", "the activity or amount of selling goods and services", "increase sales", "The weekend campaign increased online sales by twelve percent.", "周末活动使线上销售额增长了百分之十二。", "商业分析"],
    ["profit", "/ˈprɒfɪt/", "noun", "利润；盈利", "money remaining after business costs are paid", "make a profit", "The new service began to make a profit in its second year.", "这项新服务在第二年开始盈利。", "商业分析"],
    ["loss", "/lɒs/", "noun", "亏损；损失", "money or value that is lost rather than gained", "report a loss", "The branch reported a small loss during the renovation.", "该分店在装修期间报告了小额亏损。", "商业分析"],
    ["pricing", "/ˈpraɪsɪŋ/", "noun", "定价；价格策略", "the process or method of deciding how much something should cost", "review the pricing", "The team reviewed its pricing after comparing similar services.", "团队在比较类似服务后审查了定价策略。", "商业分析"],
    ["popularity", "/ˌpɒpjuˈlærəti/", "noun", "受欢迎程度；市场热度", "the state of being liked or chosen by many people", "measure product popularity", "Online reviews helped us measure the product's popularity.", "线上评价帮助我们衡量产品的受欢迎程度。", "商业分析"],
    ["supply", "/səˈplaɪ/", "noun", "供应；供给量", "the amount of something available for use or sale", "a limited supply", "A limited supply caused the price to rise.", "供应有限导致价格上涨。", "商业分析"],
    ["competition", "/ˌkɒmpəˈtɪʃn/", "noun", "竞争；竞争局面", "the situation in which businesses try to be more successful than others", "face strong competition", "Local shops face strong competition from online retailers.", "本地商店面临线上零售商的激烈竞争。", "商业分析"],
    ["competitor", "/kəmˈpetɪtə(r)/", "noun", "竞争者；竞争企业", "a person or business trying to succeed in the same market", "study a competitor", "We studied how each competitor priced a similar service.", "我们研究了各竞争企业如何为类似服务定价。", "商业分析"],
    ["campaign", "/kæmˈpeɪn/", "noun", "推广活动；营销活动", "a planned series of actions to achieve a business goal", "run a marketing campaign", "The team ran a campaign aimed at first-time buyers.", "团队开展了面向首次购买者的营销活动。", "商业分析"],
    ["advertisement", "/ədˈvɜːtɪsmənt/", "noun", "广告；宣传内容", "a public notice that promotes a product, service, or job", "place an advertisement", "The advertisement attracted more visitors than expected.", "这则广告吸引的访客超过预期。", "商业分析"],
    ["questionnaire", "/ˌkwestʃəˈneə(r)/", "noun", "问卷；调查表", "a written set of questions used to collect information", "complete a questionnaire", "Customers completed a short questionnaire after the event.", "顾客在活动结束后填写了一份简短问卷。", "商业分析"],
    ["research", "/rɪˈsɜːtʃ/", "noun", "研究；调研", "careful study carried out to discover facts", "carry out market research", "Market research showed that customers preferred simpler plans.", "市场调研表明，顾客更喜欢简单的方案。", "商业分析"],
    ["figure", "/ˈfɪɡə(r)/", "noun", "数字；统计数值", "a number representing an amount, especially in a report", "check the figures", "Please check the quarterly figures before the meeting.", "请在会议前核对季度数据。", "商业分析"],
    ["chart", "/tʃɑːt/", "noun", "图表；统计图", "a visual display of information using lines, bars, or sections", "create a bar chart", "The chart compares sales across four regions.", "该图表比较了四个地区的销售额。", "商业分析"],
    ["graph", "/ɡrɑːf/", "noun", "曲线图；关系图", "a diagram showing how amounts change or relate", "read a graph", "The graph shows a steady rise in monthly users.", "该图显示月度用户数稳步增长。", "商业分析"],
    ["rate", "/reɪt/", "noun", "比率；速率", "a measure showing the frequency or speed of something", "a response rate", "The survey achieved a response rate of sixty percent.", "该调查获得了百分之六十的回复率。", "商业分析"],
    ["increase", "/ˈɪŋkriːs/", "noun", "增加；增长量", "a rise in the amount, number, or level of something", "a significant increase", "We saw a significant increase in repeat orders.", "我们看到重复订单显著增加。", "商业分析"],
    ["decrease", "/ˈdiːkriːs/", "noun", "减少；下降", "a reduction in the amount, number, or level of something", "a gradual decrease", "The data shows a gradual decrease in delivery complaints.", "数据显示配送投诉逐渐减少。", "商业分析"],
    ["growth", "/ɡrəʊθ/", "noun", "增长；发展", "an increase in size, value, or importance", "support business growth", "The new location supported steady business growth.", "新地点推动了业务稳定增长。", "商业分析"],
    ["performance", "/pəˈfɔːməns/", "noun", "表现；业绩", "how well a person, product, or business works", "review sales performance", "Managers review sales performance at the end of each month.", "经理在每月底审查销售业绩。", "商业分析"],
    ["average", "/ˈævərɪdʒ/", "noun / adjective", "平均数；平均的", "a level found by adding values and dividing by their number", "the average order value", "The average order value rose slightly this quarter.", "本季度平均订单金额略有上升。", "商业分析"],
    ["percentage", "/pəˈsentɪdʒ/", "noun", "百分比；比例", "an amount expressed as part of one hundred", "a small percentage", "Only a small percentage of users canceled the service.", "只有一小部分用户取消了服务。", "商业分析"],
    ["finding", "/ˈfaɪndɪŋ/", "noun", "调查结果；研究发现", "a fact discovered through research or analysis", "a key finding", "One key finding was that speed mattered more than price.", "一项关键发现是速度比价格更重要。", "商业分析"],
    ["cycle", "/ˈsaɪkl/", "noun", "周期；循环过程", "a series of events that repeats in the same order", "a seasonal sales cycle", "The data reveals a predictable seasonal sales cycle.", "数据显示出可预测的季节性销售周期。", "商业分析"]
  ];

  window.ENGLISH_COMPASS_VOCABULARY_BULK_B1 = Object.freeze(rows.map(([
    word,
    phonetic,
    partOfSpeech,
    definition,
    definitionEn,
    collocation,
    example,
    exampleZh,
    topic
  ]) => Object.freeze({
    id: `bulk-b1-${word.replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
    word,
    phonetic,
    partOfSpeech,
    definition,
    definitionEn,
    collocation,
    example,
    exampleZh,
    topic,
    level: "B1"
  })));
})();
