(function () {
  "use strict";

  const rows = [
    ["aspiration", "/ˌæspəˈreɪʃn/", "noun", "职业抱负；强烈希望实现的目标", "a strong hope or ambition to achieve something", "career aspiration", "Her career aspiration is to lead an international design team.", "她的职业抱负是领导一支国际设计团队。", "职业发展"],
    ["autonomy", "/ɔːˈtɒnəmi/", "noun", "自主权；独立作出决定的能力", "the freedom to make decisions and act independently", "greater autonomy", "Experienced staff are given greater autonomy over their schedules.", "经验丰富的员工在日程安排上拥有更大的自主权。", "职业发展"],
    ["credentials", "/krəˈdenʃlz/", "plural noun", "资历证明；表明能力的证书或经历", "qualifications or experience that show someone is suitable for a role", "professional credentials", "The employer verified her professional credentials before making an offer.", "雇主在发出录用通知前核实了她的专业资历。", "职业发展"],
    ["employability", "/ɪmˌplɔɪəˈbɪləti/", "noun", "就业能力；获得并保持工作的能力", "the skills and qualities that make someone likely to gain employment", "improve employability", "International experience can improve your employability in a global market.", "国际经验能提升你在全球市场中的就业能力。", "职业发展"],
    ["entrepreneurship", "/ˌɒntrəprəˈnɜːʃɪp/", "noun", "创业精神；创办和经营企业的能力", "the activity and skill of starting and running a business", "develop entrepreneurship", "The course develops entrepreneurship through practical business projects.", "这门课程通过实际商业项目培养创业能力。", "职业发展"],
    ["internship", "/ˈɪntɜːnʃɪp/", "noun", "实习岗位；为获取经验而从事的短期工作", "a temporary position that provides practical work experience", "complete an internship", "She completed an internship with a logistics company in Singapore.", "她在新加坡一家物流公司完成了实习。", "职业发展"],
    ["progression", "/prəˈɡreʃn/", "noun", "晋升路径；逐步向更高职位发展", "gradual development toward a more advanced position", "career progression", "The company offers a clear path for career progression.", "公司提供清晰的职业晋升路径。", "职业发展"],
    ["recognition", "/ˌrekəɡˈnɪʃn/", "noun", "认可；对贡献或成就的肯定", "public or formal appreciation of someone's work or achievement", "gain recognition", "Her research gained recognition from senior industry experts.", "她的研究得到了资深行业专家的认可。", "职业发展"],
    ["remuneration", "/rɪˌmjuːnəˈreɪʃn/", "noun", "薪酬；工作所得的工资和福利", "money and benefits received in return for work", "remuneration package", "The remuneration package includes a bonus and private insurance.", "这套薪酬方案包括奖金和私人保险。", "职业发展"],
    ["retention", "/rɪˈtenʃn/", "noun", "人才留任；让员工继续任职", "the ability of an organization to keep its employees", "staff retention", "Flexible working arrangements have improved staff retention.", "灵活工作安排提高了员工留任率。", "职业发展"],
    ["appraisal", "/əˈpreɪzl/", "noun", "绩效评估；对工作表现的正式评价", "a formal assessment of an employee's performance", "annual appraisal", "We agreed on three development goals during my annual appraisal.", "我们在年度绩效评估中商定了三个发展目标。", "职业发展"],
    ["onboarding", "/ˈɒnbɔːdɪŋ/", "noun", "入职融入；帮助新员工适应岗位的过程", "the process of helping a new employee settle into an organization", "onboarding process", "A structured onboarding process helps new hires become productive sooner.", "系统化的入职流程能帮助新员工更快进入工作状态。", "职业发展"],
    ["reskill", "/ˌriːˈskɪl/", "verb", "转岗培训；学习不同工作所需的新技能", "to learn new skills for a different type of work", "reskill the workforce", "The program will reskill employees for roles in digital operations.", "该计划将帮助员工学习数字运营岗位所需的新技能。", "职业发展"],
    ["upskill", "/ˌʌpˈskɪl/", "verb", "技能升级；学习更高级的工作技能", "to learn additional or more advanced skills for work", "upskill the team", "We need to upskill the team before introducing the new platform.", "在引入新平台前，我们需要提升团队技能。", "职业发展"],
    ["tenure", "/ˈtenjə(r)/", "noun", "任职期；在某岗位工作的时间", "the period for which someone holds a particular job", "long tenure", "During her ten-year tenure, she expanded the regional office.", "在十年任职期间，她扩大了区域办事处。", "职业发展"],
    ["succession", "/səkˈseʃn/", "noun", "接班安排；职位继任的过程", "the process of someone taking over an important position", "succession planning", "Succession planning prepares future leaders for key roles.", "继任规划能让未来领导者为关键岗位做好准备。", "职业发展"],
    ["mobility", "/məʊˈbɪləti/", "noun", "职业流动性；在岗位或地区间调动的能力", "the ability to move between jobs, roles, or locations", "career mobility", "Language skills can increase career mobility across regions.", "语言技能能提高跨地区的职业流动性。", "职业发展"],
    ["placement", "/ˈpleɪsmənt/", "noun", "岗位安排；为学习者提供的工作机会", "a temporary job arranged to provide training or experience", "work placement", "The degree includes a six-month work placement overseas.", "该学位课程包含六个月的海外岗位实践。", "职业发展"],
    ["prospect", "/ˈprɒspekt/", "noun", "发展前景；未来成功的可能性", "the possibility of future success or advancement", "career prospects", "The qualification improved her career prospects considerably.", "这项资格显著改善了她的职业前景。", "职业发展"],
    ["aptitude", "/ˈæptɪtjuːd/", "noun", "天赋；学习某项技能的自然能力", "a natural ability to learn or do something well", "aptitude for leadership", "He showed a strong aptitude for leadership early in his career.", "他在职业生涯早期就表现出很强的领导天赋。", "职业发展"],
    ["proficiency", "/prəˈfɪʃnsi/", "noun", "熟练程度；高水平运用技能的能力", "a high degree of skill or ability", "language proficiency", "The role requires professional proficiency in written English.", "该岗位要求具备专业水平的英语写作能力。", "职业发展"],
    ["mastery", "/ˈmɑːstəri/", "noun", "精通；对某项技能的全面掌握", "complete knowledge or very high skill in a subject", "achieve mastery", "Mastery of the software takes consistent practice.", "精通这款软件需要持续练习。", "职业发展"],
    ["specialization", "/ˌspeʃəlaɪˈzeɪʃn/", "noun", "专业方向；重点研究或工作的领域", "a particular area in which someone develops expert knowledge", "technical specialization", "Her technical specialization is supply-chain analytics.", "她的技术专业方向是供应链分析。", "职业发展"],
    ["professionalism", "/prəˈfeʃənəlɪzəm/", "noun", "职业素养；工作中应有的能力和行为", "the skill and conduct expected from a competent professional", "demonstrate professionalism", "She demonstrated professionalism throughout the difficult negotiation.", "她在整个艰难谈判中表现出了职业素养。", "职业发展"],
    ["networking", "/ˈnetwɜːkɪŋ/", "noun", "职业社交；建立有助于工作的联系", "the activity of building professional relationships", "business networking", "Business networking introduced him to several potential partners.", "职业社交让他认识了几位潜在合作伙伴。", "职业发展"],
    ["resume", "/ˈrezjumeɪ/", "noun", "个人简历；求职时使用的经历概述", "a document summarizing education, experience, and skills for a job application", "update a resume", "Tailor your resume to the requirements of each position.", "应根据每个岗位的要求调整个人简历。", "职业发展"],
    ["recruiter", "/rɪˈkruːtə(r)/", "noun", "招聘人员；负责寻找候选人的人", "a person whose job is to find suitable employees", "contact a recruiter", "A recruiter contacted me about a regional sales role.", "一名招聘人员联系我，介绍了一个区域销售岗位。", "职业发展"],
    ["reference", "/ˈrefrəns/", "noun", "推荐证明；前雇主对求职者的评价", "a statement from someone who can describe a job applicant's abilities", "provide a reference", "My former supervisor agreed to provide a reference.", "我的前主管同意提供推荐证明。", "职业发展"],
    ["induction", "/ɪnˈdʌkʃn/", "noun", "入职介绍；新员工接受的初始培训", "initial training given to someone starting a new job", "induction program", "The induction program covers safety, systems, and company culture.", "入职培训涵盖安全、系统和公司文化。", "职业发展"],
    ["redeployment", "/ˌriːdɪˈplɔɪmənt/", "noun", "岗位调配；把员工安排到新的职位", "the act of moving employees to different roles or locations", "staff redeployment", "Staff redeployment avoided unnecessary job losses.", "员工岗位调配避免了不必要的裁员。", "职业发展"],

    ["acquisition", "/ˌækwɪˈzɪʃn/", "noun", "收购；取得另一家企业的控制权", "the act of buying or gaining control of a company", "complete an acquisition", "The group completed the acquisition of a smaller competitor.", "该集团完成了对一家较小竞争对手的收购。", "商业运营"],
    ["asset", "/ˈæset/", "noun", "资产；对企业有价值的资源", "something valuable that a person or business owns", "valuable asset", "Customer data is a valuable asset and must be protected.", "客户数据是宝贵资产，必须受到保护。", "商业运营"],
    ["audit", "/ˈɔːdɪt/", "noun", "审计；对账目或流程的正式检查", "an official examination of accounts, records, or processes", "conduct an audit", "An independent firm will conduct the annual audit.", "一家独立公司将进行年度审计。", "商业运营"],
    ["automation", "/ˌɔːtəˈmeɪʃn/", "noun", "自动化；使用技术自动完成流程", "the use of technology to perform processes with little human input", "process automation", "Process automation reduced manual errors in billing.", "流程自动化减少了账单中的人工错误。", "商业运营"],
    ["backlog", "/ˈbæklɒɡ/", "noun", "积压任务；尚未处理的工作", "a quantity of work that should have been completed already", "clear a backlog", "The support team worked overtime to clear the backlog.", "支持团队加班清理积压任务。", "商业运营"],
    ["bottleneck", "/ˈbɒtlnek/", "noun", "瓶颈；限制整体效率的环节", "a stage in a process that slows down the whole system", "remove a bottleneck", "A slow approval process created a serious bottleneck.", "缓慢的审批流程造成了严重瓶颈。", "商业运营"],
    ["compliance", "/kəmˈplaɪəns/", "noun", "合规；遵守法律或规定", "the act of obeying a law, rule, or standard", "regulatory compliance", "Regular training helps maintain regulatory compliance.", "定期培训有助于保持监管合规。", "商业运营"],
    ["contract", "/ˈkɒntrækt/", "noun", "合同；具有约束力的正式协议", "a legally binding agreement between people or organizations", "sign a contract", "Both companies signed a three-year service contract.", "两家公司签署了一份三年期服务合同。", "商业运营"],
    ["contractor", "/kənˈtræktə(r)/", "noun", "承包商；按合同提供服务的个人或公司", "a person or company hired to provide services under a contract", "independent contractor", "An independent contractor installed the new security system.", "一名独立承包商安装了新的安全系统。", "商业运营"],
    ["distribution", "/ˌdɪstrɪˈbjuːʃn/", "noun", "分销；把商品送往销售地点的过程", "the process of supplying goods to shops or customers", "distribution network", "The company expanded its distribution network across Asia.", "公司扩大了在亚洲的分销网络。", "商业运营"],
    ["enterprise", "/ˈentəpraɪz/", "noun", "企业；具有商业目标的组织", "a business organization or ambitious commercial activity", "small enterprise", "The platform was designed for both startups and large enterprises.", "该平台面向初创公司和大型企业设计。", "商业运营"],
    ["facility", "/fəˈsɪləti/", "noun", "设施；为特定业务建造或配备的场所", "a building or place designed for a particular business purpose", "production facility", "The new production facility will open next spring.", "新的生产设施将于明年春季启用。", "商业运营"],
    ["franchise", "/ˈfræntʃaɪz/", "noun", "特许经营权；使用品牌经营业务的许可", "the right to operate a business using another company's brand", "open a franchise", "They plan to open a franchise in the city center.", "他们计划在市中心开设一家特许经营店。", "商业运营"],
    ["infrastructure", "/ˈɪnfrəstrʌktʃə(r)/", "noun", "基础设施；支撑业务运行的系统和设备", "the basic systems and structures needed for an organization to operate", "digital infrastructure", "Reliable digital infrastructure supports remote operations.", "可靠的数字基础设施支撑远程运营。", "商业运营"],
    ["innovation", "/ˌɪnəˈveɪʃn/", "noun", "创新；引入新方法或产品", "the introduction of new ideas, methods, or products", "drive innovation", "Cross-functional teams often drive innovation.", "跨职能团队往往能推动创新。", "商业运营"],
    ["integration", "/ˌɪntɪˈɡreɪʃn/", "noun", "整合；使不同系统协同工作的过程", "the process of combining parts so that they work together", "system integration", "System integration gave managers a single view of sales data.", "系统整合让管理者能够统一查看销售数据。", "商业运营"],
    ["margin", "/ˈmɑːdʒɪn/", "noun", "利润率；售价与成本之间的差额比例", "the difference between selling price and cost, usually expressed as profit", "profit margin", "Rising transport costs reduced the profit margin.", "运输成本上涨降低了利润率。", "商业运营"],
    ["merger", "/ˈmɜːdʒə(r)/", "noun", "合并；两家企业结合为一体", "the combination of two companies into one organization", "proposed merger", "Shareholders approved the proposed merger.", "股东批准了拟议中的合并。", "商业运营"],
    ["overhead", "/ˈəʊvəhed/", "noun", "间接成本；不直接产生产品的经营费用", "a regular business cost not directly linked to making a product", "reduce overhead", "Shared offices helped the startup reduce overhead.", "共享办公室帮助这家初创企业降低了间接成本。", "商业运营"],
    ["output", "/ˈaʊtpʊt/", "noun", "产出；在一定时期内完成的产品或工作量", "the amount of work or goods produced in a period", "increase output", "The upgraded equipment increased output without adding staff.", "升级后的设备在不增加人员的情况下提高了产出。", "商业运营"],
    ["productivity", "/ˌprɒdʌkˈtɪvəti/", "noun", "生产效率；单位资源产生的工作成果", "the rate at which work or goods are produced", "boost productivity", "Clear priorities can boost productivity across the team.", "明确的优先事项能提升整个团队的生产效率。", "商业运营"],
    ["quota", "/ˈkwəʊtə/", "noun", "配额；必须达到的销售或产量目标", "a fixed amount that someone is expected to sell or produce", "meet a quota", "The sales team exceeded its quarterly quota.", "销售团队超额完成了季度配额。", "商业运营"],
    ["retailer", "/ˈriːteɪlə(r)/", "noun", "零售商；直接向消费者销售商品的企业", "a business that sells goods directly to consumers", "online retailer", "The online retailer opened its first physical store.", "这家网络零售商开设了第一家实体店。", "商业运营"],
    ["scalable", "/ˈskeɪləbl/", "adjective", "可扩展的；能随需求增长而扩大", "able to grow or handle more demand without major difficulty", "scalable solution", "We need a scalable solution that can support ten regions.", "我们需要一个能支持十个地区的可扩展方案。", "商业运营"],
    ["subsidy", "/ˈsʌbsədi/", "noun", "补贴；政府或机构提供的资金支持", "money provided to reduce the cost of an activity or service", "government subsidy", "The project received a subsidy for energy-efficient equipment.", "该项目获得了节能设备补贴。", "商业运营"],
    ["tender", "/ˈtendə(r)/", "noun", "投标书；承接项目的正式报价", "a formal offer to supply goods or complete work at a stated price", "submit a tender", "Three suppliers submitted a tender for the construction work.", "三家供应商为这项建设工程提交了投标书。", "商业运营"],
    ["turnover", "/ˈtɜːnəʊvə(r)/", "noun", "营业额；一定时期内的销售总额", "the total value of goods or services sold by a business", "annual turnover", "The company's annual turnover rose by twelve percent.", "公司的年营业额增长了百分之十二。", "商业运营"],
    ["utilization", "/ˌjuːtəlaɪˈzeɪʃn/", "noun", "利用率；资源被实际使用的程度", "the extent to which available resources are used", "resource utilization", "Better scheduling improved equipment utilization.", "更合理的排程提高了设备利用率。", "商业运营"],
    ["vendor", "/ˈvendə(r)/", "noun", "供应商；出售产品或服务的企业", "a company or person that sells goods or services", "software vendor", "The software vendor provides support around the clock.", "软件供应商提供全天候支持。", "商业运营"],
    ["wholesale", "/ˈhəʊlseɪl/", "adjective / noun", "批发；大量销售给零售商的业务", "the business of selling goods in large quantities to retailers", "wholesale price", "Bulk buyers receive a lower wholesale price.", "批量采购者可以获得更低的批发价。", "商业运营"],
    ["workflow", "/ˈwɜːkfləʊ/", "noun", "工作流程；任务从开始到完成的顺序", "the sequence of tasks through which work is completed", "simplify a workflow", "The new dashboard simplified the approval workflow.", "新仪表板简化了审批工作流程。", "商业运营"],
    ["outsourcing", "/ˈaʊtsɔːsɪŋ/", "noun", "业务外包；把工作交给外部公司完成", "the practice of paying another company to perform business work", "outsourcing agreement", "Outsourcing payroll reduced the administrative burden.", "外包薪资核算减轻了行政负担。", "商业运营"],
    ["subscription", "/səbˈskrɪpʃn/", "noun", "订阅服务；按期付费获得持续使用权", "an arrangement to pay regularly for continued access to a service", "annual subscription", "The annual subscription includes technical support.", "年度订阅包含技术支持。", "商业运营"],
    ["deployment", "/dɪˈplɔɪmənt/", "noun", "部署；把系统投入实际使用", "the process of putting a system or resource into use", "software deployment", "The software deployment was completed without downtime.", "软件部署在没有停机的情况下完成。", "商业运营"],
    ["sustainability", "/səˌsteɪnəˈbɪləti/", "noun", "可持续性；长期运营且减少负面影响的能力", "the ability to continue over time while limiting environmental or social harm", "improve sustainability", "Reusable packaging improved the sustainability of deliveries.", "可重复使用的包装提高了配送的可持续性。", "商业运营"],

    ["advocate", "/ˈædvəkət/", "noun", "倡导者；公开支持某项理念的人", "a person who publicly supports a policy, idea, or group", "strong advocate", "She is a strong advocate for flexible working.", "她是灵活办公的坚定倡导者。", "领导力"],
    ["authority", "/ɔːˈθɒrəti/", "noun", "职权；作出决定和指示的权力", "the official power to make decisions or give instructions", "decision-making authority", "Team leaders have authority to approve small expenses.", "团队负责人有权批准小额开支。", "领导力"],
    ["credibility", "/ˌkredəˈbɪləti/", "noun", "可信度；获得他人信任的品质", "the quality of being trusted and believed", "build credibility", "Leaders build credibility by keeping their promises.", "领导者通过信守承诺建立可信度。", "领导力"],
    ["delegation", "/ˌdelɪˈɡeɪʃn/", "noun", "授权分工；把任务和责任交给他人", "the act of giving tasks or authority to other people", "effective delegation", "Effective delegation gives staff room to develop.", "有效授权能给员工留出成长空间。", "领导力"],
    ["diplomacy", "/dɪˈpləʊməsi/", "noun", "圆融沟通；妥善处理敏感关系的技巧", "skill in dealing with difficult situations without causing offense", "handle with diplomacy", "She handled the disagreement with patience and diplomacy.", "她以耐心和圆融妥善处理了分歧。", "领导力"],
    ["directive", "/dəˈrektɪv/", "noun", "指令；管理层发布的正式要求", "an official instruction issued by someone in authority", "issue a directive", "Management issued a directive on data security.", "管理层发布了一项有关数据安全的指令。", "领导力"],
    ["governance", "/ˈɡʌvənəns/", "noun", "治理；组织被监督和管理的制度", "the system by which an organization is directed and controlled", "corporate governance", "Strong corporate governance reduces legal and financial risk.", "健全的公司治理能降低法律和财务风险。", "领导力"],
    ["influence", "/ˈɪnfluəns/", "noun", "影响力；改变他人决定或行为的能力", "the power to affect how someone thinks or acts", "positive influence", "A calm manager can be a positive influence during change.", "冷静的经理能在变革期间产生积极影响。", "领导力"],
    ["inspiration", "/ˌɪnspəˈreɪʃn/", "noun", "激励作用；促使他人采取积极行动的力量", "something that motivates people to think or act positively", "source of inspiration", "Her persistence became a source of inspiration for the team.", "她的坚持成为团队的激励来源。", "领导力"],
    ["integrity", "/ɪnˈteɡrəti/", "noun", "正直；即使困难也坚持诚实原则", "the quality of being honest and guided by strong moral principles", "act with integrity", "Managers must act with integrity when handling confidential data.", "管理者在处理机密数据时必须保持正直。", "领导力"],
    ["mediator", "/ˈmiːdieɪtə(r)/", "noun", "调解人；帮助冲突双方达成一致的人", "a neutral person who helps opposing sides reach agreement", "act as a mediator", "A senior colleague acted as a mediator in the dispute.", "一位资深同事在争议中担任调解人。", "领导力"],
    ["morale", "/məˈrɑːl/", "noun", "团队士气；成员的信心和热情", "the confidence and enthusiasm felt by a group", "boost morale", "Recognizing small wins can boost team morale.", "认可小成果能够提升团队士气。", "领导力"],
    ["ownership", "/ˈəʊnəʃɪp/", "noun", "主人翁意识；主动对结果负责的态度", "a willingness to take personal responsibility for an outcome", "take ownership", "She took ownership of the mistake and corrected it quickly.", "她主动承担错误责任并迅速纠正。", "领导力"],
    ["supervision", "/ˌsuːpəˈvɪʒn/", "noun", "监督指导；负责观察并支持他人工作", "the act of overseeing and guiding another person's work", "under supervision", "New operators work under close supervision for two weeks.", "新操作员会在密切监督下工作两周。", "领导力"],
    ["transparency", "/trænsˈpærənsi/", "noun", "透明度；公开说明决定和信息的程度", "the quality of being open and clear about actions or decisions", "increase transparency", "Publishing the criteria increased transparency in promotion decisions.", "公布标准提高了晋升决定的透明度。", "领导力"],
    ["vision", "/ˈvɪʒn/", "noun", "愿景；对组织未来的清晰设想", "a clear idea of what an organization should become in the future", "shared vision", "The director presented a shared vision for sustainable growth.", "总监提出了可持续增长的共同愿景。", "领导力"],
    ["accountability", "/əˌkaʊntəˈbɪləti/", "noun", "问责意识；对决定及结果承担责任", "the duty to accept responsibility for decisions and results", "ensure accountability", "Written responsibilities help ensure accountability.", "书面职责有助于确保问责落实。", "领导力"],
    ["alignment", "/əˈlaɪnmənt/", "noun", "目标一致；不同人员或计划方向相同", "a state in which people or plans support the same objectives", "strategic alignment", "The workshop created alignment between sales and operations.", "研讨会使销售与运营团队的目标达成一致。", "领导力"],
    ["coaching", "/ˈkəʊtʃɪŋ/", "noun", "工作辅导；通过指导帮助他人提升表现", "guidance that helps someone improve skills or performance", "receive coaching", "New supervisors receive coaching from experienced managers.", "新主管会得到经验丰富的经理辅导。", "领导力"],
    ["encouragement", "/ɪnˈkʌrɪdʒmənt/", "noun", "鼓励；给予他人信心的支持", "words or actions that give someone confidence to continue", "offer encouragement", "A few words of encouragement helped the trainee continue.", "几句鼓励的话帮助这名学员坚持了下去。", "领导力"],
    ["resilience", "/rɪˈzɪliəns/", "noun", "复原力；受挫后恢复并继续前进的能力", "the ability to recover quickly from difficulty or change", "build resilience", "Regular reflection helps leaders build resilience.", "定期反思有助于领导者培养复原力。", "领导力"],
    ["decisive", "/dɪˈsaɪsɪv/", "adjective", "果断的；能够及时作出明确决定的", "able to make clear decisions quickly and confidently", "decisive action", "Decisive action prevented a minor issue from spreading.", "果断行动防止了小问题扩大。", "领导力"],
    ["impartial", "/ɪmˈpɑːʃl/", "adjective", "公正的；不偏向任何一方的", "fair and not favoring one person or group", "impartial assessment", "An impartial panel reviewed every application.", "一个公正的评审小组审查了每份申请。", "领导力"],
    ["approachable", "/əˈprəʊtʃəbl/", "adjective", "平易近人的；让人愿意交流的", "friendly and easy to talk to", "approachable manager", "An approachable manager hears about problems earlier.", "平易近人的经理能更早听到问题反馈。", "领导力"],
    ["assertive", "/əˈsɜːtɪv/", "adjective", "坚定自信的；清楚表达立场而不冒犯的", "confident in expressing a view without being aggressive", "assertive communication", "Assertive communication helps set healthy boundaries.", "坚定自信的沟通有助于建立合理边界。", "领导力"],
    ["compassionate", "/kəmˈpæʃənət/", "adjective", "富有同理心的；关心他人困难的", "showing concern for people who are experiencing difficulty", "compassionate leadership", "Compassionate leadership supported staff during the restructuring.", "富有同理心的领导方式在重组期间支持了员工。", "领导力"],
    ["ethical", "/ˈeθɪkl/", "adjective", "符合道德的；遵循正确行为原则的", "morally right and consistent with accepted principles", "ethical decision", "The committee considered the ethical impact of using customer data.", "委员会考虑了使用客户数据的道德影响。", "领导力"],
    ["strategic", "/strəˈtiːdʒɪk/", "adjective", "战略性的；服务于长期目标的", "designed to achieve an important long-term aim", "strategic decision", "Opening the regional hub was a strategic decision.", "设立区域中心是一项战略性决定。", "领导力"],
    ["visionary", "/ˈvɪʒənəri/", "adjective", "有远见的；能想象并规划未来的", "able to imagine and plan important future developments", "visionary leader", "A visionary leader can turn uncertainty into a clear direction.", "有远见的领导者能把不确定性转化为清晰方向。", "领导力"],
    ["mentoring", "/ˈmentərɪŋ/", "noun", "导师指导；由资深人员提供长期发展建议", "long-term guidance provided by a more experienced person", "mentoring program", "The mentoring program pairs graduates with senior specialists.", "导师计划把毕业生与资深专家配对。", "领导力"],

    ["analysis", "/əˈnæləsɪs/", "noun", "分析；系统研究信息以理解问题", "a detailed examination of information in order to understand something", "conduct an analysis", "The cost analysis revealed several unnecessary expenses.", "成本分析揭示了几项不必要的开支。", "分析决策"],
    ["analytics", "/ˌænəˈlɪtɪks/", "plural noun", "数据分析技术；从数据中提取规律的方法", "the systematic use of data to discover useful patterns", "customer analytics", "Customer analytics helped us predict purchasing behavior.", "客户数据分析帮助我们预测了购买行为。", "分析决策"],
    ["anomaly", "/əˈnɒməli/", "noun", "异常现象；偏离正常模式的情况", "something that differs from what is normal or expected", "detect an anomaly", "The system detected an anomaly in the payment records.", "系统在付款记录中发现了异常。", "分析决策"],
    ["assess", "/əˈses/", "verb", "评估；判断某事的质量或程度", "to judge the quality, importance, or extent of something", "assess the risk", "We assessed the risk before approving the change.", "我们在批准变更前评估了风险。", "分析决策"],
    ["bias", "/ˈbaɪəs/", "noun", "偏差；影响客观判断的倾向", "a tendency that prevents fair or objective judgment", "reduce bias", "Using clear criteria can reduce bias in recruitment.", "使用明确标准能减少招聘中的偏差。", "分析决策"],
    ["causation", "/kɔːˈzeɪʃn/", "noun", "因果关系；一个因素导致另一结果", "the relationship in which one event causes another", "prove causation", "A correlation alone does not prove causation.", "仅有相关性并不能证明因果关系。", "分析决策"],
    ["constraint", "/kənˈstreɪnt/", "noun", "限制条件；约束可选方案的因素", "a limit that restricts what can be done", "budget constraint", "The main constraint is the limited implementation time.", "主要限制条件是实施时间有限。", "分析决策"],
    ["diagnosis", "/ˌdaɪəɡˈnəʊsɪs/", "noun", "问题诊断；确定故障根本原因的过程", "the process of identifying the cause of a problem", "accurate diagnosis", "An accurate diagnosis prevented the same fault from returning.", "准确诊断防止了相同故障再次出现。", "分析决策"],
    ["indicator", "/ˈɪndɪkeɪtə(r)/", "noun", "指示指标；显示趋势或状态的数据", "a measure that shows the condition or direction of something", "performance indicator", "Customer retention is a useful performance indicator.", "客户留存率是一项有用的绩效指标。", "分析决策"],
    ["likelihood", "/ˈlaɪklihʊd/", "noun", "可能性；某事发生的概率程度", "the chance that something will happen", "reduce the likelihood", "Extra testing reduced the likelihood of a failed launch.", "额外测试降低了发布失败的可能性。", "分析决策"],
    ["metric", "/ˈmetrɪk/", "noun", "衡量指标；用于评估表现的数值", "a numerical measure used to evaluate performance", "key metric", "Response time is a key metric for the support team.", "响应时间是支持团队的一项关键指标。", "分析决策"],
    ["pattern", "/ˈpætn/", "noun", "规律；反复出现的可识别趋势", "a repeated or recognizable way in which something happens", "identify a pattern", "We identified a seasonal pattern in customer demand.", "我们发现了客户需求的季节性规律。", "分析决策"],
    ["probability", "/ˌprɒbəˈbɪləti/", "noun", "概率；事件发生的可能程度", "a numerical or general measure of how likely an event is", "high probability", "There is a high probability that costs will rise next quarter.", "下季度成本上涨的概率很高。", "分析决策"],
    ["projection", "/prəˈdʒekʃn/", "noun", "预测值；根据现有数据推算的未来结果", "an estimate of a future amount based on current information", "sales projection", "The latest sales projection is more cautious than last month's.", "最新销售预测比上月更为谨慎。", "分析决策"],
    ["rationale", "/ˌræʃəˈnɑːl/", "noun", "决策依据；行动背后的合理理由", "the set of reasons that explain a decision or action", "explain the rationale", "The manager explained the rationale behind the new policy.", "经理解释了新政策背后的决策依据。", "分析决策"],
    ["scenario", "/səˈnɑːriəʊ/", "noun", "情景设定；可能发生的一组情况", "a possible situation considered for planning purposes", "worst-case scenario", "We prepared a reserve fund for the worst-case scenario.", "我们为最坏情景准备了备用资金。", "分析决策"],
    ["significance", "/sɪɡˈnɪfɪkəns/", "noun", "重要性；某项发现具有的影响程度", "the importance or meaning of a fact, result, or event", "practical significance", "The report explains the practical significance of the findings.", "报告解释了这些发现的实际重要性。", "分析决策"],
    ["simulation", "/ˌsɪmjuˈleɪʃn/", "noun", "模拟；仿照真实过程进行的测试", "a model or exercise that imitates a real process", "run a simulation", "The team ran a simulation before changing the warehouse layout.", "团队在改变仓库布局前进行了模拟。", "分析决策"],
    ["statistics", "/stəˈtɪstɪks/", "plural noun", "统计数据；以数字表示的信息集合", "numerical facts collected and analyzed for a purpose", "official statistics", "Official statistics show steady growth in online sales.", "官方统计数据显示网络销售稳定增长。", "分析决策"],
    ["threshold", "/ˈθreʃhəʊld/", "noun", "阈值；触发行动的最低或最高界限", "a level at which a particular action or effect begins", "reach a threshold", "An alert appears when spending reaches the approved threshold.", "支出达到批准阈值时会出现警报。", "分析决策"],
    ["tradeoff", "/ˈtreɪdɒf/", "noun", "取舍；获得一项利益而牺牲另一项", "a balance in which one advantage is exchanged for another", "consider the tradeoff", "We considered the tradeoff between speed and accuracy.", "我们考虑了速度与准确性之间的取舍。", "分析决策"],
    ["validity", "/vəˈlɪdəti/", "noun", "有效性；结论或方法可靠成立的程度", "the extent to which a method or conclusion is sound and accurate", "test the validity", "A larger sample would improve the validity of the study.", "更大的样本会提高研究的有效性。", "分析决策"],
    ["hypothesis", "/haɪˈpɒθəsɪs/", "noun", "假设；等待数据验证的解释", "a proposed explanation that can be tested with evidence", "test a hypothesis", "The team tested the hypothesis with customer interviews.", "团队通过客户访谈检验了这一假设。", "分析决策"],
    ["inference", "/ˈɪnfərəns/", "noun", "推断；根据证据得出的判断", "a conclusion reached on the basis of evidence", "draw an inference", "It is too early to draw an inference from one complaint.", "仅凭一次投诉还不能过早作出推断。", "分析决策"],
    ["methodology", "/ˌmeθəˈdɒlədʒi/", "noun", "方法论；完成研究或分析的一套方法", "a system of methods used in a study or process", "research methodology", "The appendix describes the research methodology in detail.", "附录详细说明了研究方法。", "分析决策"],
    ["parameter", "/pəˈræmɪtə(r)/", "noun", "参数；决定系统运行范围的数值或界限", "a value or limit that controls how a system operates", "set a parameter", "Users can set a parameter for the maximum order value.", "用户可以设置订单最高金额参数。", "分析决策"],
    ["quantify", "/ˈkwɒntɪfaɪ/", "verb", "量化；用数字表示影响或数量", "to measure or express something as a number", "quantify the impact", "The study attempts to quantify the impact of delayed delivery.", "这项研究试图量化延迟交货的影响。", "分析决策"],
    ["ratio", "/ˈreɪʃiəʊ/", "noun", "比率；两个数量之间的关系", "the relationship between two amounts expressed by comparison", "conversion ratio", "The conversion ratio improved after the website redesign.", "网站改版后的转化比率有所提高。", "分析决策"],
    ["sample", "/ˈsɑːmpl/", "noun", "样本；用于代表整体的一小部分", "a smaller group or amount used to represent a whole", "representative sample", "The survey used a representative sample of five hundred customers.", "这项调查采用了五百名客户的代表性样本。", "分析决策"],
    ["survey", "/ˈsɜːveɪ/", "noun", "问卷调查；系统收集意见或信息的方法", "a set of questions used to collect information from people", "conduct a survey", "We conducted a survey to understand remote workers' needs.", "我们开展了一项调查，以了解远程员工的需求。", "分析决策"],
    ["impact", "/ˈɪmpækt/", "noun", "影响；行动对结果产生的明显作用", "a strong effect that an action or event has on something", "assess the impact", "We assessed the impact of the price change on demand.", "我们评估了价格变动对需求的影响。", "分析决策"],
    ["implication", "/ˌɪmplɪˈkeɪʃn/", "noun", "潜在后果；决定可能带来的影响", "a possible effect or consequence of an action or decision", "financial implication", "The proposal has significant financial implications.", "该提案可能带来重大的财务影响。", "分析决策"],
    ["optimization", "/ˌɒptɪmaɪˈzeɪʃn/", "noun", "优化；使流程达到最佳效果", "the process of making a system or process as effective as possible", "process optimization", "Route optimization reduced fuel use and delivery time.", "路线优化减少了燃料消耗和配送时间。", "分析决策"],
    ["conclusion", "/kənˈkluːʒn/", "noun", "结论；根据分析最终形成的判断", "a judgment reached after considering evidence", "reach a conclusion", "The committee reached a conclusion after reviewing all bids.", "委员会审查所有投标后得出了结论。", "分析决策"],
    ["accuracy", "/ˈækjərəsi/", "noun", "准确度；信息接近正确值的程度", "the degree to which information or measurement is correct", "improve accuracy", "Double-checking entries improved the accuracy of the database.", "复核录入内容提高了数据库的准确度。", "分析决策"],

    ["bargain", "/ˈbɑːɡən/", "noun", "划算交易；以有利条件达成的买卖", "an agreement or purchase made on favorable terms", "strike a bargain", "The buyer struck a bargain after two rounds of discussion.", "买方经过两轮讨论达成了一笔划算交易。", "商务谈判"],
    ["clause", "/klɔːz/", "noun", "合同条款；协议中的特定规定", "a particular section or condition in a legal agreement", "termination clause", "The lawyer revised the termination clause before signing.", "律师在签约前修订了终止条款。", "商务谈判"],
    ["concession", "/kənˈseʃn/", "noun", "让步；为达成协议而放弃的要求", "something given up in order to reach an agreement", "make a concession", "Both sides made a concession on delivery timing.", "双方都在交货时间上作出了让步。", "商务谈判"],
    ["counteroffer", "/ˈkaʊntərɒfə(r)/", "noun", "还价方案；针对原报价提出的新条件", "a new offer made in response to an earlier offer", "submit a counteroffer", "We submitted a counteroffer with a longer contract period.", "我们提交了一个延长合同期限的还价方案。", "商务谈判"],
    ["deal", "/diːl/", "noun", "商业协议；双方达成的交易安排", "a business agreement between two or more parties", "close a deal", "The teams closed the deal before the end of the quarter.", "双方团队在季度结束前完成了交易。", "商务谈判"],
    ["dispute", "/dɪˈspjuːt/", "noun", "争议；对权利或条件的正式分歧", "a serious disagreement about terms, rights, or facts", "resolve a dispute", "A written record helped resolve the payment dispute.", "书面记录帮助解决了付款争议。", "商务谈判"],
    ["incentive", "/ɪnˈsentɪv/", "noun", "激励条件；促使对方行动的利益", "a benefit offered to encourage a particular action", "financial incentive", "The supplier offered a financial incentive for early payment.", "供应商为提前付款提供了财务激励。", "商务谈判"],
    ["leverage", "/ˈliːvərɪdʒ/", "noun", "谈判筹码；影响结果的优势", "an advantage that gives someone influence in a negotiation", "gain leverage", "A competing offer gave the buyer greater leverage.", "另一份竞争报价让买方获得了更大的谈判筹码。", "商务谈判"],
    ["obligation", "/ˌɒblɪˈɡeɪʃn/", "noun", "履约义务；必须依法或依约完成的责任", "a legal or formal duty that must be fulfilled", "contractual obligation", "Both parties must meet their contractual obligations.", "双方都必须履行合同义务。", "商务谈判"],
    ["partnership", "/ˈpɑːtnəʃɪp/", "noun", "合作关系；共同经营或开展项目的安排", "an arrangement in which parties work or do business together", "strategic partnership", "The agreement established a strategic partnership in Asia.", "该协议在亚洲建立了战略合作关系。", "商务谈判"],
    ["penalty", "/ˈpenəlti/", "noun", "违约罚金；未履行条件产生的处罚", "a charge or punishment for breaking an agreement", "late-delivery penalty", "The contract includes a penalty for late delivery.", "合同包含延迟交货罚金。", "商务谈判"],
    ["persuasion", "/pəˈsweɪʒn/", "noun", "说服；促使他人接受观点的过程", "the act of convincing someone to accept an idea or proposal", "power of persuasion", "Evidence is usually more effective than pressure in persuasion.", "在说服中，证据通常比施压更有效。", "商务谈判"],
    ["terms", "/tɜːmz/", "plural noun", "交易条件；协议规定的付款或交付要求", "the conditions that form part of an agreement", "negotiate terms", "We negotiated payment terms that protect both companies.", "我们协商了能保护双方公司的付款条件。", "商务谈判"],
    ["agreement", "/əˈɡriːmənt/", "noun", "协议；经讨论后共同接受的安排", "an arrangement accepted by two or more parties", "reach an agreement", "The two firms reached an agreement on data ownership.", "两家公司就数据所有权达成了协议。", "商务谈判"],
    ["bid", "/bɪd/", "noun", "竞标报价；为赢得合同提出的价格方案", "a formal offer to complete work or buy something at a stated price", "submit a bid", "The company submitted a competitive bid for the project.", "公司为该项目提交了具有竞争力的投标报价。", "商务谈判"],
    ["commission", "/kəˈmɪʃn/", "noun", "销售佣金；按成交额支付的报酬", "payment calculated as a percentage of sales", "earn commission", "Representatives earn commission on completed sales.", "销售代表会从完成的销售中获得佣金。", "商务谈判"],
    ["compensation", "/ˌkɒmpenˈseɪʃn/", "noun", "补偿；因损失或服务获得的金钱", "money given for loss, damage, or work performed", "seek compensation", "The customer sought compensation for the canceled service.", "客户因服务取消而要求补偿。", "商务谈判"],
    ["confidentiality", "/ˌkɒnfɪdenʃiˈæləti/", "noun", "保密义务；不公开敏感信息的要求", "the duty to keep sensitive information private", "maintain confidentiality", "All participants must maintain confidentiality during the talks.", "所有参与者在会谈期间都必须保密。", "商务谈判"],
    ["demand", "/dɪˈmɑːnd/", "noun", "谈判要求；一方坚持需要满足的条件", "a firm request that one party expects another to meet", "meet a demand", "The vendor could not meet the buyer's demand for same-day delivery.", "供应商无法满足买方当天交货的要求。", "商务谈判"],
    ["endorsement", "/ɪnˈdɔːsmənt/", "noun", "正式支持；公开认可某项方案", "public or official approval of a person, product, or proposal", "gain endorsement", "The proposal gained endorsement from the regional board.", "该提案获得了区域董事会的正式支持。", "商务谈判"],
    ["exclusivity", "/ˌekskluːˈsɪvəti/", "noun", "独家权；限制与其他伙伴合作的安排", "the right to be the only party allowed to sell or provide something", "exclusivity period", "The distributor requested a two-year exclusivity period.", "分销商要求两年的独家经营期。", "商务谈判"],
    ["installment", "/ɪnˈstɔːlmənt/", "noun", "分期付款；总金额中的一次支付", "one of several payments made over a period", "monthly installment", "The final installment is due after installation.", "最后一期款项在安装完成后到期。", "商务谈判"],
    ["licensing", "/ˈlaɪsnsɪŋ/", "noun", "许可授权；允许他人使用技术或品牌", "the process of giving permission to use a product, brand, or technology", "licensing agreement", "The licensing agreement covers three international markets.", "这份许可协议覆盖三个国际市场。", "商务谈判"],
    ["renewal", "/rɪˈnjuːəl/", "noun", "续约；延长合同或服务期限", "the act of extending an agreement or subscription", "contract renewal", "Prices will be reviewed at the next contract renewal.", "价格将在下次合同续约时审查。", "商务谈判"],
    ["settlement", "/ˈsetlmənt/", "noun", "和解协议；为结束争议达成的安排", "an agreement that ends a dispute", "reach a settlement", "The parties reached a settlement without going to court.", "双方在不诉诸法院的情况下达成了和解。", "商务谈判"],
    ["valuation", "/ˌvæljuˈeɪʃn/", "noun", "估值；对企业或资产价值的评定", "an assessment of how much a business or asset is worth", "company valuation", "Recent growth increased the company's valuation.", "近期增长提高了公司的估值。", "商务谈判"],
    ["arbitration", "/ˌɑːbɪˈtreɪʃn/", "noun", "仲裁；由独立第三方裁决争议", "a process in which an independent person decides a dispute", "enter arbitration", "The contract requires arbitration before legal action.", "合同要求在采取法律行动前先进行仲裁。", "商务谈判"],
    ["condition", "/kənˈdɪʃn/", "noun", "附加条件；协议成立必须满足的要求", "a requirement that must be met as part of an agreement", "accept a condition", "We accepted the condition after clarifying its scope.", "在明确其范围后，我们接受了该附加条件。", "商务谈判"],
    ["provision", "/prəˈvɪʒn/", "noun", "合同规定；为特定情况写入的条文", "a statement in an agreement dealing with a particular matter", "contractual provision", "A new provision protects confidential customer information.", "一项新条款保护客户机密信息。", "商务谈判"],
    ["withdrawal", "/wɪðˈdrɔːəl/", "noun", "撤回；正式取消报价或提案", "the act of formally removing an offer or proposal", "withdrawal of an offer", "The sudden withdrawal of the offer reopened negotiations.", "报价突然撤回使谈判重新开始。", "商务谈判"],

    ["ambiguity", "/ˌæmbɪˈɡjuːəti/", "noun", "歧义；可以产生多种理解的表达", "a lack of clarity that allows more than one interpretation", "avoid ambiguity", "Specific dates help avoid ambiguity in international emails.", "明确的日期有助于避免国际邮件中的歧义。", "跨文化沟通"],
    ["convention", "/kənˈvenʃn/", "noun", "社会惯例；群体普遍接受的行为方式", "a customary way of behaving within a group or society", "social convention", "Greeting conventions vary widely between cultures.", "不同文化的问候惯例差异很大。", "跨文化沟通"],
    ["cultural", "/ˈkʌltʃərəl/", "adjective", "文化相关的；源于群体价值和习惯的", "connected with the beliefs, customs, and practices of a society", "cultural difference", "Cultural differences can influence how silence is interpreted.", "文化差异会影响人们对沉默的理解。", "跨文化沟通"],
    ["dialect", "/ˈdaɪəlekt/", "noun", "方言；某地区或群体使用的语言变体", "a form of a language used in a particular region or group", "regional dialect", "The speaker used a regional dialect that was new to me.", "演讲者使用了一种我不熟悉的地方方言。", "跨文化沟通"],
    ["empathy", "/ˈempəθi/", "noun", "共情；理解他人感受和处境的能力", "the ability to understand another person's feelings and experience", "show empathy", "Showing empathy can calm a frustrated customer.", "表达共情能让沮丧的客户平静下来。", "跨文化沟通"],
    ["fluency", "/ˈfluːənsi/", "noun", "流利度；自然顺畅使用语言的能力", "the ability to speak or write a language smoothly and easily", "develop fluency", "Regular conversation practice helps develop fluency.", "定期对话练习有助于提高流利度。", "跨文化沟通"],
    ["gesture", "/ˈdʒestʃə(r)/", "noun", "手势；用身体动作传达的信息", "a movement of the hands or body that communicates meaning", "friendly gesture", "A friendly gesture in one culture may be confusing in another.", "一种文化中的友好手势在另一种文化中可能令人困惑。", "跨文化沟通"],
    ["idiom", "/ˈɪdiəm/", "noun", "习语；含义不能逐字理解的固定表达", "a fixed expression whose meaning is not clear from its individual words", "common idiom", "Avoid local idioms when writing for a global audience.", "为全球读者写作时应避免地方习语。", "跨文化沟通"],
    ["nuance", "/ˈnjuːɑːns/", "noun", "细微差别；意义或语气中的微妙变化", "a small but important difference in meaning, tone, or feeling", "subtle nuance", "The translator preserved the subtle nuance of the original message.", "译者保留了原信息中的细微语气差别。", "跨文化沟通"],
    ["perception", "/pəˈsepʃn/", "noun", "观感；人们理解某事的方式", "the way in which someone understands or views something", "public perception", "Response time strongly affects customers' perception of service quality.", "响应时间会显著影响客户对服务质量的观感。", "跨文化沟通"],
    ["rapport", "/ræˈpɔː(r)/", "noun", "融洽关系；建立在理解和信任上的联系", "a friendly relationship based on mutual understanding", "build rapport", "Asking thoughtful questions helps build rapport with clients.", "提出用心的问题有助于与客户建立融洽关系。", "跨文化沟通"],
    ["register", "/ˈredʒɪstə(r)/", "noun", "语域；适合特定场合的语言正式程度", "the level and style of language used in a particular situation", "formal register", "A formal register is appropriate for the first client email.", "第一次给客户发邮件时适合使用正式语域。", "跨文化沟通"],
    ["respectful", "/rɪˈspektfl/", "adjective", "尊重他人的；体现礼貌和重视的", "showing consideration and respect for other people", "respectful tone", "Use a respectful tone even when correcting an error.", "即使纠正错误，也应使用尊重他人的语气。", "跨文化沟通"],
    ["tolerance", "/ˈtɒlərəns/", "noun", "包容度；接受不同观点和做法的意愿", "willingness to accept beliefs or behavior different from one's own", "promote tolerance", "International teamwork requires patience and tolerance.", "国际团队合作需要耐心和包容。", "跨文化沟通"],
    ["translation", "/trænzˈleɪʃn/", "noun", "翻译文本；从一种语言转换成另一种语言的内容", "text or speech converted from one language into another", "accurate translation", "An accurate translation should preserve both meaning and tone.", "准确的翻译应同时保留含义和语气。", "跨文化沟通"],
    ["viewpoint", "/ˈvjuːpɔɪnt/", "noun", "观点角度；观察和判断问题的立场", "a particular way of thinking about or seeing an issue", "different viewpoint", "Invite each participant to explain their viewpoint.", "请每位参与者说明自己的观点。", "跨文化沟通"],
    ["adaptation", "/ˌædæpˈteɪʃn/", "noun", "适应调整；为新环境作出的改变", "a change made to suit a new situation or environment", "cultural adaptation", "Cultural adaptation takes time and active observation.", "文化适应需要时间和主动观察。", "跨文化沟通"],
    ["awareness", "/əˈweənəs/", "noun", "意识；对差异或问题的理解", "knowledge and understanding of a situation or issue", "cultural awareness", "Cultural awareness reduces accidental misunderstandings.", "文化意识能减少无意造成的误解。", "跨文化沟通"],
    ["inclusion", "/ɪnˈkluːʒn/", "noun", "包容参与；确保不同成员都能加入", "the practice of ensuring different people can participate fully", "promote inclusion", "Rotating meeting times promotes inclusion across time zones.", "轮换会议时间能促进不同时区成员的参与。", "跨文化沟通"],
    ["nationality", "/ˌnæʃəˈnæləti/", "noun", "国籍；个人依法所属的国家身份", "the legal status of belonging to a particular nation", "state your nationality", "The form asks applicants to state their nationality.", "表格要求申请者填写国籍。", "跨文化沟通"],
    ["norm", "/nɔːm/", "noun", "行为规范；群体中被视为正常的做法", "an accepted standard of behavior within a group", "cultural norm", "Direct eye contact is not the same cultural norm everywhere.", "直接目光接触并非各地相同的文化规范。", "跨文化沟通"],
    ["offense", "/əˈfens/", "noun", "冒犯感；因言行不当产生的不快", "a feeling of being upset by disrespectful words or behavior", "cause offense", "The expression may cause offense in some regions.", "这种表达在某些地区可能会引起冒犯。", "跨文化沟通"],
    ["politeness", "/pəˈlaɪtnəs/", "noun", "礼貌性；对他人表示尊重的言行", "behavior or language that shows respect for others", "level of politeness", "Requests differ in their expected level of politeness.", "不同请求所需的礼貌程度有所不同。", "跨文化沟通"],
    ["prejudice", "/ˈpredʒudɪs/", "noun", "成见；不了解事实就形成的负面判断", "an unfair negative opinion formed without sufficient knowledge", "challenge prejudice", "Training can help staff recognize and challenge prejudice.", "培训能帮助员工识别并质疑成见。", "跨文化沟通"],
    ["protocol", "/ˈprəʊtəkɒl/", "noun", "礼宾规范；正式场合应遵循的程序", "official rules for behavior in formal situations", "business protocol", "Local business protocol requires exchanging cards at the start.", "当地商务礼仪要求在会面开始时交换名片。", "跨文化沟通"],
    ["receptive", "/rɪˈseptɪv/", "adjective", "乐于接受的；愿意考虑新观点的", "willing to listen to or consider new ideas", "receptive to feedback", "She was receptive to feedback about her presentation style.", "她愿意接受有关演示风格的反馈。", "跨文化沟通"],
    ["relationship", "/rɪˈleɪʃnʃɪp/", "noun", "合作关系；人与人或组织间的联系", "the way in which people or organizations are connected", "long-term relationship", "Trust is essential to a long-term business relationship.", "信任对于长期商业关系至关重要。", "跨文化沟通"],
    ["misinterpretation", "/ˌmɪsɪntɜːprəˈteɪʃn/", "noun", "误读；对信息作出错误理解", "an incorrect understanding of the meaning of something", "avoid misinterpretation", "A written summary can avoid misinterpretation after a meeting.", "会后书面总结可以避免误读。", "跨文化沟通"],
    ["multicultural", "/ˌmʌltiˈkʌltʃərəl/", "adjective", "多元文化的；包含多种文化背景的", "including people or traditions from several cultures", "multicultural team", "A multicultural team can offer a wider range of ideas.", "多元文化团队可以提供更广泛的想法。", "跨文化沟通"],
    ["intercultural", "/ˌɪntəˈkʌltʃərəl/", "adjective", "跨文化的；涉及不同文化之间互动的", "involving communication or interaction between different cultures", "intercultural competence", "Intercultural competence is essential for global client work.", "跨文化能力对全球客户工作至关重要。", "跨文化沟通"],

    ["abstract", "/ˈæbstrækt/", "noun", "摘要；研究文章的简短概述", "a short summary placed at the beginning of an academic paper", "write an abstract", "Write the abstract after the main analysis is complete.", "在主体分析完成后再撰写摘要。", "学术表达"],
    ["acknowledge", "/əkˈnɒlɪdʒ/", "verb", "承认；明确接受某个事实或贡献", "to accept that something is true or recognize a contribution", "acknowledge a limitation", "The report acknowledges a limitation in the data.", "报告承认了数据中的一项局限。", "学术表达"],
    ["analogy", "/əˈnælədʒi/", "noun", "类比；通过相似关系解释概念", "a comparison used to explain an idea through similarity", "use an analogy", "The lecturer used an analogy to explain cloud storage.", "讲师用类比解释了云存储。", "学术表达"],
    ["argument", "/ˈɑːɡjumənt/", "noun", "论点；由理由和证据支持的主张", "a claim supported by reasons and evidence", "develop an argument", "Each paragraph should develop one part of the argument.", "每个段落都应展开论点的一部分。", "学术表达"],
    ["citation", "/saɪˈteɪʃn/", "noun", "文献引用；标明信息来源的记录", "a reference that identifies the source of information", "include a citation", "Include a citation whenever you use another author's data.", "使用其他作者的数据时都应添加引用。", "学术表达"],
    ["coherent", "/kəʊˈhɪərənt/", "adjective", "连贯的；各部分逻辑清楚地连接", "logical, consistent, and easy to follow", "coherent explanation", "The revised report presents a more coherent explanation.", "修订后的报告给出了更连贯的解释。", "学术表达"],
    ["compelling", "/kəmˈpelɪŋ/", "adjective", "有说服力的；能使人相信或关注的", "strong and convincing enough to attract belief or attention", "compelling evidence", "The case study provides compelling evidence for the approach.", "案例研究为这种方法提供了有力证据。", "学术表达"],
    ["comprehensive", "/ˌkɒmprɪˈhensɪv/", "adjective", "全面的；包含所有重要部分的", "including all or nearly all important aspects", "comprehensive review", "The paper offers a comprehensive review of recent research.", "这篇论文对近期研究进行了全面回顾。", "学术表达"],
    ["concept", "/ˈkɒnsept/", "noun", "概念；用于理解事物的一般性观念", "a general idea used to understand a subject", "key concept", "The first chapter introduces the key concept of social trust.", "第一章介绍了社会信任这一关键概念。", "学术表达"],
    ["contradict", "/ˌkɒntrəˈdɪkt/", "verb", "反驳；与某个说法或证据不一致", "to state or show the opposite of a claim", "contradict a finding", "The new figures contradict the earlier forecast.", "新数据与早先的预测相矛盾。", "学术表达"],
    ["convey", "/kənˈveɪ/", "verb", "传达；清楚表达含义或感受", "to communicate a meaning, idea, or feeling", "convey a message", "The chart conveys the main trend more clearly than the table.", "这张图表比表格更清楚地传达了主要趋势。", "学术表达"],
    ["critique", "/krɪˈtiːk/", "noun", "评析；有依据地评价优点和不足", "a detailed evaluation of strengths and weaknesses", "write a critique", "The assignment requires a critique of two competing theories.", "这项作业要求评析两种相互竞争的理论。", "学术表达"],
    ["derive", "/dɪˈraɪv/", "verb", "推导；从来源或证据中得出", "to obtain or develop something from a source", "derive a conclusion", "The conclusion is derived from three independent datasets.", "该结论由三个独立数据集推导而来。", "学术表达"],
    ["distinguish", "/dɪˈstɪŋɡwɪʃ/", "verb", "区分；识别事物之间的差别", "to recognize or explain the difference between things", "distinguish between", "The study distinguishes between short-term and long-term effects.", "该研究区分了短期影响和长期影响。", "学术表达"],
    ["elaborate", "/ɪˈlæbəreɪt/", "verb", "详述；补充更多解释和细节", "to explain an idea in greater detail", "elaborate on a point", "Could you elaborate on how the sample was selected?", "你能详细说明样本是如何选取的吗？", "学术表达"],
    ["framework", "/ˈfreɪmwɜːk/", "noun", "分析框架；组织概念或研究的结构", "a structure of ideas used to organize analysis or research", "analytical framework", "The framework links customer behavior to service design.", "该分析框架把客户行为与服务设计联系起来。", "学术表达"],
    ["illustrate", "/ˈɪləstreɪt/", "verb", "阐明；用例子或图表使观点清楚", "to make an idea clear by using an example or image", "illustrate a point", "The example illustrates why context matters.", "这个例子说明了语境为何重要。", "学术表达"],
    ["justify", "/ˈdʒʌstɪfaɪ/", "verb", "论证合理性；用理由支持选择", "to show that a decision or belief is reasonable", "justify a choice", "You should justify your choice of research method.", "你应论证所选研究方法的合理性。", "学术表达"],
    ["literature", "/ˈlɪtrətʃə(r)/", "noun", "研究文献；某领域已发表的学术作品", "published academic writing on a particular subject", "review the literature", "The introduction reviews the literature on remote learning.", "引言回顾了有关远程学习的研究文献。", "学术表达"],
    ["notion", "/ˈnəʊʃn/", "noun", "观念；对某事的一般理解", "an idea or belief about something", "challenge a notion", "The findings challenge the notion that price is the main factor.", "研究结果质疑了价格是主要因素这一观念。", "学术表达"],
    ["paragraph", "/ˈpærəɡrɑːf/", "noun", "段落；围绕一个中心意思组织的文字", "a section of writing focused on one main idea", "topic paragraph", "Begin each paragraph with a clear controlling idea.", "每个段落都应以清晰的中心意思开头。", "学术表达"],
    ["paraphrase", "/ˈpærəfreɪz/", "verb", "释义改写；用自己的语言重述内容", "to express the same meaning using different words", "paraphrase a source", "Paraphrase the source accurately and still provide a citation.", "应准确改写来源内容，同时仍需注明引用。", "学术表达"],
    ["principle", "/ˈprɪnsəpl/", "noun", "基本原则；指导判断或方法的核心规则", "a fundamental rule or belief that guides reasoning or action", "underlying principle", "The same underlying principle applies to both cases.", "同一项基本原则适用于这两个案例。", "学术表达"],
    ["source", "/sɔːs/", "noun", "资料来源；信息或证据的出处", "the place, person, or document from which information comes", "reliable source", "Use a reliable source to support each major claim.", "应使用可靠来源支持每项主要主张。", "学术表达"],
    ["synthesis", "/ˈsɪnθəsɪs/", "noun", "综合；把多个来源整合成整体观点", "the combination of ideas from several sources into a new whole", "synthesis of research", "The conclusion provides a clear synthesis of the research.", "结论对研究内容进行了清晰综合。", "学术表达"],
    ["thesis", "/ˈθiːsɪs/", "noun", "论文主旨；文章要证明的核心观点", "the central claim that a paper aims to support", "thesis statement", "The thesis statement should be specific and arguable.", "论文主旨陈述应当具体且可论证。", "学术表达"],
    ["vocabulary", "/vəˈkæbjələri/", "noun", "词汇体系；某领域使用的一组词语", "the set of words used in a language or subject area", "academic vocabulary", "Academic vocabulary helps writers express precise relationships.", "学术词汇能帮助写作者表达精确关系。", "学术表达"],
    ["whereas", "/ˌweərˈæz/", "conjunction", "然而；用于对比两个事实", "used to contrast two different facts or situations", "whereas the latter", "The first method is faster, whereas the second is more accurate.", "第一种方法更快，而第二种方法更准确。", "学术表达"],
    ["furthermore", "/ˌfɜːðəˈmɔː(r)/", "adverb", "此外；用于补充更有力的信息", "used to add another important point", "furthermore, the data", "The process is cheaper; furthermore, it produces less waste.", "这个流程成本更低；此外，它产生的废弃物更少。", "学术表达"],
    ["subsequently", "/ˈsʌbsɪkwəntli/", "adverb", "随后；在某事件之后发生", "after a particular event or at a later time", "subsequently revised", "The model was tested and subsequently revised.", "该模型经过测试，随后又进行了修订。", "学术表达"]
  ];

  const makeId = (word) => word
    .normalize("NFKD")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

  window.ENGLISH_COMPASS_VOCABULARY_BULK_B2 = Object.freeze(rows.map(([
    word,
    phonetic,
    partOfSpeech,
    definition,
    definitionEn,
    collocation,
    example,
    exampleZh,
    topic
  ]) => Object.freeze({
    id: makeId(word),
    word,
    phonetic,
    partOfSpeech,
    definition,
    definitionEn,
    collocation,
    example,
    exampleZh,
    topic,
    level: "B2"
  })));
})();
