(function () {
  "use strict";

  window.ENGLISH_COMPASS_MORE_VOCABULARY_B1 = Object.freeze([
    {
      id: "assign",
      word: "assign",
      phonetic: "/əˈsaɪn/",
      partOfSpeech: "verb",
      definition: "分派；把工作交给某人",
      definitionEn: "to give someone a particular job or responsibility",
      collocation: "assign a task",
      example: "The manager will assign each task before the meeting ends.",
      exampleZh: "经理会在会议结束前分派每项任务。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "attendance",
      word: "attendance",
      phonetic: "/əˈtendəns/",
      partOfSpeech: "noun",
      definition: "出勤情况；到场记录",
      definitionEn: "the fact of being present at work or an event",
      collocation: "check attendance",
      example: "Please check the attendance list before the training begins.",
      exampleZh: "请在培训开始前核对出勤名单。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "budget",
      word: "budget",
      phonetic: "/ˈbʌdʒɪt/",
      partOfSpeech: "noun",
      definition: "预算；可用资金计划",
      definitionEn: "a plan showing how much money is available and how it will be spent",
      collocation: "stay within budget",
      example: "We need to finish the project within the agreed budget.",
      exampleZh: "我们需要在商定的预算内完成项目。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "capacity",
      word: "capacity",
      phonetic: "/kəˈpæsəti/",
      partOfSpeech: "noun",
      definition: "容量；可承担的工作量",
      definitionEn: "the amount of work that a person or team is able to do",
      collocation: "work at full capacity",
      example: "Our support team is working at full capacity this week.",
      exampleZh: "我们的支持团队本周正在满负荷工作。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "department",
      word: "department",
      phonetic: "/dɪˈpɑːtmənt/",
      partOfSpeech: "noun",
      definition: "部门；机构中的业务单位",
      definitionEn: "a section of an organization that has a particular purpose",
      collocation: "the sales department",
      example: "Please send the report to the finance department.",
      exampleZh: "请把报告发送给财务部门。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "document",
      word: "document",
      phonetic: "/ˈdɒkjumənt/",
      partOfSpeech: "noun",
      definition: "文件；记录信息的材料",
      definitionEn: "a written or digital file that contains information",
      collocation: "share a document",
      example: "I shared the updated document with the whole team.",
      exampleZh: "我把更新后的文件分享给了整个团队。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "equipment",
      word: "equipment",
      phonetic: "/ɪˈkwɪpmənt/",
      partOfSpeech: "noun",
      definition: "设备；完成工作所需的器材",
      definitionEn: "the tools or machines needed for a particular activity",
      collocation: "check the equipment",
      example: "Always check the equipment before opening the store.",
      exampleZh: "开店前一定要检查设备。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "expense",
      word: "expense",
      phonetic: "/ɪkˈspens/",
      partOfSpeech: "noun",
      definition: "开支；工作中产生的费用",
      definitionEn: "money that is spent while doing a job or activity",
      collocation: "claim an expense",
      example: "Keep the receipt if you need to claim a travel expense.",
      exampleZh: "如果需要报销差旅开支，请保留收据。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "policy",
      word: "policy",
      phonetic: "/ˈpɒləsi/",
      partOfSpeech: "noun",
      definition: "规章；组织采用的办事原则",
      definitionEn: "an official rule or plan used by an organization",
      collocation: "follow company policy",
      example: "The refund must follow company policy.",
      exampleZh: "退款必须遵循公司规章。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "recruit",
      word: "recruit",
      phonetic: "/rɪˈkruːt/",
      partOfSpeech: "verb",
      definition: "招聘；寻找新员工",
      definitionEn: "to find and employ new people for an organization",
      collocation: "recruit new staff",
      example: "The company plans to recruit two new assistants.",
      exampleZh: "公司计划招聘两名新助理。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "salary",
      word: "salary",
      phonetic: "/ˈsæləri/",
      partOfSpeech: "noun",
      definition: "薪资；按月支付的工作报酬",
      definitionEn: "a fixed amount of money paid regularly for work",
      collocation: "discuss the salary",
      example: "The salary details are included in the job offer.",
      exampleZh: "薪资详情已写在录用通知中。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "shift",
      word: "shift",
      phonetic: "/ʃɪft/",
      partOfSpeech: "noun",
      definition: "班次；一段轮班工作时间",
      definitionEn: "a period of time during which a person works",
      collocation: "work the evening shift",
      example: "I can work the evening shift on Friday.",
      exampleZh: "星期五我可以上晚班。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "training",
      word: "training",
      phonetic: "/ˈtreɪnɪŋ/",
      partOfSpeech: "noun",
      definition: "培训；学习工作技能的过程",
      definitionEn: "the process of learning the skills needed for a job",
      collocation: "attend a training session",
      example: "All new employees attend a safety training session.",
      exampleZh: "所有新员工都要参加安全培训。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "vacancy",
      word: "vacancy",
      phonetic: "/ˈveɪkənsi/",
      partOfSpeech: "noun",
      definition: "职位空缺；尚未有人担任的工作",
      definitionEn: "a job that is available for someone to apply for",
      collocation: "apply for a vacancy",
      example: "I saw the customer service vacancy on your website.",
      exampleZh: "我在贵公司网站上看到了客户服务职位空缺。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "workplace",
      word: "workplace",
      phonetic: "/ˈwɜːkpleɪs/",
      partOfSpeech: "noun",
      definition: "工作场所；人们办公的地方",
      definitionEn: "the place where people do their jobs",
      collocation: "a safe workplace",
      example: "Clear rules help create a safe workplace.",
      exampleZh: "明确的规则有助于创造安全的工作场所。",
      topic: "职场运营",
      level: "B1"
    },
    {
      id: "confirm",
      word: "confirm",
      phonetic: "/kənˈfɜːm/",
      partOfSpeech: "verb",
      definition: "确认；证明信息无误",
      definitionEn: "to say or show that information is correct",
      collocation: "confirm the details",
      example: "Could you confirm the delivery address by email?",
      exampleZh: "您能通过电子邮件确认配送地址吗？",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "contact",
      word: "contact",
      phonetic: "/ˈkɒntækt/",
      partOfSpeech: "verb",
      definition: "联系；与某人取得沟通",
      definitionEn: "to communicate with someone by phone, email, or another method",
      collocation: "contact a client",
      example: "I will contact the client as soon as I have an update.",
      exampleZh: "一有最新进展，我就会联系客户。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "describe",
      word: "describe",
      phonetic: "/dɪˈskraɪb/",
      partOfSpeech: "verb",
      definition: "描述；用语言说明特征",
      definitionEn: "to say what someone or something is like",
      collocation: "describe the issue",
      example: "Please describe the issue in as much detail as possible.",
      exampleZh: "请尽可能详细地描述这个问题。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "emphasize",
      word: "emphasize",
      phonetic: "/ˈemfəsaɪz/",
      partOfSpeech: "verb",
      definition: "强调；使重点更加突出",
      definitionEn: "to give special importance to something you say",
      collocation: "emphasize a key point",
      example: "The presenter emphasized the need for clear communication.",
      exampleZh: "演讲者强调了清晰沟通的必要性。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "inform",
      word: "inform",
      phonetic: "/ɪnˈfɔːm/",
      partOfSpeech: "verb",
      definition: "通知；正式告知消息",
      definitionEn: "to officially tell someone about something",
      collocation: "inform the team",
      example: "Please inform the team about the new deadline.",
      exampleZh: "请把新的截止时间通知团队。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "mention",
      word: "mention",
      phonetic: "/ˈmenʃn/",
      partOfSpeech: "verb",
      definition: "提及；简短地说到某事",
      definitionEn: "to speak or write about something briefly",
      collocation: "mention a concern",
      example: "She mentioned one concern during the meeting.",
      exampleZh: "她在会议中提及了一个顾虑。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "negotiate",
      word: "negotiate",
      phonetic: "/nɪˈɡəʊʃieɪt/",
      partOfSpeech: "verb",
      definition: "协商；通过讨论达成协议",
      definitionEn: "to discuss something in order to reach an agreement",
      collocation: "negotiate a contract",
      example: "Both sides met to negotiate the delivery schedule.",
      exampleZh: "双方会面协商配送时间表。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "request",
      word: "request",
      phonetic: "/rɪˈkwest/",
      partOfSpeech: "noun / verb",
      definition: "请求；礼貌地要求某事",
      definitionEn: "an act of asking politely or formally for something",
      collocation: "respond to a request",
      example: "We responded to the client's request this morning.",
      exampleZh: "我们今天上午回复了客户的请求。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "summarize",
      word: "summarize",
      phonetic: "/ˈsʌməraɪz/",
      partOfSpeech: "verb",
      definition: "概括；简要说明要点",
      definitionEn: "to give the main points of something in a short form",
      collocation: "summarize the discussion",
      example: "Could you summarize the discussion in three sentences?",
      exampleZh: "你能用三句话概括这次讨论吗？",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "update",
      word: "update",
      phonetic: "/ˈʌpdeɪt/",
      partOfSpeech: "noun",
      definition: "最新进展；新增的信息",
      definitionEn: "new information about a changing situation",
      collocation: "give a quick update",
      example: "I will give everyone a quick project update.",
      exampleZh: "我会向大家简要说明项目的最新进展。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "audience",
      word: "audience",
      phonetic: "/ˈɔːdiəns/",
      partOfSpeech: "noun",
      definition: "听众；观看演示的一群人",
      definitionEn: "the people who watch or listen to a presentation",
      collocation: "engage the audience",
      example: "Start with a question to engage the audience.",
      exampleZh: "以一个问题开场来吸引听众。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "proposal",
      word: "proposal",
      phonetic: "/prəˈpəʊzl/",
      partOfSpeech: "noun",
      definition: "提案；供讨论的正式建议",
      definitionEn: "a formal suggestion or plan for people to consider",
      collocation: "present a proposal",
      example: "We will present our proposal to the client tomorrow.",
      exampleZh: "我们明天会向客户展示提案。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "presentation",
      word: "presentation",
      phonetic: "/ˌpreznˈteɪʃn/",
      partOfSpeech: "noun",
      definition: "演示；面向他人的正式讲解",
      definitionEn: "a formal talk in which information is explained to a group",
      collocation: "give a presentation",
      example: "I practiced my presentation before speaking to the client.",
      exampleZh: "在向客户讲解前，我练习了自己的演示。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "instruction",
      word: "instruction",
      phonetic: "/ɪnˈstrʌkʃn/",
      partOfSpeech: "noun",
      definition: "指示；说明应如何操作的话",
      definitionEn: "information that tells someone what to do or how to do it",
      collocation: "follow an instruction",
      example: "Read each instruction carefully before using the system.",
      exampleZh: "使用系统前请仔细阅读每项指示。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "detail",
      word: "detail",
      phonetic: "/ˈdiːteɪl/",
      partOfSpeech: "noun",
      definition: "细节；整体中的具体信息",
      definitionEn: "a small piece of information about something",
      collocation: "check every detail",
      example: "Please check every detail before sending the email.",
      exampleZh: "发送邮件前请检查每个细节。",
      topic: "职场沟通",
      level: "B1"
    },
    {
      id: "complaint",
      word: "complaint",
      phonetic: "/kəmˈpleɪnt/",
      partOfSpeech: "noun",
      definition: "投诉；表达不满的意见",
      definitionEn: "a statement that says someone is unhappy with a product or service",
      collocation: "handle a complaint",
      example: "A calm reply can help us handle a complaint well.",
      exampleZh: "冷静的回复能帮助我们妥善处理投诉。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "replacement",
      word: "replacement",
      phonetic: "/rɪˈpleɪsmənt/",
      partOfSpeech: "noun",
      definition: "替换品；用来代替原物的东西",
      definitionEn: "a product or item that takes the place of another one",
      collocation: "offer a replacement",
      example: "We can offer a free replacement for the damaged item.",
      exampleZh: "我们可以为受损商品免费提供替换品。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "guarantee",
      word: "guarantee",
      phonetic: "/ˌɡærənˈtiː/",
      partOfSpeech: "noun / verb",
      definition: "保修承诺；对质量作出的保证",
      definitionEn: "a promise that a product will work or be repaired if it does not",
      collocation: "a money-back guarantee",
      example: "This product comes with a thirty-day money-back guarantee.",
      exampleZh: "这款产品附带三十天退款保证。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "unavailable",
      word: "unavailable",
      phonetic: "/ˌʌnəˈveɪləbl/",
      partOfSpeech: "adjective",
      definition: "暂时无货的；目前无法提供的",
      definitionEn: "not able to be obtained or used at the present time",
      collocation: "currently unavailable",
      example: "The blue model is currently unavailable in this store.",
      exampleZh: "蓝色款目前在本店暂时无货。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "delivery",
      word: "delivery",
      phonetic: "/dɪˈlɪvəri/",
      partOfSpeech: "noun",
      definition: "配送；把商品送到客户手中的过程",
      definitionEn: "the act of taking goods to a customer",
      collocation: "arrange delivery",
      example: "We can arrange delivery for Monday afternoon.",
      exampleZh: "我们可以安排星期一下午配送。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "exchange",
      word: "exchange",
      phonetic: "/ɪksˈtʃeɪndʒ/",
      partOfSpeech: "noun / verb",
      definition: "换货；用一件商品更换另一件",
      definitionEn: "the act of replacing one product with another",
      collocation: "request an exchange",
      example: "The customer requested an exchange for a larger size.",
      exampleZh: "顾客要求换成更大的尺码。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "fault",
      word: "fault",
      phonetic: "/fɔːlt/",
      partOfSpeech: "noun",
      definition: "故障；产品中的问题",
      definitionEn: "a problem in a product that stops it from working correctly",
      collocation: "report a fault",
      example: "Please report the fault and include a photo of the product.",
      exampleZh: "请报告故障，并附上产品照片。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "inspection",
      word: "inspection",
      phonetic: "/ɪnˈspekʃn/",
      partOfSpeech: "noun",
      definition: "检查；为确认质量进行的检验",
      definitionEn: "the process of checking something carefully for quality or problems",
      collocation: "pass an inspection",
      example: "Every returned device goes through an inspection before replacement.",
      exampleZh: "每台退回的设备在更换前都要经过检查。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "charge",
      word: "charge",
      phonetic: "/tʃɑːdʒ/",
      partOfSpeech: "noun",
      definition: "费用；服务收取的金额",
      definitionEn: "an amount of money asked for a service",
      collocation: "a delivery charge",
      example: "There is no delivery charge for orders over fifty dollars.",
      exampleZh: "订单超过五十美元便不收配送费。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "invoice",
      word: "invoice",
      phonetic: "/ˈɪnvɔɪs/",
      partOfSpeech: "noun",
      definition: "发票；列明应付金额的单据",
      definitionEn: "a document listing goods or services and the amount that must be paid",
      collocation: "issue an invoice",
      example: "The accounts team will issue an invoice after delivery.",
      exampleZh: "财务团队会在交货后开具发票。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "payment",
      word: "payment",
      phonetic: "/ˈpeɪmənt/",
      partOfSpeech: "noun",
      definition: "付款；支付的一笔钱",
      definitionEn: "an amount of money paid for goods or services",
      collocation: "process a payment",
      example: "The system could not process the customer's payment.",
      exampleZh: "系统无法处理这位顾客的付款。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "shipment",
      word: "shipment",
      phonetic: "/ˈʃɪpmənt/",
      partOfSpeech: "noun",
      definition: "货运批次；一同运输的一批货物",
      definitionEn: "a quantity of goods that are sent together from one place to another",
      collocation: "track a shipment",
      example: "We tracked the shipment and updated the customer this morning.",
      exampleZh: "我们今天上午跟踪了这批货运，并向客户更新了情况。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "recommend",
      word: "recommend",
      phonetic: "/ˌrekəˈmend/",
      partOfSpeech: "verb",
      definition: "推荐；建议某个合适选择",
      definitionEn: "to suggest that something is suitable for a person",
      collocation: "recommend a product",
      example: "I can recommend a less expensive product with similar features.",
      exampleZh: "我可以推荐一款功能相近但价格更低的产品。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "verify",
      word: "verify",
      phonetic: "/ˈverɪfaɪ/",
      partOfSpeech: "verb",
      definition: "核实；检查信息是否真实",
      definitionEn: "to check that information is true or correct",
      collocation: "verify an account",
      example: "We need to verify your account before changing the address.",
      exampleZh: "更改地址前，我们需要核实您的账户。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "warranty",
      word: "warranty",
      phonetic: "/ˈwɒrənti/",
      partOfSpeech: "noun",
      definition: "保修期；厂家负责维修的期限",
      definitionEn: "a written promise to repair a product within a certain period",
      collocation: "under warranty",
      example: "The laptop is still under warranty, so the repair is free.",
      exampleZh: "这台笔记本电脑仍在保修期内，因此维修免费。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "goal",
      word: "goal",
      phonetic: "/ɡəʊl/",
      partOfSpeech: "noun",
      definition: "目标；努力想要达到的结果",
      definitionEn: "something that a person or team is trying to achieve",
      collocation: "set a clear goal",
      example: "We set a clear goal for the first month of the project.",
      exampleZh: "我们为项目的第一个月设定了明确目标。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "milestone",
      word: "milestone",
      phonetic: "/ˈmaɪlstəʊn/",
      partOfSpeech: "noun",
      definition: "里程碑；项目中的重要节点",
      definitionEn: "an important stage or achievement in a project",
      collocation: "reach a milestone",
      example: "Finishing the first design is an important milestone.",
      exampleZh: "完成第一版设计是一个重要里程碑。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "scope",
      word: "scope",
      phonetic: "/skəʊp/",
      partOfSpeech: "noun",
      definition: "范围；项目涵盖的工作边界",
      definitionEn: "the range of work included in a project",
      collocation: "define the project scope",
      example: "We should define the project scope before estimating the cost.",
      exampleZh: "估算成本前，我们应该明确项目范围。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "requirement",
      word: "requirement",
      phonetic: "/rɪˈkwaɪəmənt/",
      partOfSpeech: "noun",
      definition: "要求；必须满足的条件",
      definitionEn: "something that a project or product must have",
      collocation: "meet a requirement",
      example: "This feature meets the client's main requirement.",
      exampleZh: "这项功能满足了客户的主要要求。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "outcome",
      word: "outcome",
      phonetic: "/ˈaʊtkʌm/",
      partOfSpeech: "noun",
      definition: "成果；行动产生的最终结果",
      definitionEn: "the final result of an activity or process",
      collocation: "a successful outcome",
      example: "Good planning increases the chance of a successful outcome.",
      exampleZh: "良好的规划能提高取得成功成果的可能性。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "risk",
      word: "risk",
      phonetic: "/rɪsk/",
      partOfSpeech: "noun",
      definition: "风险；可能造成问题的因素",
      definitionEn: "a possible problem that may cause loss or delay",
      collocation: "identify a risk",
      example: "The team identified a delivery risk early.",
      exampleZh: "团队很早就发现了一个配送风险。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "launch",
      word: "launch",
      phonetic: "/lɔːntʃ/",
      partOfSpeech: "noun / verb",
      definition: "启动；正式推出项目或产品",
      definitionEn: "to introduce a new project or product officially",
      collocation: "launch a new service",
      example: "We plan to launch the new service in September.",
      exampleZh: "我们计划在九月推出这项新服务。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "review",
      word: "review",
      phonetic: "/rɪˈvjuː/",
      partOfSpeech: "noun / verb",
      definition: "复盘；重新检查工作成果",
      definitionEn: "to examine work again in order to improve or approve it",
      collocation: "review the results",
      example: "Let us review the results before the client meeting.",
      exampleZh: "让我们在客户会议前复盘一下结果。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "approve",
      word: "approve",
      phonetic: "/əˈpruːv/",
      partOfSpeech: "verb",
      definition: "批准；正式同意某项计划",
      definitionEn: "to officially accept or agree to a plan",
      collocation: "approve a plan",
      example: "The client approved the final design this morning.",
      exampleZh: "客户今天上午批准了最终设计。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "revise",
      word: "revise",
      phonetic: "/rɪˈvaɪz/",
      partOfSpeech: "verb",
      definition: "修订；根据意见修改内容",
      definitionEn: "to change something in order to improve or correct it",
      collocation: "revise a draft",
      example: "I revised the draft after receiving the team's comments.",
      exampleZh: "收到团队意见后，我修订了草稿。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "track",
      word: "track",
      phonetic: "/træk/",
      partOfSpeech: "verb",
      definition: "跟踪；持续记录变化",
      definitionEn: "to follow the progress or development of something",
      collocation: "track project progress",
      example: "We use a shared board to track project progress.",
      exampleZh: "我们用共享看板跟踪项目进度。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "estimate",
      word: "estimate",
      phonetic: "/ˈestɪmeɪt/",
      partOfSpeech: "verb",
      definition: "估算；计算大致的数量或时间",
      definitionEn: "to make a reasonable guess about an amount, cost, or time",
      collocation: "estimate the time",
      example: "Can you estimate the time needed for this task?",
      exampleZh: "你能估算完成这项任务所需的时间吗？",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "stage",
      word: "stage",
      phonetic: "/steɪdʒ/",
      partOfSpeech: "noun",
      definition: "阶段；过程中的一个时期",
      definitionEn: "a particular period in the development of a project",
      collocation: "at an early stage",
      example: "The project is still at an early stage.",
      exampleZh: "这个项目仍处于早期阶段。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "partner",
      word: "partner",
      phonetic: "/ˈpɑːtnə(r)/",
      partOfSpeech: "noun",
      definition: "合作伙伴；共同完成工作的人或组织",
      definitionEn: "a person or organization that works with another on a project",
      collocation: "a project partner",
      example: "Our project partner will provide the technical support.",
      exampleZh: "我们的项目合作伙伴将提供技术支持。",
      topic: "项目协作",
      level: "B1"
    },
    {
      id: "priority",
      word: "priority",
      phonetic: "/praɪˈɒrəti/",
      partOfSpeech: "noun",
      definition: "优先事项；需要首先处理的事情",
      definitionEn: "something that is more important than other things",
      collocation: "make something a priority",
      example: "Customer safety must remain our top priority.",
      exampleZh: "客户安全必须始终是我们的首要事项。",
      topic: "项目协作",
      level: "B1"
    }
  ]);
})();
