(function () {
  "use strict";

  window.ENGLISH_COMPASS_EXTRA_VOCABULARY = Object.freeze([
    {
      id: "routine",
      word: "routine",
      phonetic: "/ruːˈtiːn/",
      partOfSpeech: "noun",
      definition: "日常惯例；固定程序",
      definitionEn: "the usual way in which you regularly do things",
      collocation: "follow a daily routine",
      example: "I follow a simple routine before I leave for work.",
      exampleZh: "上班出门前，我会遵循一套简单的日常流程。",
      topic: "日常生活",
      level: "A1"
    },
    {
      id: "breakfast",
      word: "breakfast",
      phonetic: "/ˈbrekfəst/",
      partOfSpeech: "noun",
      definition: "早餐",
      definitionEn: "the first meal of the day",
      collocation: "have breakfast",
      example: "I usually have breakfast at seven o'clock.",
      exampleZh: "我通常七点吃早餐。",
      topic: "日常生活",
      level: "A1"
    },
    {
      id: "neighbor",
      word: "neighbor",
      phonetic: "/ˈneɪbə(r)/",
      partOfSpeech: "noun",
      definition: "邻居",
      definitionEn: "a person who lives near you",
      collocation: "a friendly neighbor",
      example: "My neighbor helped me carry the heavy box.",
      exampleZh: "我的邻居帮我搬了那个重箱子。",
      topic: "日常生活",
      level: "A1"
    },
    {
      id: "laundry",
      word: "laundry",
      phonetic: "/ˈlɔːndri/",
      partOfSpeech: "noun",
      definition: "待洗或洗好的衣物；洗衣",
      definitionEn: "clothes that need washing or have just been washed",
      collocation: "do the laundry",
      example: "I do the laundry every Saturday morning.",
      exampleZh: "我每周六早上洗衣服。",
      topic: "日常生活",
      level: "A2"
    },
    {
      id: "groceries",
      word: "groceries",
      phonetic: "/ˈɡrəʊsəriz/",
      partOfSpeech: "plural noun",
      definition: "食品杂货；生活用品",
      definitionEn: "food and other goods bought for the home",
      collocation: "buy groceries",
      example: "We buy groceries for the week on Sunday.",
      exampleZh: "我们星期日购买一周所需的食品杂货。",
      topic: "日常生活",
      level: "A1"
    },
    {
      id: "appointment",
      word: "appointment",
      phonetic: "/əˈpɔɪntmənt/",
      partOfSpeech: "noun",
      definition: "预约；约定",
      definitionEn: "an arrangement to meet someone at a particular time",
      collocation: "make an appointment",
      example: "I made a doctor's appointment for Friday afternoon.",
      exampleZh: "我预约了星期五下午去看医生。",
      topic: "日常生活",
      level: "A2"
    },
    {
      id: "healthy",
      word: "healthy",
      phonetic: "/ˈhelθi/",
      partOfSpeech: "adjective",
      definition: "健康的；有益健康的",
      definitionEn: "physically well or good for your health",
      collocation: "a healthy meal",
      example: "Walking after dinner is a healthy habit.",
      exampleZh: "晚饭后散步是一个健康的习惯。",
      topic: "日常生活",
      level: "A1"
    },
    {
      id: "habit",
      word: "habit",
      phonetic: "/ˈhæbɪt/",
      partOfSpeech: "noun",
      definition: "习惯",
      definitionEn: "something that you do regularly, often without thinking",
      collocation: "develop a good habit",
      example: "Reading in English has become a daily habit.",
      exampleZh: "阅读英语已经成了我的每日习惯。",
      topic: "日常生活",
      level: "A2"
    },
    {
      id: "prepare",
      word: "prepare",
      phonetic: "/prɪˈpeə(r)/",
      partOfSpeech: "verb",
      definition: "准备",
      definitionEn: "to make something or yourself ready",
      collocation: "prepare dinner",
      example: "I prepare my clothes the night before work.",
      exampleZh: "我会在上班前一晚准备好衣服。",
      topic: "日常生活",
      level: "A1"
    },
    {
      id: "convenient",
      word: "convenient",
      phonetic: "/kənˈviːniənt/",
      partOfSpeech: "adjective",
      definition: "方便的；省事的",
      definitionEn: "easy to use or suitable for your needs",
      collocation: "a convenient location",
      example: "The new supermarket is in a convenient location.",
      exampleZh: "新超市的位置很方便。",
      topic: "日常生活",
      level: "A2"
    },
    {
      id: "household",
      word: "household",
      phonetic: "/ˈhaʊshəʊld/",
      partOfSpeech: "noun / adjective",
      definition: "家庭；家用的",
      definitionEn: "the people living together in one home, or related to the home",
      collocation: "household expenses",
      example: "We keep a monthly record of our household expenses.",
      exampleZh: "我们每月记录家庭开支。",
      topic: "日常生活",
      level: "B1"
    },
    {
      id: "colleague",
      word: "colleague",
      phonetic: "/ˈkɒliːɡ/",
      partOfSpeech: "noun",
      definition: "同事",
      definitionEn: "a person that you work with",
      collocation: "help a colleague",
      example: "A colleague showed me how to use the new system.",
      exampleZh: "一位同事教我如何使用新系统。",
      topic: "职场",
      level: "A2"
    },
    {
      id: "deadline",
      word: "deadline",
      phonetic: "/ˈdedlaɪn/",
      partOfSpeech: "noun",
      definition: "截止期限",
      definitionEn: "the latest time by which something must be completed",
      collocation: "meet a deadline",
      example: "We worked together to meet the project deadline.",
      exampleZh: "我们共同努力，按时完成了项目。",
      topic: "职场",
      level: "B1"
    },
    {
      id: "task",
      word: "task",
      phonetic: "/tɑːsk/",
      partOfSpeech: "noun",
      definition: "任务；工作",
      definitionEn: "a piece of work that must be done",
      collocation: "complete a task",
      example: "I complete each task before starting the next one.",
      exampleZh: "我完成一项任务后再开始下一项。",
      topic: "职场",
      level: "A2"
    },
    {
      id: "meeting",
      word: "meeting",
      phonetic: "/ˈmiːtɪŋ/",
      partOfSpeech: "noun",
      definition: "会议；会面",
      definitionEn: "an occasion when people come together to discuss something",
      collocation: "attend a meeting",
      example: "Our team has a short meeting every Monday.",
      exampleZh: "我们团队每周一开一个短会。",
      topic: "职场",
      level: "A1"
    },
    {
      id: "report",
      word: "report",
      phonetic: "/rɪˈpɔːt/",
      partOfSpeech: "noun / verb",
      definition: "报告；汇报",
      definitionEn: "a written or spoken account that gives information",
      collocation: "write a report",
      example: "I send a weekly report to my supervisor.",
      exampleZh: "我每周向主管提交一份报告。",
      topic: "职场",
      level: "A2"
    },
    {
      id: "supervisor",
      word: "supervisor",
      phonetic: "/ˈsuːpəvaɪzə(r)/",
      partOfSpeech: "noun",
      definition: "主管；监督者",
      definitionEn: "a person who manages the work of other people",
      collocation: "ask a supervisor",
      example: "I asked my supervisor for advice about the problem.",
      exampleZh: "我就这个问题向主管寻求建议。",
      topic: "职场",
      level: "B1"
    },
    {
      id: "workload",
      word: "workload",
      phonetic: "/ˈwɜːkləʊd/",
      partOfSpeech: "noun",
      definition: "工作量",
      definitionEn: "the amount of work that a person has to do",
      collocation: "manage a heavy workload",
      example: "Clear priorities help me manage a heavy workload.",
      exampleZh: "明确的优先级帮助我应对繁重的工作量。",
      topic: "职场",
      level: "B2"
    },
    {
      id: "productive",
      word: "productive",
      phonetic: "/prəˈdʌktɪv/",
      partOfSpeech: "adjective",
      definition: "富有成效的；高产的",
      definitionEn: "achieving useful results in a reasonable amount of time",
      collocation: "a productive day",
      example: "Turning off notifications helps me stay productive.",
      exampleZh: "关闭通知能帮助我保持高效。",
      topic: "职场",
      level: "B1"
    },
    {
      id: "procedure",
      word: "procedure",
      phonetic: "/prəˈsiːdʒə(r)/",
      partOfSpeech: "noun",
      definition: "程序；办事流程",
      definitionEn: "an official or accepted way of doing something",
      collocation: "follow the procedure",
      example: "New employees must follow the safety procedure.",
      exampleZh: "新员工必须遵循安全流程。",
      topic: "职场",
      level: "B1"
    },
    {
      id: "coordinate",
      word: "coordinate",
      phonetic: "/kəʊˈɔːdɪneɪt/",
      partOfSpeech: "verb",
      definition: "协调；统筹",
      definitionEn: "to organize people or activities so that they work together well",
      collocation: "coordinate a project",
      example: "I coordinate deliveries with the sales team.",
      exampleZh: "我与销售团队协调送货事宜。",
      topic: "职场",
      level: "B2"
    },
    {
      id: "resource",
      word: "resource",
      phonetic: "/rɪˈsɔːs/",
      partOfSpeech: "noun",
      definition: "资源；可利用的事物",
      definitionEn: "something useful that helps you achieve a purpose",
      collocation: "use resources wisely",
      example: "We use our limited resources carefully.",
      exampleZh: "我们谨慎使用有限的资源。",
      topic: "职场",
      level: "B1"
    },
    {
      id: "experience",
      word: "experience",
      phonetic: "/ɪkˈspɪəriəns/",
      partOfSpeech: "noun",
      definition: "经验；经历",
      definitionEn: "knowledge or skill gained from doing or seeing something",
      collocation: "gain work experience",
      example: "My part-time job gave me useful customer service experience.",
      exampleZh: "兼职工作给了我实用的客户服务经验。",
      topic: "面试",
      level: "A2"
    },
    {
      id: "strength",
      word: "strength",
      phonetic: "/streŋθ/",
      partOfSpeech: "noun",
      definition: "优势；长处",
      definitionEn: "a quality or ability that someone does well",
      collocation: "a key strength",
      example: "One of my key strengths is careful planning.",
      exampleZh: "我主要的优势之一是做事计划周密。",
      topic: "面试",
      level: "A2"
    },
    {
      id: "qualification",
      word: "qualification",
      phonetic: "/ˌkwɒlɪfɪˈkeɪʃn/",
      partOfSpeech: "noun",
      definition: "资格；资历；资格证书",
      definitionEn: "a skill, quality, or certificate that makes you suitable for a job",
      collocation: "meet the qualifications",
      example: "My training meets the main qualifications for this role.",
      exampleZh: "我的培训经历符合该职位的主要资格要求。",
      topic: "面试",
      level: "B1"
    },
    {
      id: "candidate",
      word: "candidate",
      phonetic: "/ˈkændɪdət/",
      partOfSpeech: "noun",
      definition: "候选人；应聘者",
      definitionEn: "a person who is being considered for a job or position",
      collocation: "a strong candidate",
      example: "I believe my service experience makes me a strong candidate.",
      exampleZh: "我相信自己的服务经验使我成为有竞争力的候选人。",
      topic: "面试",
      level: "B1"
    },
    {
      id: "achievement",
      word: "achievement",
      phonetic: "/əˈtʃiːvmənt/",
      partOfSpeech: "noun",
      definition: "成就；成绩",
      definitionEn: "something important that you succeed in doing",
      collocation: "a proud achievement",
      example: "Completing the project early was a proud achievement.",
      exampleZh: "提前完成项目是一项令我自豪的成就。",
      topic: "面试",
      level: "B1"
    },
    {
      id: "motivation",
      word: "motivation",
      phonetic: "/ˌməʊtɪˈveɪʃn/",
      partOfSpeech: "noun",
      definition: "动力；积极性",
      definitionEn: "the reason or enthusiasm that makes you want to do something",
      collocation: "strong motivation to learn",
      example: "My motivation comes from seeing customers leave satisfied.",
      exampleZh: "看到顾客满意地离开，是我工作的动力。",
      topic: "面试",
      level: "B2"
    },
    {
      id: "suitable",
      word: "suitable",
      phonetic: "/ˈsuːtəbl/",
      partOfSpeech: "adjective",
      definition: "合适的；适宜的",
      definitionEn: "right or appropriate for a particular purpose or person",
      collocation: "suitable for the role",
      example: "My communication skills make me suitable for this role.",
      exampleZh: "我的沟通能力使我适合这个职位。",
      topic: "面试",
      level: "B1"
    },
    {
      id: "hire",
      word: "hire",
      phonetic: "/ˈhaɪə(r)/",
      partOfSpeech: "verb",
      definition: "雇用；聘用",
      definitionEn: "to employ someone for a job",
      collocation: "hire a new employee",
      example: "The company plans to hire two new assistants.",
      exampleZh: "公司计划聘用两名新助理。",
      topic: "面试",
      level: "A2"
    },
    {
      id: "background",
      word: "background",
      phonetic: "/ˈbækɡraʊnd/",
      partOfSpeech: "noun",
      definition: "背景；经历",
      definitionEn: "a person's education, family, and previous experience",
      collocation: "an educational background",
      example: "Let me briefly explain my educational background.",
      exampleZh: "请允许我简要介绍一下我的教育背景。",
      topic: "面试",
      level: "A2"
    },
    {
      id: "demonstrate",
      word: "demonstrate",
      phonetic: "/ˈdemənstreɪt/",
      partOfSpeech: "verb",
      definition: "证明；展示",
      definitionEn: "to show clearly that you have a skill or quality",
      collocation: "demonstrate leadership skills",
      example: "This example demonstrates my ability to solve problems.",
      exampleZh: "这个例子展示了我解决问题的能力。",
      topic: "面试",
      level: "B2"
    },
    {
      id: "customer",
      word: "customer",
      phonetic: "/ˈkʌstəmə(r)/",
      partOfSpeech: "noun",
      definition: "顾客；客户",
      definitionEn: "a person who buys goods or services",
      collocation: "serve a customer",
      example: "I greeted each customer with a smile.",
      exampleZh: "我微笑着迎接每一位顾客。",
      topic: "客户服务",
      level: "A1"
    },
    {
      id: "assist",
      word: "assist",
      phonetic: "/əˈsɪst/",
      partOfSpeech: "verb",
      definition: "帮助；协助",
      definitionEn: "to help someone do something",
      collocation: "assist a customer",
      example: "May I assist you with your order?",
      exampleZh: "需要我协助您处理订单吗？",
      topic: "客户服务",
      level: "A2"
    },
    {
      id: "refund",
      word: "refund",
      phonetic: "/ˈriːfʌnd/",
      partOfSpeech: "noun",
      definition: "退款；退还的钱",
      definitionEn: "money returned to someone because they are not satisfied with a purchase",
      collocation: "request a refund",
      example: "The customer requested a refund for the damaged item.",
      exampleZh: "顾客要求为损坏的商品退款。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "receipt",
      word: "receipt",
      phonetic: "/rɪˈsiːt/",
      partOfSpeech: "noun",
      definition: "收据；小票",
      definitionEn: "a document showing that goods or services have been paid for",
      collocation: "keep the receipt",
      example: "Please keep the receipt in case you need an exchange.",
      exampleZh: "请保留小票，以备需要换货。",
      topic: "客户服务",
      level: "A2"
    },
    {
      id: "patient",
      word: "patient",
      phonetic: "/ˈpeɪʃnt/",
      partOfSpeech: "adjective",
      definition: "有耐心的",
      definitionEn: "able to stay calm while waiting or dealing with difficulty",
      collocation: "be patient with someone",
      example: "Good service staff are patient with confused customers.",
      exampleZh: "优秀的服务人员会耐心对待感到困惑的顾客。",
      topic: "客户服务",
      level: "A2"
    },
    {
      id: "apologize",
      word: "apologize",
      phonetic: "/əˈpɒlədʒaɪz/",
      partOfSpeech: "verb",
      definition: "道歉",
      definitionEn: "to tell someone that you are sorry for a mistake or problem",
      collocation: "apologize for the delay",
      example: "I apologized for the delay and explained the reason.",
      exampleZh: "我为延误道歉，并解释了原因。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "satisfaction",
      word: "satisfaction",
      phonetic: "/ˌsætɪsˈfækʃn/",
      partOfSpeech: "noun",
      definition: "满意；满足",
      definitionEn: "the feeling of being pleased with a service or result",
      collocation: "customer satisfaction",
      example: "Fast responses can improve customer satisfaction.",
      exampleZh: "快速响应可以提高客户满意度。",
      topic: "客户服务",
      level: "B2"
    },
    {
      id: "inquiry",
      word: "inquiry",
      phonetic: "/ɪnˈkwaɪəri/",
      partOfSpeech: "noun",
      definition: "询问；咨询",
      definitionEn: "a request for information",
      collocation: "handle an inquiry",
      example: "I handled the customer's inquiry by phone.",
      exampleZh: "我通过电话处理了顾客的咨询。",
      topic: "客户服务",
      level: "B1"
    },
    {
      id: "courteous",
      word: "courteous",
      phonetic: "/ˈkɜːtiəs/",
      partOfSpeech: "adjective",
      definition: "礼貌的；谦恭的",
      definitionEn: "polite and respectful toward other people",
      collocation: "courteous service",
      example: "We remain courteous even during difficult conversations.",
      exampleZh: "即使在棘手的对话中，我们也会保持礼貌。",
      topic: "客户服务",
      level: "B2"
    },
    {
      id: "solution",
      word: "solution",
      phonetic: "/səˈluːʃn/",
      partOfSpeech: "noun",
      definition: "解决办法；答案",
      definitionEn: "a way of solving a problem",
      collocation: "find a solution",
      example: "Let us find a solution that works for you.",
      exampleZh: "让我们一起找一个适合您的解决办法。",
      topic: "客户服务",
      level: "A2"
    },
    {
      id: "cashier",
      word: "cashier",
      phonetic: "/kæˈʃɪə(r)/",
      partOfSpeech: "noun",
      definition: "收银员",
      definitionEn: "a person whose job is to receive payments in a store",
      collocation: "work as a cashier",
      example: "The cashier gave me the correct change.",
      exampleZh: "收银员找给了我正确的零钱。",
      topic: "零售",
      level: "A1"
    },
    {
      id: "shelf",
      word: "shelf",
      phonetic: "/ʃelf/",
      partOfSpeech: "noun",
      definition: "架子；货架",
      definitionEn: "a flat surface used for holding or displaying things",
      collocation: "put products on a shelf",
      example: "These drinks belong on the top shelf.",
      exampleZh: "这些饮料应该放在最上层货架。",
      topic: "零售",
      level: "A1"
    },
    {
      id: "price",
      word: "price",
      phonetic: "/praɪs/",
      partOfSpeech: "noun",
      definition: "价格；价钱",
      definitionEn: "the amount of money needed to buy something",
      collocation: "check the price",
      example: "Please check the price on the label.",
      exampleZh: "请查看标签上的价格。",
      topic: "零售",
      level: "A1"
    },
    {
      id: "discount",
      word: "discount",
      phonetic: "/ˈdɪskaʊnt/",
      partOfSpeech: "noun",
      definition: "折扣；减价",
      definitionEn: "a reduction in the usual price",
      collocation: "offer a discount",
      example: "Members receive a ten percent discount.",
      exampleZh: "会员可享受九折优惠。",
      topic: "零售",
      level: "A2"
    },
    {
      id: "stock",
      word: "stock",
      phonetic: "/stɒk/",
      partOfSpeech: "noun",
      definition: "库存；现货",
      definitionEn: "goods that a store has available to sell",
      collocation: "run out of stock",
      example: "This size is currently out of stock.",
      exampleZh: "这个尺码目前缺货。",
      topic: "零售",
      level: "B1"
    },
    {
      id: "supplier",
      word: "supplier",
      phonetic: "/səˈplaɪə(r)/",
      partOfSpeech: "noun",
      definition: "供应商",
      definitionEn: "a company or person that provides goods to a business",
      collocation: "contact a supplier",
      example: "We contacted the supplier about the missing boxes.",
      exampleZh: "我们就缺少的箱子联系了供应商。",
      topic: "零售",
      level: "B1"
    },
    {
      id: "purchase",
      word: "purchase",
      phonetic: "/ˈpɜːtʃəs/",
      partOfSpeech: "noun / verb",
      definition: "购买；购得之物",
      definitionEn: "to buy something, or something that has been bought",
      collocation: "make a purchase",
      example: "You can return your purchase within fourteen days.",
      exampleZh: "您可以在十四天内退回所购商品。",
      topic: "零售",
      level: "A2"
    },
    {
      id: "display",
      word: "display",
      phonetic: "/dɪˈspleɪ/",
      partOfSpeech: "noun / verb",
      definition: "陈列；展示",
      definitionEn: "to arrange something so people can see it, or such an arrangement",
      collocation: "create a window display",
      example: "We changed the window display for the summer sale.",
      exampleZh: "我们为夏季促销更换了橱窗陈列。",
      topic: "零售",
      level: "A2"
    },
    {
      id: "barcode",
      word: "barcode",
      phonetic: "/ˈbɑːkəʊd/",
      partOfSpeech: "noun",
      definition: "条形码",
      definitionEn: "a pattern of lines on a product that a machine reads",
      collocation: "scan a barcode",
      example: "The barcode would not scan at the checkout.",
      exampleZh: "结账时这个条形码无法扫描。",
      topic: "零售",
      level: "A2"
    },
    {
      id: "promotion",
      word: "promotion",
      phonetic: "/prəˈməʊʃn/",
      partOfSpeech: "noun",
      definition: "促销活动；晋升",
      definitionEn: "an activity designed to increase sales, or a move to a higher job",
      collocation: "a seasonal promotion",
      example: "The store is running a weekend promotion.",
      exampleZh: "这家商店正在开展周末促销活动。",
      topic: "零售",
      level: "B1"
    },
    {
      id: "ticket",
      word: "ticket",
      phonetic: "/ˈtɪkɪt/",
      partOfSpeech: "noun",
      definition: "票；车票；机票",
      definitionEn: "a document that allows you to travel or enter a place",
      collocation: "buy a ticket",
      example: "I bought a train ticket online.",
      exampleZh: "我在网上买了一张火车票。",
      topic: "旅行",
      level: "A1"
    },
    {
      id: "passport",
      word: "passport",
      phonetic: "/ˈpɑːspɔːt/",
      partOfSpeech: "noun",
      definition: "护照",
      definitionEn: "an official document used when traveling to another country",
      collocation: "show your passport",
      example: "Keep your passport in a safe place.",
      exampleZh: "请把护照放在安全的地方。",
      topic: "旅行",
      level: "A1"
    },
    {
      id: "luggage",
      word: "luggage",
      phonetic: "/ˈlʌɡɪdʒ/",
      partOfSpeech: "noun",
      definition: "行李",
      definitionEn: "bags and cases that you take when traveling",
      collocation: "collect your luggage",
      example: "We collected our luggage after the flight.",
      exampleZh: "航班抵达后，我们领取了行李。",
      topic: "旅行",
      level: "A2"
    },
    {
      id: "departure",
      word: "departure",
      phonetic: "/dɪˈpɑːtʃə(r)/",
      partOfSpeech: "noun",
      definition: "离开；出发",
      definitionEn: "the act or time of leaving a place",
      collocation: "departure time",
      example: "Please arrive two hours before the departure time.",
      exampleZh: "请在出发时间前两小时到达。",
      topic: "旅行",
      level: "A2"
    },
    {
      id: "destination",
      word: "destination",
      phonetic: "/ˌdestɪˈneɪʃn/",
      partOfSpeech: "noun",
      definition: "目的地",
      definitionEn: "the place to which someone is traveling",
      collocation: "reach a destination",
      example: "We reached our destination before sunset.",
      exampleZh: "我们在日落前到达了目的地。",
      topic: "旅行",
      level: "A2"
    },
    {
      id: "reservation",
      word: "reservation",
      phonetic: "/ˌrezəˈveɪʃn/",
      partOfSpeech: "noun",
      definition: "预订；预约",
      definitionEn: "an arrangement to keep a seat, room, or table for someone",
      collocation: "confirm a reservation",
      example: "I called the hotel to confirm our reservation.",
      exampleZh: "我给酒店打电话确认了我们的预订。",
      topic: "旅行",
      level: "A2"
    },
    {
      id: "delay",
      word: "delay",
      phonetic: "/dɪˈleɪ/",
      partOfSpeech: "noun / verb",
      definition: "延误；推迟",
      definitionEn: "a period of waiting, or to make something happen later",
      collocation: "a flight delay",
      example: "The airline announced a one-hour delay.",
      exampleZh: "航空公司宣布航班延误一小时。",
      topic: "旅行",
      level: "A2"
    },
    {
      id: "accommodation",
      word: "accommodation",
      phonetic: "/əˌkɒməˈdeɪʃn/",
      partOfSpeech: "noun",
      definition: "住处；住宿",
      definitionEn: "a place where someone can stay while traveling",
      collocation: "book accommodation",
      example: "We booked affordable accommodation near the station.",
      exampleZh: "我们在车站附近预订了价格合适的住宿。",
      topic: "旅行",
      level: "B1"
    },
    {
      id: "itinerary",
      word: "itinerary",
      phonetic: "/aɪˈtɪnərəri/",
      partOfSpeech: "noun",
      definition: "旅行计划；行程表",
      definitionEn: "a detailed plan of a journey, including places and times",
      collocation: "plan an itinerary",
      example: "Our itinerary includes three cities in five days.",
      exampleZh: "我们的行程包括五天游览三个城市。",
      topic: "旅行",
      level: "B2"
    },
    {
      id: "navigate",
      word: "navigate",
      phonetic: "/ˈnævɪɡeɪt/",
      partOfSpeech: "verb",
      definition: "导航；找到路线",
      definitionEn: "to find and follow a route to a place",
      collocation: "navigate around a city",
      example: "The map helped us navigate around the old town.",
      exampleZh: "地图帮助我们在老城区找到路线。",
      topic: "旅行",
      level: "B1"
    },
    {
      id: "listen",
      word: "listen",
      phonetic: "/ˈlɪsn/",
      partOfSpeech: "verb",
      definition: "听；倾听",
      definitionEn: "to pay attention to a sound or to what someone says",
      collocation: "listen carefully",
      example: "Please listen carefully to the instructions.",
      exampleZh: "请仔细听说明。",
      topic: "沟通",
      level: "A1"
    },
    {
      id: "explain",
      word: "explain",
      phonetic: "/ɪkˈspleɪn/",
      partOfSpeech: "verb",
      definition: "解释；说明",
      definitionEn: "to make something clear by giving details",
      collocation: "explain something clearly",
      example: "Could you explain the process one more time?",
      exampleZh: "您能再解释一遍这个流程吗？",
      topic: "沟通",
      level: "A2"
    },
    {
      id: "message",
      word: "message",
      phonetic: "/ˈmesɪdʒ/",
      partOfSpeech: "noun",
      definition: "消息；口信",
      definitionEn: "a piece of information sent from one person to another",
      collocation: "leave a message",
      example: "I left a message for the store manager.",
      exampleZh: "我给商店经理留了口信。",
      topic: "沟通",
      level: "A1"
    },
    {
      id: "discuss",
      word: "discuss",
      phonetic: "/dɪˈskʌs/",
      partOfSpeech: "verb",
      definition: "讨论；商量",
      definitionEn: "to talk about something with another person or group",
      collocation: "discuss an idea",
      example: "Let us discuss the plan before making a decision.",
      exampleZh: "让我们在做决定前讨论一下这个计划。",
      topic: "沟通",
      level: "A2"
    },
    {
      id: "respond",
      word: "respond",
      phonetic: "/rɪˈspɒnd/",
      partOfSpeech: "verb",
      definition: "回答；回应",
      definitionEn: "to answer or react to someone or something",
      collocation: "respond to an email",
      example: "I respond to customer emails within one business day.",
      exampleZh: "我会在一个工作日内回复客户邮件。",
      topic: "沟通",
      level: "A2"
    },
    {
      id: "interrupt",
      word: "interrupt",
      phonetic: "/ˌɪntəˈrʌpt/",
      partOfSpeech: "verb",
      definition: "打断；中断",
      definitionEn: "to stop someone speaking or something happening for a short time",
      collocation: "interrupt a conversation",
      example: "Try not to interrupt while another person is speaking.",
      exampleZh: "别人说话时尽量不要打断。",
      topic: "沟通",
      level: "B1"
    },
    {
      id: "tone",
      word: "tone",
      phonetic: "/təʊn/",
      partOfSpeech: "noun",
      definition: "语气；口吻",
      definitionEn: "the quality of a voice that shows a person's feelings or attitude",
      collocation: "use a friendly tone",
      example: "A friendly tone makes the message easier to accept.",
      exampleZh: "友好的语气会让信息更容易被接受。",
      topic: "沟通",
      level: "B1"
    },
    {
      id: "persuade",
      word: "persuade",
      phonetic: "/pəˈsweɪd/",
      partOfSpeech: "verb",
      definition: "说服；劝服",
      definitionEn: "to make someone agree to do or believe something",
      collocation: "persuade someone to act",
      example: "The evidence persuaded the team to change its approach.",
      exampleZh: "这些证据说服团队改变了做法。",
      topic: "沟通",
      level: "B2"
    },
    {
      id: "concise",
      word: "concise",
      phonetic: "/kənˈsaɪs/",
      partOfSpeech: "adjective",
      definition: "简明的；言简意赅的",
      definitionEn: "giving necessary information clearly in only a few words",
      collocation: "a concise answer",
      example: "A concise answer is often more effective in an interview.",
      exampleZh: "面试中，简明的回答通常更有效。",
      topic: "沟通",
      level: "B2"
    },
    {
      id: "misunderstanding",
      word: "misunderstanding",
      phonetic: "/ˌmɪsʌndəˈstændɪŋ/",
      partOfSpeech: "noun",
      definition: "误解；误会",
      definitionEn: "a failure to understand someone or something correctly",
      collocation: "avoid a misunderstanding",
      example: "I repeated the details to avoid a misunderstanding.",
      exampleZh: "我重复了细节，以免产生误解。",
      topic: "沟通",
      level: "B1"
    },
    {
      id: "team",
      word: "team",
      phonetic: "/tiːm/",
      partOfSpeech: "noun",
      definition: "团队；小组",
      definitionEn: "a group of people who work together toward a shared goal",
      collocation: "join a team",
      example: "Our team works well together.",
      exampleZh: "我们的团队合作得很好。",
      topic: "团队",
      level: "A1"
    },
    {
      id: "support",
      word: "support",
      phonetic: "/səˈpɔːt/",
      partOfSpeech: "noun / verb",
      definition: "支持；帮助",
      definitionEn: "help or encouragement given to someone",
      collocation: "support a team member",
      example: "We support each other during busy periods.",
      exampleZh: "在繁忙时期，我们会互相支持。",
      topic: "团队",
      level: "A2"
    },
    {
      id: "share",
      word: "share",
      phonetic: "/ʃeə(r)/",
      partOfSpeech: "verb",
      definition: "分享；共同使用",
      definitionEn: "to give part of something to others or use something together",
      collocation: "share an idea",
      example: "Everyone can share an idea at the meeting.",
      exampleZh: "每个人都可以在会上分享一个想法。",
      topic: "团队",
      level: "A1"
    },
    {
      id: "trust",
      word: "trust",
      phonetic: "/trʌst/",
      partOfSpeech: "noun / verb",
      definition: "信任；相信",
      definitionEn: "the belief that someone is honest and dependable",
      collocation: "build trust",
      example: "Open communication helps a team build trust.",
      exampleZh: "坦诚沟通有助于团队建立信任。",
      topic: "团队",
      level: "A2"
    },
    {
      id: "leader",
      word: "leader",
      phonetic: "/ˈliːdə(r)/",
      partOfSpeech: "noun",
      definition: "领导者；负责人",
      definitionEn: "a person who guides or manages a group",
      collocation: "a supportive leader",
      example: "A good leader listens to the whole team.",
      exampleZh: "优秀的领导者会倾听整个团队的意见。",
      topic: "团队",
      level: "A2"
    },
    {
      id: "contribute",
      word: "contribute",
      phonetic: "/kənˈtrɪbjuːt/",
      partOfSpeech: "verb",
      definition: "贡献；出力",
      definitionEn: "to give time, effort, or ideas to help achieve something",
      collocation: "contribute to a project",
      example: "Each person contributed a useful idea to the project.",
      exampleZh: "每个人都为项目贡献了一个有用的想法。",
      topic: "团队",
      level: "B1"
    },
    {
      id: "cooperate",
      word: "cooperate",
      phonetic: "/kəʊˈɒpəreɪt/",
      partOfSpeech: "verb",
      definition: "合作；配合",
      definitionEn: "to work with other people to achieve a shared result",
      collocation: "cooperate with colleagues",
      example: "The two departments cooperated to solve the issue.",
      exampleZh: "两个部门合作解决了这个问题。",
      topic: "团队",
      level: "B1"
    },
    {
      id: "conflict",
      word: "conflict",
      phonetic: "/ˈkɒnflɪkt/",
      partOfSpeech: "noun",
      definition: "冲突；分歧",
      definitionEn: "a serious disagreement between people or groups",
      collocation: "manage a conflict",
      example: "We discussed the facts calmly to manage the conflict.",
      exampleZh: "我们冷静地讨论事实，以处理这场分歧。",
      topic: "团队",
      level: "B1"
    },
    {
      id: "delegate",
      word: "delegate",
      phonetic: "/ˈdelɪɡeɪt/",
      partOfSpeech: "verb",
      definition: "委派；分派任务",
      definitionEn: "to give a task or responsibility to another person",
      collocation: "delegate tasks effectively",
      example: "A manager should delegate tasks according to each person's skills.",
      exampleZh: "管理者应根据每个人的技能合理分派任务。",
      topic: "团队",
      level: "B2"
    },
    {
      id: "accountable",
      word: "accountable",
      phonetic: "/əˈkaʊntəbl/",
      partOfSpeech: "adjective",
      definition: "负有责任的；应作出说明的",
      definitionEn: "responsible for your decisions and expected to explain them",
      collocation: "hold someone accountable",
      example: "Each team member is accountable for the quality of their work.",
      exampleZh: "每位团队成员都要对自己的工作质量负责。",
      topic: "团队",
      level: "B2"
    },
    {
      id: "today",
      word: "today",
      phonetic: "/təˈdeɪ/",
      partOfSpeech: "adverb / noun",
      definition: "今天；今日",
      definitionEn: "on or during the present day",
      collocation: "finish today",
      example: "I need to finish this task today.",
      exampleZh: "我今天需要完成这项任务。",
      topic: "时间管理",
      level: "A1"
    },
    {
      id: "early",
      word: "early",
      phonetic: "/ˈɜːli/",
      partOfSpeech: "adjective / adverb",
      definition: "早的；提前地",
      definitionEn: "before the usual or expected time",
      collocation: "arrive early",
      example: "I arrive early so I can prepare for the day.",
      exampleZh: "我会提前到达，以便为一天的工作做准备。",
      topic: "时间管理",
      level: "A1"
    },
    {
      id: "late",
      word: "late",
      phonetic: "/leɪt/",
      partOfSpeech: "adjective / adverb",
      definition: "迟的；晚的",
      definitionEn: "after the expected or arranged time",
      collocation: "be late for work",
      example: "The bus was late this morning.",
      exampleZh: "今天早上公交车晚点了。",
      topic: "时间管理",
      level: "A1"
    },
    {
      id: "plan",
      word: "plan",
      phonetic: "/plæn/",
      partOfSpeech: "noun / verb",
      definition: "计划；规划",
      definitionEn: "a set of actions for achieving something, or to decide those actions",
      collocation: "make a plan",
      example: "I make a plan for the next day every evening.",
      exampleZh: "我每天晚上都会为第二天制定计划。",
      topic: "时间管理",
      level: "A1"
    },
    {
      id: "urgent",
      word: "urgent",
      phonetic: "/ˈɜːdʒənt/",
      partOfSpeech: "adjective",
      definition: "紧急的；迫切的",
      definitionEn: "needing immediate attention or action",
      collocation: "an urgent request",
      example: "I handle urgent requests before routine paperwork.",
      exampleZh: "我会先处理紧急请求，再做常规文书工作。",
      topic: "时间管理",
      level: "A2"
    },
    {
      id: "focus",
      word: "focus",
      phonetic: "/ˈfəʊkəs/",
      partOfSpeech: "noun / verb",
      definition: "专注；集中注意力",
      definitionEn: "to give your full attention to one thing",
      collocation: "focus on a task",
      example: "I focus on one important task at a time.",
      exampleZh: "我每次专注于一项重要任务。",
      topic: "时间管理",
      level: "A2"
    },
    {
      id: "organize",
      word: "organize",
      phonetic: "/ˈɔːɡənaɪz/",
      partOfSpeech: "verb",
      definition: "组织；整理；安排",
      definitionEn: "to arrange things or activities in a clear and useful way",
      collocation: "organize your work",
      example: "I organize my work with a short checklist.",
      exampleZh: "我用一张简短的清单来安排工作。",
      topic: "时间管理",
      level: "A2"
    },
    {
      id: "reminder",
      word: "reminder",
      phonetic: "/rɪˈmaɪndə(r)/",
      partOfSpeech: "noun",
      definition: "提醒；提示物",
      definitionEn: "something that helps you remember to do something",
      collocation: "set a reminder",
      example: "I set a reminder for every important appointment.",
      exampleZh: "我会为每个重要约会设置提醒。",
      topic: "时间管理",
      level: "A2"
    },
    {
      id: "postpone",
      word: "postpone",
      phonetic: "/pəˈspəʊn/",
      partOfSpeech: "verb",
      definition: "推迟；延期",
      definitionEn: "to arrange for something to happen at a later time",
      collocation: "postpone a meeting",
      example: "We had to postpone the meeting until Thursday.",
      exampleZh: "我们不得不把会议推迟到星期四。",
      topic: "时间管理",
      level: "B1"
    },
    {
      id: "allocate",
      word: "allocate",
      phonetic: "/ˈæləkeɪt/",
      partOfSpeech: "verb",
      definition: "分配；拨出",
      definitionEn: "to give a particular amount of time or resources to a purpose",
      collocation: "allocate time wisely",
      example: "I allocate extra time to complex tasks.",
      exampleZh: "我会为复杂任务分配额外时间。",
      topic: "时间管理",
      level: "B2"
    },
    {
      id: "happy",
      word: "happy",
      phonetic: "/ˈhæpi/",
      partOfSpeech: "adjective",
      definition: "快乐的；满意的",
      definitionEn: "feeling pleased or satisfied",
      collocation: "feel happy about",
      example: "I feel happy when I understand a new sentence.",
      exampleZh: "当我理解一个新句子时，我会感到开心。",
      topic: "情绪与成长",
      level: "A1"
    },
    {
      id: "worried",
      word: "worried",
      phonetic: "/ˈwʌrid/",
      partOfSpeech: "adjective",
      definition: "担心的；焦虑的",
      definitionEn: "feeling anxious about a problem or possible difficulty",
      collocation: "feel worried about",
      example: "I felt worried before my first English interview.",
      exampleZh: "第一次英语面试前，我感到很担心。",
      topic: "情绪与成长",
      level: "A2"
    },
    {
      id: "calm",
      word: "calm",
      phonetic: "/kɑːm/",
      partOfSpeech: "adjective",
      definition: "冷静的；平静的",
      definitionEn: "relaxed and not worried, angry, or excited",
      collocation: "stay calm",
      example: "Taking a slow breath helps me stay calm.",
      exampleZh: "缓慢地深呼吸能帮助我保持冷静。",
      topic: "情绪与成长",
      level: "A2"
    },
    {
      id: "proud",
      word: "proud",
      phonetic: "/praʊd/",
      partOfSpeech: "adjective",
      definition: "自豪的；骄傲的",
      definitionEn: "pleased about something you or someone else has achieved",
      collocation: "be proud of",
      example: "I am proud of the progress I have made.",
      exampleZh: "我为自己取得的进步感到自豪。",
      topic: "情绪与成长",
      level: "A2"
    },
    {
      id: "mistake",
      word: "mistake",
      phonetic: "/mɪˈsteɪk/",
      partOfSpeech: "noun",
      definition: "错误；失误",
      definitionEn: "something done or understood incorrectly",
      collocation: "learn from a mistake",
      example: "Every mistake is a chance to learn.",
      exampleZh: "每个错误都是一次学习机会。",
      topic: "情绪与成长",
      level: "A1"
    },
    {
      id: "progress",
      word: "progress",
      phonetic: "/ˈprəʊɡres/",
      partOfSpeech: "noun",
      definition: "进步；进展",
      definitionEn: "development or improvement toward a goal",
      collocation: "make steady progress",
      example: "Daily practice helps me make steady progress.",
      exampleZh: "每日练习帮助我稳步进步。",
      topic: "情绪与成长",
      level: "A2"
    },
    {
      id: "resilient",
      word: "resilient",
      phonetic: "/rɪˈzɪliənt/",
      partOfSpeech: "adjective",
      definition: "有韧性的；能迅速恢复的",
      definitionEn: "able to recover and continue after difficulties",
      collocation: "remain resilient",
      example: "Resilient learners keep practicing after a difficult day.",
      exampleZh: "有韧性的学习者即使经历困难的一天也会继续练习。",
      topic: "情绪与成长",
      level: "B2"
    },
    {
      id: "reflect",
      word: "reflect",
      phonetic: "/rɪˈflekt/",
      partOfSpeech: "verb",
      definition: "认真思考；反思",
      definitionEn: "to think carefully about an experience or idea",
      collocation: "reflect on your performance",
      example: "I reflect on each practice session and note one improvement.",
      exampleZh: "每次练习后我都会反思，并记下一项进步。",
      topic: "情绪与成长",
      level: "B1"
    },
    {
      id: "challenge",
      word: "challenge",
      phonetic: "/ˈtʃælɪndʒ/",
      partOfSpeech: "noun / verb",
      definition: "挑战；考验",
      definitionEn: "a difficult task that tests your ability",
      collocation: "face a challenge",
      example: "Speaking in public is a challenge I want to overcome.",
      exampleZh: "公开讲话是我想克服的一项挑战。",
      topic: "情绪与成长",
      level: "B1"
    },
    {
      id: "persistent",
      word: "persistent",
      phonetic: "/pəˈsɪstənt/",
      partOfSpeech: "adjective",
      definition: "坚持不懈的；锲而不舍的",
      definitionEn: "continuing firmly even when something is difficult",
      collocation: "a persistent learner",
      example: "A persistent learner practices even when progress feels slow.",
      exampleZh: "坚持不懈的学习者即使感觉进步缓慢也会继续练习。",
      topic: "情绪与成长",
      level: "B2"
    }
  ]);
})();
