(function () {
  "use strict";

  window.ENGLISH_COMPASS_MORE_VOCABULARY_B2 = Object.freeze([
    {
      id: "advancement",
      word: "advancement",
      phonetic: "/ədˈvɑːnsmənt/",
      partOfSpeech: "noun",
      definition: "晋升；职业发展",
      definitionEn: "progress to a more senior or successful position",
      collocation: "career advancement opportunities",
      example: "The company offers clear opportunities for career advancement.",
      exampleZh: "这家公司提供清晰的职业晋升机会。",
      topic: "职业发展",
      level: "B2"
    },
    {
      id: "competency",
      word: "competency",
      phonetic: "/ˈkɒmpɪtənsi/",
      partOfSpeech: "noun",
      definition: "胜任能力；专业能力",
      definitionEn: "an important skill or ability needed to perform a job well",
      collocation: "develop core competencies",
      example: "Digital literacy is now a core competency in many professions.",
      exampleZh: "数字素养如今是许多职业的一项核心胜任能力。",
      topic: "职业发展",
      level: "B2"
    },
    {
      id: "specialize",
      word: "specialize",
      phonetic: "/ˈspeʃəlaɪz/",
      partOfSpeech: "verb",
      definition: "专门从事；专攻",
      definitionEn: "to focus on a particular area of work or knowledge",
      collocation: "specialize in data analysis",
      example: "I plan to specialize in international supply chain management.",
      exampleZh: "我计划专攻国际供应链管理。",
      topic: "职业发展",
      level: "B2"
    },
    {
      id: "transferable",
      word: "transferable",
      phonetic: "/trænsˈfɜːrəbl/",
      partOfSpeech: "adjective",
      definition: "可迁移的；可转用的",
      definitionEn: "able to be used in a different job, situation, or place",
      collocation: "transferable skills",
      example: "Problem-solving and communication are highly transferable skills.",
      exampleZh: "解决问题和沟通都是高度可迁移的技能。",
      topic: "职业发展",
      level: "B2"
    },
    {
      id: "portfolio",
      word: "portfolio",
      phonetic: "/pɔːtˈfəʊliəʊ/",
      partOfSpeech: "noun",
      definition: "作品集；成果档案",
      definitionEn: "a collection of work that shows a person's skills and experience",
      collocation: "build a professional portfolio",
      example: "She built a professional portfolio to demonstrate her design skills.",
      exampleZh: "她制作了专业作品集来展示自己的设计能力。",
      topic: "职业发展",
      level: "B2"
    },
    {
      id: "mentorship",
      word: "mentorship",
      phonetic: "/ˈmentɔːʃɪp/",
      partOfSpeech: "noun",
      definition: "导师指导；师徒辅导",
      definitionEn: "guidance provided by an experienced person to someone less experienced",
      collocation: "receive valuable mentorship",
      example: "Good mentorship helped me make better career decisions.",
      exampleZh: "良好的导师指导帮助我做出了更合适的职业决定。",
      topic: "职业发展",
      level: "B2"
    },
    {
      id: "vocation",
      word: "vocation",
      phonetic: "/vəʊˈkeɪʃn/",
      partOfSpeech: "noun",
      definition: "志业；适合自己的职业",
      definitionEn: "a type of work that a person feels especially suited to do",
      collocation: "find your true vocation",
      example: "Teaching became more than a job; it felt like her true vocation.",
      exampleZh: "教学对她而言不只是一份工作，更像是她真正的志业。",
      topic: "职业发展",
      level: "B2"
    },
    {
      id: "certification",
      word: "certification",
      phonetic: "/ˌsɜːtɪfɪˈkeɪʃn/",
      partOfSpeech: "noun",
      definition: "资格认证；合格证书",
      definitionEn: "an official document proving that a person has a particular skill",
      collocation: "earn a professional certification",
      example: "Earning the certification improved her employment prospects.",
      exampleZh: "获得这项专业认证提升了她的就业前景。",
      topic: "职业发展",
      level: "B2"
    },
    {
      id: "expertise",
      word: "expertise",
      phonetic: "/ˌekspɜːˈtiːz/",
      partOfSpeech: "noun",
      definition: "专业知识；专长",
      definitionEn: "a high level of knowledge or skill in a particular subject",
      collocation: "technical expertise",
      example: "The project requires both technical expertise and business awareness.",
      exampleZh: "这个项目既需要技术专长，也需要商业意识。",
      topic: "职业发展",
      level: "B2"
    },
    {
      id: "trajectory",
      word: "trajectory",
      phonetic: "/trəˈdʒektəri/",
      partOfSpeech: "noun",
      definition: "发展轨迹；演变路线",
      definitionEn: "the way in which a career or situation develops over time",
      collocation: "a promising career trajectory",
      example: "International experience can change the trajectory of your career.",
      exampleZh: "国际经验可以改变你的职业发展轨迹。",
      topic: "职业发展",
      level: "B2"
    },
    {
      id: "revenue",
      word: "revenue",
      phonetic: "/ˈrevənjuː/",
      partOfSpeech: "noun",
      definition: "营业收入；收益",
      definitionEn: "the money that a business receives from selling goods or services",
      collocation: "increase annual revenue",
      example: "Online sales generated nearly half of the company's annual revenue.",
      exampleZh: "线上销售创造了公司近一半的年度营业收入。",
      topic: "商业运营",
      level: "B2"
    },
    {
      id: "expenditure",
      word: "expenditure",
      phonetic: "/ɪkˈspendɪtʃə(r)/",
      partOfSpeech: "noun",
      definition: "支出；花费",
      definitionEn: "the amount of money spent by a person, company, or government",
      collocation: "reduce unnecessary expenditure",
      example: "The finance team identified several areas of unnecessary expenditure.",
      exampleZh: "财务团队发现了几项不必要的支出。",
      topic: "商业运营",
      level: "B2"
    },
    {
      id: "profitability",
      word: "profitability",
      phonetic: "/ˌprɒfɪtəˈbɪləti/",
      partOfSpeech: "noun",
      definition: "盈利能力；收益水平",
      definitionEn: "the ability of a business or activity to produce a profit",
      collocation: "improve long-term profitability",
      example: "Better cost control improved the product's long-term profitability.",
      exampleZh: "更好的成本控制提升了该产品的长期盈利能力。",
      topic: "商业运营",
      level: "B2"
    },
    {
      id: "stakeholder",
      word: "stakeholder",
      phonetic: "/ˈsteɪkhəʊldə(r)/",
      partOfSpeech: "noun",
      definition: "利益相关者",
      definitionEn: "a person or group affected by the decisions of an organization",
      collocation: "consult key stakeholders",
      example: "We consulted key stakeholders before changing the service policy.",
      exampleZh: "在修改服务政策前，我们征求了主要利益相关者的意见。",
      topic: "商业运营",
      level: "B2"
    },
    {
      id: "negotiation",
      word: "negotiation",
      phonetic: "/nɪˌɡəʊʃiˈeɪʃn/",
      partOfSpeech: "noun",
      definition: "谈判；协商过程",
      definitionEn: "a formal discussion intended to produce an agreement",
      collocation: "enter into negotiations",
      example: "Both sides entered the negotiation with clear priorities.",
      exampleZh: "双方都带着明确的优先事项进入谈判。",
      topic: "商业运营",
      level: "B2"
    },
    {
      id: "procurement",
      word: "procurement",
      phonetic: "/prəˈkjʊəmənt/",
      partOfSpeech: "noun",
      definition: "采购；物资取得",
      definitionEn: "the process of obtaining supplies or services for an organization",
      collocation: "the procurement process",
      example: "A transparent procurement process reduces financial risk.",
      exampleZh: "透明的采购流程可以降低财务风险。",
      topic: "商业运营",
      level: "B2"
    },
    {
      id: "logistics",
      word: "logistics",
      phonetic: "/ləˈdʒɪstɪks/",
      partOfSpeech: "plural noun",
      definition: "物流；组织运输工作",
      definitionEn: "the practical organization of transporting and supplying goods",
      collocation: "manage global logistics",
      example: "The logistics team arranged delivery to five regional warehouses.",
      exampleZh: "物流团队安排货物运送到五个地区仓库。",
      topic: "商业运营",
      level: "B2"
    },
    {
      id: "benchmark",
      word: "benchmark",
      phonetic: "/ˈbentʃmɑːk/",
      partOfSpeech: "noun",
      definition: "基准；衡量标准",
      definitionEn: "a standard used to measure the quality or performance of something",
      collocation: "set an industry benchmark",
      example: "The new response time has become an industry benchmark.",
      exampleZh: "新的响应速度已经成为行业基准。",
      topic: "商业运营",
      level: "B2"
    },
    {
      id: "forecast",
      word: "forecast",
      phonetic: "/ˈfɔːkɑːst/",
      partOfSpeech: "noun / verb",
      definition: "预测；预报",
      definitionEn: "a statement about what is likely to happen in the future",
      collocation: "prepare a sales forecast",
      example: "The quarterly sales forecast was more optimistic than expected.",
      exampleZh: "季度销售预测比预期更加乐观。",
      topic: "商业运营",
      level: "B2"
    },
    {
      id: "transaction",
      word: "transaction",
      phonetic: "/trænˈzækʃn/",
      partOfSpeech: "noun",
      definition: "交易；业务往来",
      definitionEn: "an occasion when money or goods are exchanged",
      collocation: "complete a secure transaction",
      example: "Customers receive an email after each online transaction.",
      exampleZh: "顾客完成每笔线上交易后都会收到一封邮件。",
      topic: "商业运营",
      level: "B2"
    },
    {
      id: "evaluate",
      word: "evaluate",
      phonetic: "/ɪˈvæljueɪt/",
      partOfSpeech: "verb",
      definition: "评估；评价",
      definitionEn: "to judge the quality, importance, or effectiveness of something",
      collocation: "evaluate the results",
      example: "We need more data to evaluate the results objectively.",
      exampleZh: "我们需要更多数据来客观评估结果。",
      topic: "分析思维",
      level: "B2"
    },
    {
      id: "interpret",
      word: "interpret",
      phonetic: "/ɪnˈtɜːprɪt/",
      partOfSpeech: "verb",
      definition: "解读；阐释",
      definitionEn: "to explain or understand the meaning of information",
      collocation: "interpret survey data",
      example: "Different departments may interpret the survey data differently.",
      exampleZh: "不同部门可能会以不同方式解读调查数据。",
      topic: "分析思维",
      level: "B2"
    },
    {
      id: "insight",
      word: "insight",
      phonetic: "/ˈɪnsaɪt/",
      partOfSpeech: "noun",
      definition: "洞见；深刻理解",
      definitionEn: "a clear and deep understanding of a complicated situation",
      collocation: "gain valuable insight",
      example: "Customer interviews gave us valuable insight into their needs.",
      exampleZh: "顾客访谈让我们深入了解了他们的需求。",
      topic: "分析思维",
      level: "B2"
    },
    {
      id: "evidence",
      word: "evidence",
      phonetic: "/ˈevɪdəns/",
      partOfSpeech: "noun",
      definition: "证据；依据",
      definitionEn: "facts or information that support a conclusion or belief",
      collocation: "provide convincing evidence",
      example: "The report provides convincing evidence for the proposed change.",
      exampleZh: "这份报告为拟议的改变提供了有力依据。",
      topic: "分析思维",
      level: "B2"
    },
    {
      id: "variable",
      word: "variable",
      phonetic: "/ˈveəriəbl/",
      partOfSpeech: "noun",
      definition: "变量；可变因素",
      definitionEn: "a factor that can change and affect the result of a situation",
      collocation: "control each variable",
      example: "Price was not the only variable affecting customer demand.",
      exampleZh: "价格并不是影响顾客需求的唯一变量。",
      topic: "分析思维",
      level: "B2"
    },
    {
      id: "correlation",
      word: "correlation",
      phonetic: "/ˌkɒrəˈleɪʃn/",
      partOfSpeech: "noun",
      definition: "相关性；相互关系",
      definitionEn: "a connection between two things in which one changes with the other",
      collocation: "a strong correlation between",
      example: "The study found a strong correlation between training and retention.",
      exampleZh: "研究发现培训与员工留任之间存在很强的相关性。",
      topic: "分析思维",
      level: "B2"
    },
    {
      id: "assumption",
      word: "assumption",
      phonetic: "/əˈsʌmpʃn/",
      partOfSpeech: "noun",
      definition: "假设；未经证实的看法",
      definitionEn: "something accepted as true without definite proof",
      collocation: "challenge an assumption",
      example: "The market research challenged our original assumption.",
      exampleZh: "市场调研对我们最初的假设提出了质疑。",
      topic: "分析思维",
      level: "B2"
    },
    {
      id: "criterion",
      word: "criterion",
      phonetic: "/kraɪˈtɪəriən/",
      partOfSpeech: "noun",
      definition: "评判准则；选择条件",
      definitionEn: "a standard used for judging or deciding something",
      collocation: "meet a selection criterion",
      example: "Relevant experience is an important selection criterion.",
      exampleZh: "相关经验是一项重要的选择条件。",
      topic: "分析思维",
      level: "B2"
    },
    {
      id: "trend",
      word: "trend",
      phonetic: "/trend/",
      partOfSpeech: "noun",
      definition: "趋势；变化倾向",
      definitionEn: "a general direction in which a situation is developing",
      collocation: "identify a market trend",
      example: "The data shows a clear trend toward mobile purchasing.",
      exampleZh: "数据显示出向移动端购物发展的明显趋势。",
      topic: "分析思维",
      level: "B2"
    },
    {
      id: "discrepancy",
      word: "discrepancy",
      phonetic: "/dɪˈskrepənsi/",
      partOfSpeech: "noun",
      definition: "不一致；差异",
      definitionEn: "a difference between two things that should be the same",
      collocation: "investigate a discrepancy",
      example: "The auditor investigated a discrepancy in the monthly figures.",
      exampleZh: "审计人员调查了月度数据中的不一致。",
      topic: "分析思维",
      level: "B2"
    },
    {
      id: "strategy",
      word: "strategy",
      phonetic: "/ˈstrætədʒi/",
      partOfSpeech: "noun",
      definition: "战略；行动方案",
      definitionEn: "a detailed plan designed to achieve a particular goal",
      collocation: "develop a long-term strategy",
      example: "The management team developed a strategy for overseas growth.",
      exampleZh: "管理团队制定了海外增长战略。",
      topic: "团队管理",
      level: "B2"
    },
    {
      id: "implement",
      word: "implement",
      phonetic: "/ˈɪmplɪment/",
      partOfSpeech: "verb",
      definition: "实施；执行",
      definitionEn: "to put a plan or decision into effect",
      collocation: "implement a new policy",
      example: "We will implement the new policy gradually over three months.",
      exampleZh: "我们将在三个月内逐步实施新政策。",
      topic: "团队管理",
      level: "B2"
    },
    {
      id: "monitor",
      word: "monitor",
      phonetic: "/ˈmɒnɪtə(r)/",
      partOfSpeech: "verb",
      definition: "监测；持续观察",
      definitionEn: "to watch and check something carefully over a period of time",
      collocation: "monitor team performance",
      example: "Managers monitor performance without interrupting daily work.",
      exampleZh: "管理者在不干扰日常工作的情况下监测团队表现。",
      topic: "团队管理",
      level: "B2"
    },
    {
      id: "empower",
      word: "empower",
      phonetic: "/ɪmˈpaʊə(r)/",
      partOfSpeech: "verb",
      definition: "授权；使有能力",
      definitionEn: "to give someone the authority or confidence to make decisions",
      collocation: "empower employees to decide",
      example: "Good leaders empower employees to solve routine problems independently.",
      exampleZh: "优秀的领导者会授权员工独立解决日常问题。",
      topic: "团队管理",
      level: "B2"
    },
    {
      id: "facilitate",
      word: "facilitate",
      phonetic: "/fəˈsɪlɪteɪt/",
      partOfSpeech: "verb",
      definition: "促进；使更容易",
      definitionEn: "to make an action or process easier",
      collocation: "facilitate effective communication",
      example: "A shared platform can facilitate communication across departments.",
      exampleZh: "共享平台可以促进跨部门沟通。",
      topic: "团队管理",
      level: "B2"
    },
    {
      id: "consensus",
      word: "consensus",
      phonetic: "/kənˈsensəs/",
      partOfSpeech: "noun",
      definition: "共识；一致意见",
      definitionEn: "general agreement among the members of a group",
      collocation: "reach a consensus",
      example: "The team reached a consensus after discussing three alternatives.",
      exampleZh: "团队讨论了三个备选方案后达成了共识。",
      topic: "团队管理",
      level: "B2"
    },
    {
      id: "leadership",
      word: "leadership",
      phonetic: "/ˈliːdəʃɪp/",
      partOfSpeech: "noun",
      definition: "领导力；领导方式",
      definitionEn: "the ability to guide and influence a group of people",
      collocation: "demonstrate strong leadership",
      example: "She demonstrated strong leadership during the service disruption.",
      exampleZh: "服务中断期间，她展现出了强大的领导力。",
      topic: "团队管理",
      level: "B2"
    },
    {
      id: "objective",
      word: "objective",
      phonetic: "/əbˈdʒektɪv/",
      partOfSpeech: "noun",
      definition: "目标；预期成果",
      definitionEn: "a specific result that a person or organization aims to achieve",
      collocation: "set a measurable objective",
      example: "Each department has a measurable objective for the quarter.",
      exampleZh: "每个部门都有一项可衡量的季度目标。",
      topic: "团队管理",
      level: "B2"
    },
    {
      id: "contingency",
      word: "contingency",
      phonetic: "/kənˈtɪndʒənsi/",
      partOfSpeech: "noun",
      definition: "意外情况；应急事件",
      definitionEn: "a possible future event that must be prepared for",
      collocation: "a contingency plan",
      example: "We prepared a contingency plan in case the supplier was delayed.",
      exampleZh: "我们制定了应急计划，以防供应商延迟交货。",
      topic: "团队管理",
      level: "B2"
    },
    {
      id: "streamline",
      word: "streamline",
      phonetic: "/ˈstriːmlaɪn/",
      partOfSpeech: "verb",
      definition: "精简；提高流程效率",
      definitionEn: "to make a process simpler and more efficient",
      collocation: "streamline the approval process",
      example: "The new software streamlined the approval process significantly.",
      exampleZh: "新软件显著精简了审批流程。",
      topic: "团队管理",
      level: "B2"
    },
    {
      id: "articulate",
      word: "articulate",
      phonetic: "/ɑːˈtɪkjuleɪt/",
      partOfSpeech: "verb",
      definition: "清楚表达；明确说明",
      definitionEn: "to express an idea or feeling clearly in words",
      collocation: "articulate your ideas clearly",
      example: "She articulated her reasons for applying clearly and confidently.",
      exampleZh: "她清晰而自信地说明了申请这个职位的原因。",
      topic: "求职面试",
      level: "B2"
    },
    {
      id: "accomplishment",
      word: "accomplishment",
      phonetic: "/əˈkʌmplɪʃmənt/",
      partOfSpeech: "noun",
      definition: "工作成果；完成的成就",
      definitionEn: "something successful that has been achieved through effort",
      collocation: "describe a major accomplishment",
      example: "My proudest accomplishment was improving the response process.",
      exampleZh: "我最自豪的工作成果是改进了响应流程。",
      topic: "求职面试",
      level: "B2"
    },
    {
      id: "enthusiasm",
      word: "enthusiasm",
      phonetic: "/ɪnˈθjuːziæzəm/",
      partOfSpeech: "noun",
      definition: "热忱；积极性",
      definitionEn: "a strong feeling of interest and excitement about something",
      collocation: "show genuine enthusiasm",
      example: "Show genuine enthusiasm without speaking too quickly.",
      exampleZh: "展现真诚的热忱，但不要说得太快。",
      topic: "求职面试",
      level: "B2"
    },
    {
      id: "flexibility",
      word: "flexibility",
      phonetic: "/ˌfleksəˈbɪləti/",
      partOfSpeech: "noun",
      definition: "灵活性；适应变化的能力",
      definitionEn: "the ability to change or adapt when circumstances change",
      collocation: "demonstrate flexibility",
      example: "My experience in retail taught me flexibility during busy periods.",
      exampleZh: "零售工作经历培养了我在繁忙时期灵活应变的能力。",
      topic: "求职面试",
      level: "B2"
    },
    {
      id: "potential",
      word: "potential",
      phonetic: "/pəˈtenʃl/",
      partOfSpeech: "noun",
      definition: "潜力；发展可能性",
      definitionEn: "the ability to develop and succeed in the future",
      collocation: "demonstrate your potential",
      example: "The internship allowed me to demonstrate my potential.",
      exampleZh: "这次实习让我有机会展现自己的潜力。",
      topic: "求职面试",
      level: "B2"
    },
    {
      id: "expectation",
      word: "expectation",
      phonetic: "/ˌekspekˈteɪʃn/",
      partOfSpeech: "noun",
      definition: "期望；预期要求",
      definitionEn: "a belief about what should happen or how someone should behave",
      collocation: "clarify role expectations",
      example: "I would like to understand your expectations for the first month.",
      exampleZh: "我想了解您对入职第一个月的期望。",
      topic: "求职面试",
      level: "B2"
    },
    {
      id: "weakness",
      word: "weakness",
      phonetic: "/ˈwiːknəs/",
      partOfSpeech: "noun",
      definition: "弱点；有待改善之处",
      definitionEn: "a quality or ability that is less strong and needs improvement",
      collocation: "address a weakness",
      example: "When discussing a weakness, explain how you are improving it.",
      exampleZh: "谈到弱点时，要说明你正在如何改善它。",
      topic: "求职面试",
      level: "B2"
    },
    {
      id: "relevant",
      word: "relevant",
      phonetic: "/ˈreləvənt/",
      partOfSpeech: "adjective",
      definition: "相关的；切合要求的",
      definitionEn: "directly connected with the subject or situation being discussed",
      collocation: "relevant work experience",
      example: "Focus on the experience that is most relevant to the role.",
      exampleZh: "重点介绍与该职位最相关的工作经历。",
      topic: "求职面试",
      level: "B2"
    },
    {
      id: "impression",
      word: "impression",
      phonetic: "/ɪmˈpreʃn/",
      partOfSpeech: "noun",
      definition: "印象；感受",
      definitionEn: "an opinion or feeling formed about someone or something",
      collocation: "make a positive impression",
      example: "A concise introduction can make a positive first impression.",
      exampleZh: "简洁的自我介绍可以留下良好的第一印象。",
      topic: "求职面试",
      level: "B2"
    },
    {
      id: "commitment",
      word: "commitment",
      phonetic: "/kəˈmɪtmənt/",
      partOfSpeech: "noun",
      definition: "投入；坚定承诺",
      definitionEn: "a strong willingness to give time and effort to something",
      collocation: "show commitment to learning",
      example: "Regular practice shows my commitment to continuous learning.",
      exampleZh: "规律练习体现了我对持续学习的投入。",
      topic: "求职面试",
      level: "B2"
    },
    {
      id: "diversity",
      word: "diversity",
      phonetic: "/daɪˈvɜːsəti/",
      partOfSpeech: "noun",
      definition: "多样性；差异共存",
      definitionEn: "the presence of people or things with many different qualities",
      collocation: "value cultural diversity",
      example: "Cultural diversity brings a wider range of ideas to the team.",
      exampleZh: "文化多样性为团队带来了更广泛的想法。",
      topic: "跨文化沟通",
      level: "B2"
    },
    {
      id: "inclusive",
      word: "inclusive",
      phonetic: "/ɪnˈkluːsɪv/",
      partOfSpeech: "adjective",
      definition: "包容的；兼顾各方的",
      definitionEn: "welcoming and respecting people with different backgrounds or needs",
      collocation: "create an inclusive workplace",
      example: "An inclusive workplace encourages everyone to contribute ideas.",
      exampleZh: "包容的职场会鼓励每个人贡献想法。",
      topic: "跨文化沟通",
      level: "B2"
    },
    {
      id: "etiquette",
      word: "etiquette",
      phonetic: "/ˈetɪket/",
      partOfSpeech: "noun",
      definition: "礼仪；行为规范",
      definitionEn: "the formal rules of polite behavior in a society or profession",
      collocation: "understand business etiquette",
      example: "Business etiquette differs considerably between countries.",
      exampleZh: "不同国家的商务礼仪有很大差异。",
      topic: "跨文化沟通",
      level: "B2"
    },
    {
      id: "stereotype",
      word: "stereotype",
      phonetic: "/ˈsteriətaɪp/",
      partOfSpeech: "noun",
      definition: "刻板印象；固定成见",
      definitionEn: "a fixed and oversimplified idea about a type of person or thing",
      collocation: "challenge a cultural stereotype",
      example: "Direct experience often challenges cultural stereotypes.",
      exampleZh: "亲身经历往往能打破文化刻板印象。",
      topic: "跨文化沟通",
      level: "B2"
    },
    {
      id: "perspective",
      word: "perspective",
      phonetic: "/pəˈspektɪv/",
      partOfSpeech: "noun",
      definition: "视角；看问题的方式",
      definitionEn: "a particular way of thinking about or viewing a situation",
      collocation: "consider another perspective",
      example: "Try to understand the issue from your colleague's perspective.",
      exampleZh: "试着从同事的视角理解这个问题。",
      topic: "跨文化沟通",
      level: "B2"
    },
    {
      id: "sensitivity",
      word: "sensitivity",
      phonetic: "/ˌsensəˈtɪvəti/",
      partOfSpeech: "noun",
      definition: "体察力；文化敏感度",
      definitionEn: "awareness of other people's feelings, customs, and needs",
      collocation: "show cultural sensitivity",
      example: "International managers need a high degree of cultural sensitivity.",
      exampleZh: "国际管理者需要具备很高的文化体察力。",
      topic: "跨文化沟通",
      level: "B2"
    },
    {
      id: "nonverbal",
      word: "nonverbal",
      phonetic: "/ˌnɒnˈvɜːbl/",
      partOfSpeech: "adjective",
      definition: "非语言的；不用言语表达的",
      definitionEn: "communicating without spoken or written words",
      collocation: "nonverbal communication",
      example: "Nonverbal signals may have different meanings across cultures.",
      exampleZh: "非语言信号在不同文化中可能有不同含义。",
      topic: "跨文化沟通",
      level: "B2"
    },
    {
      id: "hierarchy",
      word: "hierarchy",
      phonetic: "/ˈhaɪərɑːki/",
      partOfSpeech: "noun",
      definition: "等级制度；层级结构",
      definitionEn: "a system in which people are ranked according to authority or status",
      collocation: "a formal workplace hierarchy",
      example: "Some workplaces have a more formal hierarchy than others.",
      exampleZh: "有些职场的等级制度比其他职场更正式。",
      topic: "跨文化沟通",
      level: "B2"
    },
    {
      id: "context",
      word: "context",
      phonetic: "/ˈkɒntekst/",
      partOfSpeech: "noun",
      definition: "语境；背景情境",
      definitionEn: "the situation and circumstances that help explain meaning",
      collocation: "understand the cultural context",
      example: "A phrase can sound polite or rude depending on the context.",
      exampleZh: "同一句话根据语境不同，听起来可能礼貌也可能无礼。",
      topic: "跨文化沟通",
      level: "B2"
    },
    {
      id: "compromise",
      word: "compromise",
      phonetic: "/ˈkɒmprəmaɪz/",
      partOfSpeech: "noun / verb",
      definition: "妥协；折中方案",
      definitionEn: "an agreement in which each side accepts less than it originally wanted",
      collocation: "reach a reasonable compromise",
      example: "The two teams reached a compromise on the meeting schedule.",
      exampleZh: "两个团队就会议时间安排达成了折中方案。",
      topic: "跨文化沟通",
      level: "B2"
    }
  ]);
})();
